//! The timezone model: php's three `timezone_type` shapes, offset lookup
//! through the IANA database, and the local-time → timestamp resolution rule
//! php uses across a DST transition.

use jiff::tz::{AmbiguousOffset, TimeZone};
use jiff::Timestamp;

/// A php timezone, in the three shapes `timezone_type` names.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum Tz {
    /// `timezone_type` 1 — a fixed offset in seconds east of UTC.
    Offset(i32),
    /// `timezone_type` 2 — an abbreviation with its fixed offset and DST flag.
    Abbr {
        name: String,
        offset: i32,
        dst: bool,
    },
    /// `timezone_type` 3 — an IANA identifier, kept with the spelling the
    /// caller used: php echoes `new DateTimeZone("europe/BERLIN")->getName()`
    /// back verbatim.
    Id(String),
}

impl Tz {
    /// php's `timezone_type`.
    pub(crate) fn type_id(&self) -> i64 {
        match self {
            Tz::Offset(_) => 1,
            Tz::Abbr { .. } => 2,
            Tz::Id(_) => 3,
        }
    }

    /// php's `DateTimeZone::getName()` and the `e` format character.
    pub(crate) fn name(&self) -> String {
        match self {
            Tz::Offset(secs) => render_offset(*secs),
            Tz::Abbr { name, .. } => name.clone(),
            Tz::Id(id) => id.clone(),
        }
    }

    /// UTC.
    pub(crate) fn utc() -> Tz {
        Tz::Id("UTC".to_string())
    }

    /// The offset, abbreviation (`T`) and DST flag (`I`) in force at `ts`.
    pub(crate) fn info(&self, ts: i64) -> (i32, String, bool) {
        match self {
            Tz::Offset(secs) => (*secs, gmt_abbr(*secs), false),
            Tz::Abbr { name, offset, dst } => (*offset, name.clone(), *dst),
            Tz::Id(id) => match TimeZone::get(id) {
                Ok(tz) => {
                    let info = tz.to_offset_info(clamp_ts(ts));
                    (
                        info.offset().seconds(),
                        info.abbreviation().to_string(),
                        info.dst().is_dst(),
                    )
                }
                // Unreachable for a `Tz::Id` that came through `parse`, which
                // only builds one after the database accepted the name.
                Err(_) => (0, "UTC".to_string(), false),
            },
        }
    }

    /// The offset in force at `ts`.
    pub(crate) fn offset_at(&self, ts: i64) -> i32 {
        self.info(ts).0
    }

    /// The timestamp of a local wall-clock time, given as `sse` — the civil
    /// datetime read as if it were UTC (php's "seconds since epoch" of an
    /// unresolved `timelib_time`).
    ///
    /// Across a DST transition php is not simply "earlier" or "later":
    ///
    /// * a **gap** (spring forward) takes the offset from *before* the
    ///   transition, so `2021-03-28 02:30` in `Europe/Berlin` becomes
    ///   `03:30+02:00`;
    /// * an **overlap** (fall back) takes `prefer` when it is one of the two
    ///   candidates — that is the offset the `DateTime` already carried, which
    ///   is why `$d->modify(…)` and `mktime()` can land on a different
    ///   instant than `strtotime()` for the same wall clock — and otherwise
    ///   the offset in force at `sse` itself, which is what a fresh parse
    ///   does.
    pub(crate) fn resolve(&self, sse: i64, prefer: Option<i32>) -> i64 {
        match self {
            Tz::Offset(secs) => sse - *secs as i64,
            Tz::Abbr { offset, .. } => sse - *offset as i64,
            Tz::Id(id) => {
                let Ok(tz) = TimeZone::get(id) else {
                    return sse;
                };
                let (y, mo, d) = super::civil::civil_from_days(sse.div_euclid(86_400));
                let rem = sse.rem_euclid(86_400);
                let dt = i16::try_from(y).ok().and_then(|y| {
                    jiff::civil::DateTime::new(
                        y,
                        mo as i8,
                        d as i8,
                        (rem / 3600) as i8,
                        ((rem / 60) % 60) as i8,
                        (rem % 60) as i8,
                        0,
                    )
                    .ok()
                });
                // Outside the database's year range there are no transitions
                // to reason about; take the offset the zone reports there.
                let Some(dt) = dt else {
                    return sse - self.offset_at(sse) as i64;
                };
                let offset = match tz.to_ambiguous_timestamp(dt).offset() {
                    AmbiguousOffset::Unambiguous { offset } => offset.seconds(),
                    AmbiguousOffset::Gap { before, .. } => before.seconds(),
                    AmbiguousOffset::Fold { before, after } => {
                        let (b, a) = (before.seconds(), after.seconds());
                        match prefer {
                            Some(p) if p == b || p == a => p,
                            _ => {
                                let at_sse = self.offset_at(sse);
                                if at_sse == b || at_sse == a {
                                    at_sse
                                } else {
                                    a
                                }
                            }
                        }
                    }
                };
                sse - offset as i64
            }
        }
    }

    /// php's `DateTimeZone::__construct()`: an offset, then an abbreviation,
    /// then an IANA identifier. `UTC` is the one abbreviation php resolves as
    /// an identifier instead (`timezone_type` 3).
    pub(crate) fn parse(s: &str) -> Option<Tz> {
        if let Some(secs) = parse_offset(s) {
            return Some(Tz::Offset(secs));
        }
        if s.eq_ignore_ascii_case("utc") {
            return Some(Tz::Id(s.to_string()));
        }
        if let Some((offset, dst)) = lookup_abbr(s) {
            return Some(Tz::Abbr {
                name: s.to_string(),
                offset,
                dst,
            });
        }
        if is_known_id(s) {
            return Some(Tz::Id(s.to_string()));
        }
        None
    }
}

/// Whether php's database knows `name` (case-insensitively, as php matches
/// it): `date_default_timezone_set` accepts exactly these, abbreviations
/// included only when tzdata ships a zone of that name — `CET` yes, `Z` no.
/// The platform database is not asked, because it carries names php's
/// snapshot does not.
pub(crate) fn is_known_id(name: &str) -> bool {
    !name.is_empty()
        && IDENTIFIERS
            .iter()
            .any(|(id, _, _)| id.eq_ignore_ascii_case(name))
}

/// A timestamp the zone database can be asked about.
///
/// php extrapolates a zone's last rule forwards for ever, so `date("T",
/// 1e17)` in `Europe/Berlin` is still `CEST` in September. jiff's calendar
/// stops at year 9999, so a timestamp past that is moved back whole
/// 400-year Gregorian cycles: 146 097 days is exactly 20 871 weeks, so the
/// weekday and the day of the month — everything a DST rule keys on — are
/// unchanged. Before the first transition a zone has one constant offset, so
/// a timestamp below the range is simply clamped.
fn clamp_ts(ts: i64) -> Timestamp {
    /// 0001-01-01T00:00:00Z.
    const LOW: i64 = -62_135_596_800;
    /// 9000-01-01T00:00:00Z, comfortably inside jiff's range.
    const HIGH: i64 = 221_845_046_400;
    /// 400 Gregorian years.
    const CYCLE: i64 = 12_622_780_800;
    let ts = if ts > HIGH {
        ts - ((ts - HIGH + CYCLE - 1) / CYCLE) * CYCLE
    } else {
        ts.max(LOW)
    };
    Timestamp::from_second(ts).unwrap_or(if ts < 0 {
        Timestamp::MIN
    } else {
        Timestamp::MAX
    })
}

/// `+05:30`, `-08:00`, `+01:00:30` — php prints the seconds only when they
/// are not zero.
pub(crate) fn render_offset(secs: i32) -> String {
    let sign = if secs < 0 { '-' } else { '+' };
    let a = secs.unsigned_abs();
    let (h, m, s) = (a / 3600, (a / 60) % 60, a % 60);
    if s == 0 {
        format!("{sign}{h:02}:{m:02}")
    } else {
        format!("{sign}{h:02}:{m:02}:{s:02}")
    }
}

/// The `T` of a fixed-offset zone: `GMT+0530`.
fn gmt_abbr(secs: i32) -> String {
    let sign = if secs < 0 { '-' } else { '+' };
    let a = secs.unsigned_abs();
    format!("GMT{sign}{:02}{:02}", a / 3600, (a / 60) % 60)
}

/// `+5`, `+05`, `+0530`, `+05:30`, `+01:00:30` and the `GMT`-prefixed forms
/// (php accepts the prefix only in upper case).
pub(crate) fn parse_offset(s: &str) -> Option<i32> {
    let body = s.strip_prefix("GMT").unwrap_or(s);
    let (sign, rest) = match body.as_bytes().first()? {
        b'+' => (1i32, &body[1..]),
        b'-' => (-1i32, &body[1..]),
        _ => return None,
    };
    let digits: Vec<u8> = rest.bytes().filter(|b| *b != b':').collect();
    if digits.is_empty() || digits.len() > 6 || !digits.iter().all(|b| b.is_ascii_digit()) {
        return None;
    }
    // `:`-separated fields are h[:m[:s]]; a bare run is HH, HHMM or HHMMSS.
    let (h, m, sec) = if rest.contains(':') {
        let mut it = rest.split(':');
        let h: i32 = it.next()?.parse().ok()?;
        let m: i32 = it.next().map_or(Some(0), |v| v.parse().ok())?;
        let sec: i32 = it.next().map_or(Some(0), |v| v.parse().ok())?;
        if it.next().is_some() {
            return None;
        }
        (h, m, sec)
    } else {
        let n = |a: usize, b: usize| -> i32 {
            digits[a..b]
                .iter()
                .fold(0, |acc, d| acc * 10 + (d - b'0') as i32)
        };
        match digits.len() {
            1 | 2 => (n(0, digits.len()), 0, 0),
            3 => (n(0, 1), n(1, 3), 0),
            4 => (n(0, 2), n(2, 4), 0),
            5 => (n(0, 1), n(1, 3), n(3, 5)),
            6 => (n(0, 2), n(2, 4), n(4, 6)),
            _ => return None,
        }
    };
    if m > 59 || sec > 59 {
        return None;
    }
    Some(sign * (h * 3600 + m * 60 + sec))
}

/// A timezone abbreviation's offset and DST flag, case-insensitively.
pub(crate) fn lookup_abbr(name: &str) -> Option<(i32, bool)> {
    let lower = name.to_ascii_lowercase();
    ABBREVIATIONS
        .iter()
        .find(|(n, _, _)| *n == lower)
        .map(|(_, off, dst)| (*off, *dst))
}

/// php's timezone abbreviations, each with the offset and DST flag its first
/// `timezone_abbreviations_list()` entry carries — the resolution php's own
/// parser applies to `"2021-07-01 12:00:00 CET"`.
#[rustfmt::skip]
static ABBREVIATIONS: &[(&str, i32, bool)] = &[
    ("a", 3600, false),
    ("acdt", 37800, true),
    ("acst", 34200, false),
    ("addt", -7200, true),
    ("adt", -10800, true),
    ("aedt", 39600, true),
    ("aest", 36000, false),
    ("ahdt", -32400, true),
    ("ahst", -36000, false),
    ("akdt", -28800, true),
    ("akst", -32400, false),
    ("amt", -13840, false),
    ("apt", -10800, true),
    ("ast", -14400, false),
    ("awdt", 32400, true),
    ("awst", 28800, false),
    ("awt", -10800, true),
    ("b", 7200, false),
    ("bdst", 7200, true),
    ("bdt", -36000, true),
    ("bmt", -14309, false),
    ("bst", 3600, true),
    ("c", 10800, false),
    ("cast", 34200, false),
    ("cat", 7200, false),
    ("cddt", -14400, true),
    ("cdt", -18000, true),
    ("cemt", 10800, true),
    ("cest", 7200, true),
    ("cet", 3600, false),
    ("chst", 36000, false),
    ("cmt", -15408, false),
    ("cpt", -18000, true),
    ("cst", -21600, false),
    ("cwt", -18000, true),
    ("d", 14400, false),
    ("dmt", -1521, false),
    ("e", 18000, false),
    ("eat", 10800, false),
    ("eddt", -10800, true),
    ("edt", -14400, true),
    ("eest", 10800, true),
    ("eet", 7200, false),
    ("emt", -26248, false),
    ("ept", -14400, true),
    ("est", -18000, false),
    ("ewt", -14400, true),
    ("f", 21600, false),
    ("ffmt", -14660, false),
    ("fmt", -4056, false),
    ("g", 25200, false),
    ("gdt", 39600, true),
    ("gmt", 0, false),
    ("gst", 36000, false),
    ("h", 28800, false),
    ("hdt", -34200, true),
    ("hkst", 32400, true),
    ("hkt", 28800, false),
    ("hmt", -19776, false),
    ("hpt", -34200, true),
    ("hst", -36000, false),
    ("hwt", -34200, true),
    ("i", 32400, false),
    ("iddt", 14400, true),
    ("idt", 10800, true),
    ("imt", 25025, false),
    ("ist", 7200, false),
    ("jdt", 36000, true),
    ("jmt", 8440, false),
    ("jst", 32400, false),
    ("k", 36000, false),
    ("kdt", 36000, true),
    ("kmt", 5736, false),
    ("kst", 30600, false),
    ("l", 39600, false),
    ("lst", 9394, true),
    ("m", 43200, false),
    ("mddt", -18000, true),
    ("mdst", 16279, true),
    ("mdt", -21600, true),
    ("mest", 7200, true),
    ("met", 3600, false),
    ("mmt", 9017, false),
    ("mpt", -21600, true),
    ("msd", 14400, true),
    ("msk", 10800, false),
    ("mst", -25200, false),
    ("mwt", -21600, true),
    ("n", -3600, false),
    ("nddt", -5400, true),
    ("ndt", -9052, true),
    ("npt", -9000, true),
    ("nst", -12600, false),
    ("nwt", -9000, true),
    ("nzdt", 46800, true),
    ("nzmt", 41400, false),
    ("nzst", 43200, false),
    ("o", -7200, false),
    ("p", -10800, false),
    ("pddt", -21600, true),
    ("pdt", -25200, true),
    ("pkst", 21600, true),
    ("pkt", 18000, false),
    ("plmt", 25590, false),
    ("pmt", -13236, false),
    ("ppmt", -17340, false),
    ("ppt", -25200, true),
    ("pst", -28800, false),
    ("pwt", -25200, true),
    ("q", -14400, false),
    ("qmt", -18840, false),
    ("r", -18000, false),
    ("rmt", 5794, false),
    ("s", -21600, false),
    ("sast", 7200, false),
    ("sdmt", -16800, false),
    ("sjmt", -20173, false),
    ("smt", -13884, false),
    ("sst", -39600, false),
    ("t", -25200, false),
    ("tbmt", 10751, false),
    ("tmt", 12344, false),
    ("u", -28800, false),
    ("uct", 0, false),
    ("utc", 0, false),
    ("v", -32400, false),
    ("w", -36000, false),
    ("wast", 7200, true),
    ("wat", 3600, false),
    ("wemt", 7200, true),
    ("west", 3600, true),
    ("wet", 0, false),
    ("wib", 25200, false),
    ("wit", 32400, false),
    ("wita", 28800, false),
    ("wmt", 5040, false),
    ("x", -39600, false),
    ("y", -43200, false),
    ("yddt", -25200, true),
    ("ydt", -28800, true),
    ("ypt", -28800, true),
    ("yst", -32400, false),
    ("ywt", -28800, true),
    ("z", 0, false),
];

// ---- php's bundled timezone database ------------------------------------------

/// Every timezone identifier php's bundled database carries, in the order
/// `timezone_identifiers_list()` returns them: the identifier, its ISO 3166-1
/// country code (`??` when the database records none), and whether it belongs
/// to the backward-compatibility set that only `DateTimeZone::ALL_WITH_BC`
/// includes. The list is php's own, not the host's: php ships a tzdata
/// snapshot, so asking the platform database here would answer with a
/// different set of names in a different order.
#[rustfmt::skip]
pub(crate) static IDENTIFIERS: &[(&str, &str, bool)] = &[
    ("Africa/Abidjan", "CI", false),
    ("Africa/Accra", "GH", false),
    ("Africa/Addis_Ababa", "ET", false),
    ("Africa/Algiers", "DZ", false),
    ("Africa/Asmara", "ER", false),
    ("Africa/Asmera", "??", true),
    ("Africa/Bamako", "ML", false),
    ("Africa/Bangui", "CF", false),
    ("Africa/Banjul", "GM", false),
    ("Africa/Bissau", "GW", false),
    ("Africa/Blantyre", "MW", false),
    ("Africa/Brazzaville", "CG", false),
    ("Africa/Bujumbura", "BI", false),
    ("Africa/Cairo", "EG", false),
    ("Africa/Casablanca", "MA", false),
    ("Africa/Ceuta", "ES", false),
    ("Africa/Conakry", "GN", false),
    ("Africa/Dakar", "SN", false),
    ("Africa/Dar_es_Salaam", "TZ", false),
    ("Africa/Djibouti", "DJ", false),
    ("Africa/Douala", "CM", false),
    ("Africa/El_Aaiun", "EH", false),
    ("Africa/Freetown", "SL", false),
    ("Africa/Gaborone", "BW", false),
    ("Africa/Harare", "ZW", false),
    ("Africa/Johannesburg", "ZA", false),
    ("Africa/Juba", "SS", false),
    ("Africa/Kampala", "UG", false),
    ("Africa/Khartoum", "SD", false),
    ("Africa/Kigali", "RW", false),
    ("Africa/Kinshasa", "CD", false),
    ("Africa/Lagos", "NG", false),
    ("Africa/Libreville", "GA", false),
    ("Africa/Lome", "TG", false),
    ("Africa/Luanda", "AO", false),
    ("Africa/Lubumbashi", "CD", false),
    ("Africa/Lusaka", "ZM", false),
    ("Africa/Malabo", "GQ", false),
    ("Africa/Maputo", "MZ", false),
    ("Africa/Maseru", "LS", false),
    ("Africa/Mbabane", "SZ", false),
    ("Africa/Mogadishu", "SO", false),
    ("Africa/Monrovia", "LR", false),
    ("Africa/Nairobi", "KE", false),
    ("Africa/Ndjamena", "TD", false),
    ("Africa/Niamey", "NE", false),
    ("Africa/Nouakchott", "MR", false),
    ("Africa/Ouagadougou", "BF", false),
    ("Africa/Porto-Novo", "BJ", false),
    ("Africa/Sao_Tome", "ST", false),
    ("Africa/Timbuktu", "??", true),
    ("Africa/Tripoli", "LY", false),
    ("Africa/Tunis", "TN", false),
    ("Africa/Windhoek", "NA", false),
    ("America/Adak", "US", false),
    ("America/Anchorage", "US", false),
    ("America/Anguilla", "AI", false),
    ("America/Antigua", "AG", false),
    ("America/Araguaina", "BR", false),
    ("America/Argentina/Buenos_Aires", "AR", false),
    ("America/Argentina/Catamarca", "AR", false),
    ("America/Argentina/ComodRivadavia", "??", true),
    ("America/Argentina/Cordoba", "AR", false),
    ("America/Argentina/Jujuy", "AR", false),
    ("America/Argentina/La_Rioja", "AR", false),
    ("America/Argentina/Mendoza", "AR", false),
    ("America/Argentina/Rio_Gallegos", "AR", false),
    ("America/Argentina/Salta", "AR", false),
    ("America/Argentina/San_Juan", "AR", false),
    ("America/Argentina/San_Luis", "AR", false),
    ("America/Argentina/Tucuman", "AR", false),
    ("America/Argentina/Ushuaia", "AR", false),
    ("America/Aruba", "AW", false),
    ("America/Asuncion", "PY", false),
    ("America/Atikokan", "CA", false),
    ("America/Atka", "??", true),
    ("America/Bahia", "BR", false),
    ("America/Bahia_Banderas", "MX", false),
    ("America/Barbados", "BB", false),
    ("America/Belem", "BR", false),
    ("America/Belize", "BZ", false),
    ("America/Blanc-Sablon", "CA", false),
    ("America/Boa_Vista", "BR", false),
    ("America/Bogota", "CO", false),
    ("America/Boise", "US", false),
    ("America/Buenos_Aires", "??", true),
    ("America/Cambridge_Bay", "CA", false),
    ("America/Campo_Grande", "BR", false),
    ("America/Cancun", "MX", false),
    ("America/Caracas", "VE", false),
    ("America/Catamarca", "??", true),
    ("America/Cayenne", "GF", false),
    ("America/Cayman", "KY", false),
    ("America/Chicago", "US", false),
    ("America/Chihuahua", "MX", false),
    ("America/Ciudad_Juarez", "MX", false),
    ("America/Coral_Harbour", "??", true),
    ("America/Cordoba", "??", true),
    ("America/Costa_Rica", "CR", false),
    ("America/Coyhaique", "CL", false),
    ("America/Creston", "CA", false),
    ("America/Cuiaba", "BR", false),
    ("America/Curacao", "CW", false),
    ("America/Danmarkshavn", "GL", false),
    ("America/Dawson", "CA", false),
    ("America/Dawson_Creek", "CA", false),
    ("America/Denver", "US", false),
    ("America/Detroit", "US", false),
    ("America/Dominica", "DM", false),
    ("America/Edmonton", "CA", false),
    ("America/Eirunepe", "BR", false),
    ("America/El_Salvador", "SV", false),
    ("America/Ensenada", "??", true),
    ("America/Fort_Nelson", "CA", false),
    ("America/Fort_Wayne", "??", true),
    ("America/Fortaleza", "BR", false),
    ("America/Glace_Bay", "CA", false),
    ("America/Godthab", "??", true),
    ("America/Goose_Bay", "CA", false),
    ("America/Grand_Turk", "TC", false),
    ("America/Grenada", "GD", false),
    ("America/Guadeloupe", "GP", false),
    ("America/Guatemala", "GT", false),
    ("America/Guayaquil", "EC", false),
    ("America/Guyana", "GY", false),
    ("America/Halifax", "CA", false),
    ("America/Havana", "CU", false),
    ("America/Hermosillo", "MX", false),
    ("America/Indiana/Indianapolis", "US", false),
    ("America/Indiana/Knox", "US", false),
    ("America/Indiana/Marengo", "US", false),
    ("America/Indiana/Petersburg", "US", false),
    ("America/Indiana/Tell_City", "US", false),
    ("America/Indiana/Vevay", "US", false),
    ("America/Indiana/Vincennes", "US", false),
    ("America/Indiana/Winamac", "US", false),
    ("America/Indianapolis", "??", true),
    ("America/Inuvik", "CA", false),
    ("America/Iqaluit", "CA", false),
    ("America/Jamaica", "JM", false),
    ("America/Jujuy", "??", true),
    ("America/Juneau", "US", false),
    ("America/Kentucky/Louisville", "US", false),
    ("America/Kentucky/Monticello", "US", false),
    ("America/Knox_IN", "??", true),
    ("America/Kralendijk", "BQ", false),
    ("America/La_Paz", "BO", false),
    ("America/Lima", "PE", false),
    ("America/Los_Angeles", "US", false),
    ("America/Louisville", "??", true),
    ("America/Lower_Princes", "SX", false),
    ("America/Maceio", "BR", false),
    ("America/Managua", "NI", false),
    ("America/Manaus", "BR", false),
    ("America/Marigot", "MF", false),
    ("America/Martinique", "MQ", false),
    ("America/Matamoros", "MX", false),
    ("America/Mazatlan", "MX", false),
    ("America/Mendoza", "??", true),
    ("America/Menominee", "US", false),
    ("America/Merida", "MX", false),
    ("America/Metlakatla", "US", false),
    ("America/Mexico_City", "MX", false),
    ("America/Miquelon", "PM", false),
    ("America/Moncton", "CA", false),
    ("America/Monterrey", "MX", false),
    ("America/Montevideo", "UY", false),
    ("America/Montreal", "??", true),
    ("America/Montserrat", "MS", false),
    ("America/Nassau", "BS", false),
    ("America/New_York", "US", false),
    ("America/Nipigon", "??", true),
    ("America/Nome", "US", false),
    ("America/Noronha", "BR", false),
    ("America/North_Dakota/Beulah", "US", false),
    ("America/North_Dakota/Center", "US", false),
    ("America/North_Dakota/New_Salem", "US", false),
    ("America/Nuuk", "GL", false),
    ("America/Ojinaga", "MX", false),
    ("America/Panama", "PA", false),
    ("America/Pangnirtung", "??", true),
    ("America/Paramaribo", "SR", false),
    ("America/Phoenix", "US", false),
    ("America/Port-au-Prince", "HT", false),
    ("America/Port_of_Spain", "TT", false),
    ("America/Porto_Acre", "??", true),
    ("America/Porto_Velho", "BR", false),
    ("America/Puerto_Rico", "PR", false),
    ("America/Punta_Arenas", "CL", false),
    ("America/Rainy_River", "??", true),
    ("America/Rankin_Inlet", "CA", false),
    ("America/Recife", "BR", false),
    ("America/Regina", "CA", false),
    ("America/Resolute", "CA", false),
    ("America/Rio_Branco", "BR", false),
    ("America/Rosario", "??", true),
    ("America/Santa_Isabel", "??", true),
    ("America/Santarem", "BR", false),
    ("America/Santiago", "CL", false),
    ("America/Santo_Domingo", "DO", false),
    ("America/Sao_Paulo", "BR", false),
    ("America/Scoresbysund", "GL", false),
    ("America/Shiprock", "??", true),
    ("America/Sitka", "US", false),
    ("America/St_Barthelemy", "BL", false),
    ("America/St_Johns", "CA", false),
    ("America/St_Kitts", "KN", false),
    ("America/St_Lucia", "LC", false),
    ("America/St_Thomas", "VI", false),
    ("America/St_Vincent", "VC", false),
    ("America/Swift_Current", "CA", false),
    ("America/Tegucigalpa", "HN", false),
    ("America/Thule", "GL", false),
    ("America/Thunder_Bay", "??", true),
    ("America/Tijuana", "MX", false),
    ("America/Toronto", "CA", false),
    ("America/Tortola", "VG", false),
    ("America/Vancouver", "CA", false),
    ("America/Virgin", "??", true),
    ("America/Whitehorse", "CA", false),
    ("America/Winnipeg", "CA", false),
    ("America/Yakutat", "US", false),
    ("America/Yellowknife", "??", true),
    ("Antarctica/Casey", "AQ", false),
    ("Antarctica/Davis", "AQ", false),
    ("Antarctica/DumontDUrville", "AQ", false),
    ("Antarctica/Macquarie", "AU", false),
    ("Antarctica/Mawson", "AQ", false),
    ("Antarctica/McMurdo", "AQ", false),
    ("Antarctica/Palmer", "AQ", false),
    ("Antarctica/Rothera", "AQ", false),
    ("Antarctica/South_Pole", "??", true),
    ("Antarctica/Syowa", "AQ", false),
    ("Antarctica/Troll", "AQ", false),
    ("Antarctica/Vostok", "AQ", false),
    ("Arctic/Longyearbyen", "SJ", false),
    ("Asia/Aden", "YE", false),
    ("Asia/Almaty", "KZ", false),
    ("Asia/Amman", "JO", false),
    ("Asia/Anadyr", "RU", false),
    ("Asia/Aqtau", "KZ", false),
    ("Asia/Aqtobe", "KZ", false),
    ("Asia/Ashgabat", "TM", false),
    ("Asia/Ashkhabad", "??", true),
    ("Asia/Atyrau", "KZ", false),
    ("Asia/Baghdad", "IQ", false),
    ("Asia/Bahrain", "BH", false),
    ("Asia/Baku", "AZ", false),
    ("Asia/Bangkok", "TH", false),
    ("Asia/Barnaul", "RU", false),
    ("Asia/Beirut", "LB", false),
    ("Asia/Bishkek", "KG", false),
    ("Asia/Brunei", "BN", false),
    ("Asia/Calcutta", "??", true),
    ("Asia/Chita", "RU", false),
    ("Asia/Choibalsan", "??", true),
    ("Asia/Chongqing", "??", true),
    ("Asia/Chungking", "??", true),
    ("Asia/Colombo", "LK", false),
    ("Asia/Dacca", "??", true),
    ("Asia/Damascus", "SY", false),
    ("Asia/Dhaka", "BD", false),
    ("Asia/Dili", "TL", false),
    ("Asia/Dubai", "AE", false),
    ("Asia/Dushanbe", "TJ", false),
    ("Asia/Famagusta", "CY", false),
    ("Asia/Gaza", "PS", false),
    ("Asia/Harbin", "??", true),
    ("Asia/Hebron", "PS", false),
    ("Asia/Ho_Chi_Minh", "VN", false),
    ("Asia/Hong_Kong", "HK", false),
    ("Asia/Hovd", "MN", false),
    ("Asia/Irkutsk", "RU", false),
    ("Asia/Istanbul", "??", true),
    ("Asia/Jakarta", "ID", false),
    ("Asia/Jayapura", "ID", false),
    ("Asia/Jerusalem", "IL", false),
    ("Asia/Kabul", "AF", false),
    ("Asia/Kamchatka", "RU", false),
    ("Asia/Karachi", "PK", false),
    ("Asia/Kashgar", "??", true),
    ("Asia/Kathmandu", "NP", false),
    ("Asia/Katmandu", "??", true),
    ("Asia/Khandyga", "RU", false),
    ("Asia/Kolkata", "IN", false),
    ("Asia/Krasnoyarsk", "RU", false),
    ("Asia/Kuala_Lumpur", "MY", false),
    ("Asia/Kuching", "MY", false),
    ("Asia/Kuwait", "KW", false),
    ("Asia/Macao", "??", true),
    ("Asia/Macau", "MO", false),
    ("Asia/Magadan", "RU", false),
    ("Asia/Makassar", "ID", false),
    ("Asia/Manila", "PH", false),
    ("Asia/Muscat", "OM", false),
    ("Asia/Nicosia", "CY", false),
    ("Asia/Novokuznetsk", "RU", false),
    ("Asia/Novosibirsk", "RU", false),
    ("Asia/Omsk", "RU", false),
    ("Asia/Oral", "KZ", false),
    ("Asia/Phnom_Penh", "KH", false),
    ("Asia/Pontianak", "ID", false),
    ("Asia/Pyongyang", "KP", false),
    ("Asia/Qatar", "QA", false),
    ("Asia/Qostanay", "KZ", false),
    ("Asia/Qyzylorda", "KZ", false),
    ("Asia/Rangoon", "??", true),
    ("Asia/Riyadh", "SA", false),
    ("Asia/Saigon", "??", true),
    ("Asia/Sakhalin", "RU", false),
    ("Asia/Samarkand", "UZ", false),
    ("Asia/Seoul", "KR", false),
    ("Asia/Shanghai", "CN", false),
    ("Asia/Singapore", "SG", false),
    ("Asia/Srednekolymsk", "RU", false),
    ("Asia/Taipei", "TW", false),
    ("Asia/Tashkent", "UZ", false),
    ("Asia/Tbilisi", "GE", false),
    ("Asia/Tehran", "IR", false),
    ("Asia/Tel_Aviv", "??", true),
    ("Asia/Thimbu", "??", true),
    ("Asia/Thimphu", "BT", false),
    ("Asia/Tokyo", "JP", false),
    ("Asia/Tomsk", "RU", false),
    ("Asia/Ujung_Pandang", "??", true),
    ("Asia/Ulaanbaatar", "MN", false),
    ("Asia/Ulan_Bator", "??", true),
    ("Asia/Urumqi", "CN", false),
    ("Asia/Ust-Nera", "RU", false),
    ("Asia/Vientiane", "LA", false),
    ("Asia/Vladivostok", "RU", false),
    ("Asia/Yakutsk", "RU", false),
    ("Asia/Yangon", "MM", false),
    ("Asia/Yekaterinburg", "RU", false),
    ("Asia/Yerevan", "AM", false),
    ("Atlantic/Azores", "PT", false),
    ("Atlantic/Bermuda", "BM", false),
    ("Atlantic/Canary", "ES", false),
    ("Atlantic/Cape_Verde", "CV", false),
    ("Atlantic/Faeroe", "??", true),
    ("Atlantic/Faroe", "FO", false),
    ("Atlantic/Jan_Mayen", "??", true),
    ("Atlantic/Madeira", "PT", false),
    ("Atlantic/Reykjavik", "IS", false),
    ("Atlantic/South_Georgia", "GS", false),
    ("Atlantic/St_Helena", "SH", false),
    ("Atlantic/Stanley", "FK", false),
    ("Australia/ACT", "??", true),
    ("Australia/Adelaide", "AU", false),
    ("Australia/Brisbane", "AU", false),
    ("Australia/Broken_Hill", "AU", false),
    ("Australia/Canberra", "??", true),
    ("Australia/Currie", "??", true),
    ("Australia/Darwin", "AU", false),
    ("Australia/Eucla", "AU", false),
    ("Australia/Hobart", "AU", false),
    ("Australia/LHI", "??", true),
    ("Australia/Lindeman", "AU", false),
    ("Australia/Lord_Howe", "AU", false),
    ("Australia/Melbourne", "AU", false),
    ("Australia/North", "??", true),
    ("Australia/NSW", "??", true),
    ("Australia/Perth", "AU", false),
    ("Australia/Queensland", "??", true),
    ("Australia/South", "??", true),
    ("Australia/Sydney", "AU", false),
    ("Australia/Tasmania", "??", true),
    ("Australia/Victoria", "??", true),
    ("Australia/West", "??", true),
    ("Australia/Yancowinna", "??", true),
    ("Brazil/Acre", "??", true),
    ("Brazil/DeNoronha", "??", true),
    ("Brazil/East", "??", true),
    ("Brazil/West", "??", true),
    ("Canada/Atlantic", "??", true),
    ("Canada/Central", "??", true),
    ("Canada/Eastern", "??", true),
    ("Canada/Mountain", "??", true),
    ("Canada/Newfoundland", "??", true),
    ("Canada/Pacific", "??", true),
    ("Canada/Saskatchewan", "??", true),
    ("Canada/Yukon", "??", true),
    ("CET", "??", true),
    ("Chile/Continental", "??", true),
    ("Chile/EasterIsland", "??", true),
    ("CST6CDT", "??", true),
    ("Cuba", "??", true),
    ("EET", "??", true),
    ("Egypt", "??", true),
    ("Eire", "??", true),
    ("EST", "??", true),
    ("EST5EDT", "??", true),
    ("Etc/GMT", "??", true),
    ("Etc/GMT+0", "??", true),
    ("Etc/GMT+1", "??", true),
    ("Etc/GMT+10", "??", true),
    ("Etc/GMT+11", "??", true),
    ("Etc/GMT+12", "??", true),
    ("Etc/GMT+2", "??", true),
    ("Etc/GMT+3", "??", true),
    ("Etc/GMT+4", "??", true),
    ("Etc/GMT+5", "??", true),
    ("Etc/GMT+6", "??", true),
    ("Etc/GMT+7", "??", true),
    ("Etc/GMT+8", "??", true),
    ("Etc/GMT+9", "??", true),
    ("Etc/GMT-0", "??", true),
    ("Etc/GMT-1", "??", true),
    ("Etc/GMT-10", "??", true),
    ("Etc/GMT-11", "??", true),
    ("Etc/GMT-12", "??", true),
    ("Etc/GMT-13", "??", true),
    ("Etc/GMT-14", "??", true),
    ("Etc/GMT-2", "??", true),
    ("Etc/GMT-3", "??", true),
    ("Etc/GMT-4", "??", true),
    ("Etc/GMT-5", "??", true),
    ("Etc/GMT-6", "??", true),
    ("Etc/GMT-7", "??", true),
    ("Etc/GMT-8", "??", true),
    ("Etc/GMT-9", "??", true),
    ("Etc/GMT0", "??", true),
    ("Etc/Greenwich", "??", true),
    ("Etc/UCT", "??", true),
    ("Etc/Universal", "??", true),
    ("Etc/UTC", "??", true),
    ("Etc/Zulu", "??", true),
    ("Europe/Amsterdam", "NL", false),
    ("Europe/Andorra", "AD", false),
    ("Europe/Astrakhan", "RU", false),
    ("Europe/Athens", "GR", false),
    ("Europe/Belfast", "??", true),
    ("Europe/Belgrade", "RS", false),
    ("Europe/Berlin", "DE", false),
    ("Europe/Bratislava", "SK", false),
    ("Europe/Brussels", "BE", false),
    ("Europe/Bucharest", "RO", false),
    ("Europe/Budapest", "HU", false),
    ("Europe/Busingen", "DE", false),
    ("Europe/Chisinau", "MD", false),
    ("Europe/Copenhagen", "DK", false),
    ("Europe/Dublin", "IE", false),
    ("Europe/Gibraltar", "GI", false),
    ("Europe/Guernsey", "GG", false),
    ("Europe/Helsinki", "FI", false),
    ("Europe/Isle_of_Man", "IM", false),
    ("Europe/Istanbul", "TR", false),
    ("Europe/Jersey", "JE", false),
    ("Europe/Kaliningrad", "RU", false),
    ("Europe/Kiev", "??", true),
    ("Europe/Kirov", "RU", false),
    ("Europe/Kyiv", "UA", false),
    ("Europe/Lisbon", "PT", false),
    ("Europe/Ljubljana", "SI", false),
    ("Europe/London", "GB", false),
    ("Europe/Luxembourg", "LU", false),
    ("Europe/Madrid", "ES", false),
    ("Europe/Malta", "MT", false),
    ("Europe/Mariehamn", "AX", false),
    ("Europe/Minsk", "BY", false),
    ("Europe/Monaco", "MC", false),
    ("Europe/Moscow", "RU", false),
    ("Europe/Nicosia", "??", true),
    ("Europe/Oslo", "NO", false),
    ("Europe/Paris", "FR", false),
    ("Europe/Podgorica", "ME", false),
    ("Europe/Prague", "CZ", false),
    ("Europe/Riga", "LV", false),
    ("Europe/Rome", "IT", false),
    ("Europe/Samara", "RU", false),
    ("Europe/San_Marino", "SM", false),
    ("Europe/Sarajevo", "BA", false),
    ("Europe/Saratov", "RU", false),
    ("Europe/Simferopol", "UA", false),
    ("Europe/Skopje", "MK", false),
    ("Europe/Sofia", "BG", false),
    ("Europe/Stockholm", "SE", false),
    ("Europe/Tallinn", "EE", false),
    ("Europe/Tirane", "AL", false),
    ("Europe/Tiraspol", "??", true),
    ("Europe/Ulyanovsk", "RU", false),
    ("Europe/Uzhgorod", "??", true),
    ("Europe/Vaduz", "LI", false),
    ("Europe/Vatican", "VA", false),
    ("Europe/Vienna", "AT", false),
    ("Europe/Vilnius", "LT", false),
    ("Europe/Volgograd", "RU", false),
    ("Europe/Warsaw", "PL", false),
    ("Europe/Zagreb", "HR", false),
    ("Europe/Zaporozhye", "??", true),
    ("Europe/Zurich", "CH", false),
    ("Factory", "??", true),
    ("GB", "??", true),
    ("GB-Eire", "??", true),
    ("GMT", "??", true),
    ("GMT+0", "??", true),
    ("GMT-0", "??", true),
    ("GMT0", "??", true),
    ("Greenwich", "??", true),
    ("Hongkong", "??", true),
    ("HST", "??", true),
    ("Iceland", "??", true),
    ("Indian/Antananarivo", "MG", false),
    ("Indian/Chagos", "IO", false),
    ("Indian/Christmas", "CX", false),
    ("Indian/Cocos", "CC", false),
    ("Indian/Comoro", "KM", false),
    ("Indian/Kerguelen", "TF", false),
    ("Indian/Mahe", "SC", false),
    ("Indian/Maldives", "MV", false),
    ("Indian/Mauritius", "MU", false),
    ("Indian/Mayotte", "YT", false),
    ("Indian/Reunion", "RE", false),
    ("Iran", "??", true),
    ("Israel", "??", true),
    ("Jamaica", "??", true),
    ("Japan", "??", true),
    ("Kwajalein", "??", true),
    ("Libya", "??", true),
    ("MET", "??", true),
    ("Mexico/BajaNorte", "??", true),
    ("Mexico/BajaSur", "??", true),
    ("Mexico/General", "??", true),
    ("MST", "??", true),
    ("MST7MDT", "??", true),
    ("Navajo", "??", true),
    ("NZ", "??", true),
    ("NZ-CHAT", "??", true),
    ("Pacific/Apia", "WS", false),
    ("Pacific/Auckland", "NZ", false),
    ("Pacific/Bougainville", "PG", false),
    ("Pacific/Chatham", "NZ", false),
    ("Pacific/Chuuk", "FM", false),
    ("Pacific/Easter", "CL", false),
    ("Pacific/Efate", "VU", false),
    ("Pacific/Enderbury", "??", true),
    ("Pacific/Fakaofo", "TK", false),
    ("Pacific/Fiji", "FJ", false),
    ("Pacific/Funafuti", "TV", false),
    ("Pacific/Galapagos", "EC", false),
    ("Pacific/Gambier", "PF", false),
    ("Pacific/Guadalcanal", "SB", false),
    ("Pacific/Guam", "GU", false),
    ("Pacific/Honolulu", "US", false),
    ("Pacific/Johnston", "??", true),
    ("Pacific/Kanton", "KI", false),
    ("Pacific/Kiritimati", "KI", false),
    ("Pacific/Kosrae", "FM", false),
    ("Pacific/Kwajalein", "MH", false),
    ("Pacific/Majuro", "MH", false),
    ("Pacific/Marquesas", "PF", false),
    ("Pacific/Midway", "UM", false),
    ("Pacific/Nauru", "NR", false),
    ("Pacific/Niue", "NU", false),
    ("Pacific/Norfolk", "NF", false),
    ("Pacific/Noumea", "NC", false),
    ("Pacific/Pago_Pago", "AS", false),
    ("Pacific/Palau", "PW", false),
    ("Pacific/Pitcairn", "PN", false),
    ("Pacific/Pohnpei", "FM", false),
    ("Pacific/Ponape", "??", true),
    ("Pacific/Port_Moresby", "PG", false),
    ("Pacific/Rarotonga", "CK", false),
    ("Pacific/Saipan", "MP", false),
    ("Pacific/Samoa", "??", true),
    ("Pacific/Tahiti", "PF", false),
    ("Pacific/Tarawa", "KI", false),
    ("Pacific/Tongatapu", "TO", false),
    ("Pacific/Truk", "??", true),
    ("Pacific/Wake", "UM", false),
    ("Pacific/Wallis", "WF", false),
    ("Pacific/Yap", "??", true),
    ("Poland", "??", true),
    ("Portugal", "??", true),
    ("PRC", "??", true),
    ("PST8PDT", "??", true),
    ("ROC", "??", true),
    ("ROK", "??", true),
    ("Singapore", "??", true),
    ("Turkey", "??", true),
    ("UCT", "??", true),
    ("Universal", "??", true),
    ("US/Alaska", "??", true),
    ("US/Aleutian", "??", true),
    ("US/Arizona", "??", true),
    ("US/Central", "??", true),
    ("US/East-Indiana", "??", true),
    ("US/Eastern", "??", true),
    ("US/Hawaii", "??", true),
    ("US/Indiana-Starke", "??", true),
    ("US/Michigan", "??", true),
    ("US/Mountain", "??", true),
    ("US/Pacific", "??", true),
    ("US/Samoa", "??", true),
    ("UTC", "??", false),
    ("W-SU", "??", true),
    ("WET", "??", true),
    ("Zulu", "??", true),
];

/// `timezone_abbreviations_list()`: every abbreviation php knows, with the
/// DST flag, the offset and the identifier of each zone that uses it, in the
/// order php returns them. An empty identifier is php's `null` — the military
/// zones have no zone of their own.
#[rustfmt::skip]
pub(crate) static ABBREVIATION_ROWS: &[(&str, bool, i32, &str)] = &[
    ("acdt", true, 37800, "Australia/Adelaide"),
    ("acdt", true, 37800, "Australia/Broken_Hill"),
    ("acdt", true, 37800, "Australia/Darwin"),
    ("acdt", true, 37800, "Australia/North"),
    ("acdt", true, 37800, "Australia/South"),
    ("acdt", true, 37800, "Australia/Yancowinna"),
    ("acst", false, 34200, "Australia/Adelaide"),
    ("acst", false, 34200, "Australia/Broken_Hill"),
    ("acst", false, 34200, "Australia/Darwin"),
    ("acst", false, 34200, "Australia/North"),
    ("acst", false, 34200, "Australia/South"),
    ("acst", false, 34200, "Australia/Yancowinna"),
    ("addt", true, -7200, "America/Goose_Bay"),
    ("addt", true, -7200, "America/Pangnirtung"),
    ("adt", true, -10800, "America/Halifax"),
    ("adt", true, -10800, "America/Barbados"),
    ("adt", true, -10800, "America/Blanc-Sablon"),
    ("adt", true, -10800, "America/Glace_Bay"),
    ("adt", true, -10800, "America/Goose_Bay"),
    ("adt", true, -10800, "America/Martinique"),
    ("adt", true, -10800, "America/Moncton"),
    ("adt", true, -10800, "America/Pangnirtung"),
    ("adt", true, -10800, "America/Thule"),
    ("adt", true, -10800, "Atlantic/Bermuda"),
    ("adt", true, -10800, "Canada/Atlantic"),
    ("aedt", true, 39600, "Australia/Melbourne"),
    ("aedt", true, 39600, "Antarctica/Macquarie"),
    ("aedt", true, 39600, "Australia/ACT"),
    ("aedt", true, 39600, "Australia/Brisbane"),
    ("aedt", true, 39600, "Australia/Canberra"),
    ("aedt", true, 39600, "Australia/Currie"),
    ("aedt", true, 39600, "Australia/Hobart"),
    ("aedt", true, 39600, "Australia/Lindeman"),
    ("aedt", true, 39600, "Australia/NSW"),
    ("aedt", true, 39600, "Australia/Queensland"),
    ("aedt", true, 39600, "Australia/Sydney"),
    ("aedt", true, 39600, "Australia/Tasmania"),
    ("aedt", true, 39600, "Australia/Victoria"),
    ("aest", false, 36000, "Australia/Melbourne"),
    ("aest", false, 36000, "Antarctica/Macquarie"),
    ("aest", false, 36000, "Australia/ACT"),
    ("aest", false, 36000, "Australia/Brisbane"),
    ("aest", false, 36000, "Australia/Canberra"),
    ("aest", false, 36000, "Australia/Currie"),
    ("aest", false, 36000, "Australia/Hobart"),
    ("aest", false, 36000, "Australia/LHI"),
    ("aest", false, 36000, "Australia/Lindeman"),
    ("aest", false, 36000, "Australia/Lord_Howe"),
    ("aest", false, 36000, "Australia/NSW"),
    ("aest", false, 36000, "Australia/Queensland"),
    ("aest", false, 36000, "Australia/Sydney"),
    ("aest", false, 36000, "Australia/Tasmania"),
    ("aest", false, 36000, "Australia/Victoria"),
    ("ahdt", true, -32400, "America/Anchorage"),
    ("ahst", false, -36000, "America/Anchorage"),
    ("ahst", false, -36000, "America/Adak"),
    ("ahst", false, -36000, "America/Atka"),
    ("akdt", true, -28800, "America/Anchorage"),
    ("akdt", true, -28800, "America/Juneau"),
    ("akdt", true, -28800, "America/Metlakatla"),
    ("akdt", true, -28800, "America/Nome"),
    ("akdt", true, -28800, "America/Sitka"),
    ("akdt", true, -28800, "America/Yakutat"),
    ("akst", false, -32400, "America/Anchorage"),
    ("akst", false, -32400, "America/Juneau"),
    ("akst", false, -32400, "America/Metlakatla"),
    ("akst", false, -32400, "America/Nome"),
    ("akst", false, -32400, "America/Sitka"),
    ("akst", false, -32400, "America/Yakutat"),
    ("amt", false, -13840, "America/Asuncion"),
    ("amt", false, 1172, "Europe/Amsterdam"),
    ("amt", false, 5692, "Europe/Athens"),
    ("apt", true, -10800, "America/Halifax"),
    ("apt", true, -10800, "America/Blanc-Sablon"),
    ("apt", true, -10800, "America/Glace_Bay"),
    ("apt", true, -10800, "America/Moncton"),
    ("apt", true, -10800, "America/Pangnirtung"),
    ("apt", true, -10800, "America/Puerto_Rico"),
    ("apt", true, -10800, "Canada/Atlantic"),
    ("apt", true, -32400, "America/Anchorage"),
    ("ast", false, -14400, "America/Anguilla"),
    ("ast", false, -14400, "America/Antigua"),
    ("ast", false, -14400, "America/Aruba"),
    ("ast", false, -14400, "America/Barbados"),
    ("ast", false, -14400, "America/Blanc-Sablon"),
    ("ast", false, -14400, "America/Curacao"),
    ("ast", false, -14400, "America/Dominica"),
    ("ast", false, -14400, "America/Glace_Bay"),
    ("ast", false, -14400, "America/Goose_Bay"),
    ("ast", false, -14400, "America/Grand_Turk"),
    ("ast", false, -14400, "America/Grenada"),
    ("ast", false, -14400, "America/Guadeloupe"),
    ("ast", false, -14400, "America/Halifax"),
    ("ast", false, -14400, "America/Kralendijk"),
    ("ast", false, -14400, "America/Lower_Princes"),
    ("ast", false, -14400, "America/Marigot"),
    ("ast", false, -14400, "America/Martinique"),
    ("ast", false, -14400, "America/Miquelon"),
    ("ast", false, -14400, "America/Moncton"),
    ("ast", false, -14400, "America/Montserrat"),
    ("ast", false, -14400, "America/Pangnirtung"),
    ("ast", false, -14400, "America/Port_of_Spain"),
    ("ast", false, -14400, "America/Puerto_Rico"),
    ("ast", false, -14400, "America/Santo_Domingo"),
    ("ast", false, -14400, "America/St_Barthelemy"),
    ("ast", false, -14400, "America/St_Kitts"),
    ("ast", false, -14400, "America/St_Lucia"),
    ("ast", false, -14400, "America/St_Thomas"),
    ("ast", false, -14400, "America/St_Vincent"),
    ("ast", false, -14400, "America/Thule"),
    ("ast", false, -14400, "America/Tortola"),
    ("ast", false, -14400, "America/Virgin"),
    ("ast", false, -14400, "Atlantic/Bermuda"),
    ("ast", false, -14400, "Canada/Atlantic"),
    ("ast", false, -36000, "America/Anchorage"),
    ("awdt", true, 32400, "Australia/Perth"),
    ("awdt", true, 32400, "Australia/West"),
    ("awst", false, 28800, "Australia/Perth"),
    ("awst", false, 28800, "Australia/West"),
    ("awt", true, -10800, "America/Halifax"),
    ("awt", true, -10800, "America/Blanc-Sablon"),
    ("awt", true, -10800, "America/Glace_Bay"),
    ("awt", true, -10800, "America/Moncton"),
    ("awt", true, -10800, "America/Pangnirtung"),
    ("awt", true, -10800, "America/Puerto_Rico"),
    ("awt", true, -10800, "Canada/Atlantic"),
    ("awt", true, -32400, "America/Anchorage"),
    ("bdst", true, 7200, "Europe/London"),
    ("bdst", true, 7200, "Europe/Belfast"),
    ("bdst", true, 7200, "Europe/Gibraltar"),
    ("bdst", true, 7200, "Europe/Guernsey"),
    ("bdst", true, 7200, "Europe/Isle_of_Man"),
    ("bdst", true, 7200, "Europe/Jersey"),
    ("bdst", true, 7200, "GB"),
    ("bdt", true, -36000, "America/Adak"),
    ("bdt", true, -36000, "America/Atka"),
    ("bdt", true, -36000, "America/Nome"),
    ("bmt", false, -14309, "America/Barbados"),
    ("bmt", false, 6264, "Europe/Tiraspol"),
    ("bmt", false, -17776, "America/Bogota"),
    ("bmt", false, 10656, "Asia/Baghdad"),
    ("bmt", false, 24124, "Asia/Bangkok"),
    ("bmt", false, 24124, "Asia/Phnom_Penh"),
    ("bmt", false, 24124, "Asia/Vientiane"),
    ("bmt", false, 25632, "Asia/Jakarta"),
    ("bmt", false, 6264, "Europe/Bucharest"),
    ("bmt", false, 6264, "Europe/Chisinau"),
    ("bst", true, 3600, "Europe/London"),
    ("bst", false, 3600, "Europe/London"),
    ("bst", true, -12756, "America/La_Paz"),
    ("bst", false, -39600, "America/Adak"),
    ("bst", false, -39600, "America/Atka"),
    ("bst", false, -39600, "America/Nome"),
    ("bst", false, 3600, "Europe/Belfast"),
    ("bst", false, 3600, "Europe/Guernsey"),
    ("bst", false, 3600, "Europe/Isle_of_Man"),
    ("bst", false, 3600, "Europe/Jersey"),
    ("bst", false, 3600, "GB"),
    ("bst", true, 3600, "Europe/Belfast"),
    ("bst", true, 3600, "Europe/Dublin"),
    ("bst", true, 3600, "Europe/Gibraltar"),
    ("bst", true, 3600, "Europe/Guernsey"),
    ("bst", true, 3600, "Europe/Isle_of_Man"),
    ("bst", true, 3600, "Europe/Jersey"),
    ("bst", true, 3600, "GB"),
    ("cast", false, 34200, "Australia/Adelaide"),
    ("cast", true, 10800, "Africa/Juba"),
    ("cast", true, 10800, "Africa/Khartoum"),
    ("cat", false, 7200, "Africa/Khartoum"),
    ("cat", false, 7200, "Africa/Blantyre"),
    ("cat", false, 7200, "Africa/Bujumbura"),
    ("cat", false, 7200, "Africa/Gaborone"),
    ("cat", false, 7200, "Africa/Harare"),
    ("cat", false, 7200, "Africa/Juba"),
    ("cat", false, 7200, "Africa/Kigali"),
    ("cat", false, 7200, "Africa/Lubumbashi"),
    ("cat", false, 7200, "Africa/Lusaka"),
    ("cat", false, 7200, "Africa/Maputo"),
    ("cat", false, 7200, "Africa/Windhoek"),
    ("cddt", true, -14400, "America/Rankin_Inlet"),
    ("cddt", true, -14400, "America/Resolute"),
    ("cdt", true, -18000, "America/Chicago"),
    ("cdt", true, 32400, "Asia/Shanghai"),
    ("cdt", true, -14400, "America/Havana"),
    ("cdt", true, -18000, "America/Atikokan"),
    ("cdt", true, -18000, "America/Bahia_Banderas"),
    ("cdt", true, -18000, "America/Belize"),
    ("cdt", true, -18000, "America/Cambridge_Bay"),
    ("cdt", true, -18000, "America/Cancun"),
    ("cdt", true, -18000, "America/Chihuahua"),
    ("cdt", true, -18000, "America/Coral_Harbour"),
    ("cdt", true, -18000, "America/Costa_Rica"),
    ("cdt", true, -18000, "America/El_Salvador"),
    ("cdt", true, -18000, "America/Fort_Wayne"),
    ("cdt", true, -18000, "America/Guatemala"),
    ("cdt", true, -18000, "America/Indiana/Indianapolis"),
    ("cdt", true, -18000, "America/Indiana/Knox"),
    ("cdt", true, -18000, "America/Indiana/Marengo"),
    ("cdt", true, -18000, "America/Indiana/Petersburg"),
    ("cdt", true, -18000, "America/Indiana/Tell_City"),
    ("cdt", true, -18000, "America/Indiana/Vevay"),
    ("cdt", true, -18000, "America/Indiana/Vincennes"),
    ("cdt", true, -18000, "America/Indiana/Winamac"),
    ("cdt", true, -18000, "America/Indianapolis"),
    ("cdt", true, -18000, "America/Iqaluit"),
    ("cdt", true, -18000, "America/Kentucky/Louisville"),
    ("cdt", true, -18000, "America/Kentucky/Monticello"),
    ("cdt", true, -18000, "America/Knox_IN"),
    ("cdt", true, -18000, "America/Louisville"),
    ("cdt", true, -18000, "America/Managua"),
    ("cdt", true, -18000, "America/Matamoros"),
    ("cdt", true, -18000, "America/Menominee"),
    ("cdt", true, -18000, "America/Merida"),
    ("cdt", true, -18000, "America/Mexico_City"),
    ("cdt", true, -18000, "America/Monterrey"),
    ("cdt", true, -18000, "America/North_Dakota/Beulah"),
    ("cdt", true, -18000, "America/North_Dakota/Center"),
    ("cdt", true, -18000, "America/North_Dakota/New_Salem"),
    ("cdt", true, -18000, "America/Ojinaga"),
    ("cdt", true, -18000, "America/Pangnirtung"),
    ("cdt", true, -18000, "America/Rainy_River"),
    ("cdt", true, -18000, "America/Rankin_Inlet"),
    ("cdt", true, -18000, "America/Resolute"),
    ("cdt", true, -18000, "America/Tegucigalpa"),
    ("cdt", true, -18000, "America/Winnipeg"),
    ("cdt", true, -18000, "Canada/Central"),
    ("cdt", true, -18000, "Mexico/General"),
    ("cdt", true, 32400, "Asia/Chongqing"),
    ("cdt", true, 32400, "Asia/Chungking"),
    ("cdt", true, 32400, "Asia/Harbin"),
    ("cdt", true, 32400, "Asia/Macao"),
    ("cdt", true, 32400, "Asia/Macau"),
    ("cdt", true, 32400, "Asia/Taipei"),
    ("cdt", true, 32400, "PRC"),
    ("cdt", true, 32400, "ROC"),
    ("cemt", true, 10800, "Europe/Berlin"),
    ("cest", true, 7200, "Europe/Berlin"),
    ("cest", true, 10800, "Europe/Kaliningrad"),
    ("cest", true, 7200, "Africa/Algiers"),
    ("cest", true, 7200, "Africa/Ceuta"),
    ("cest", true, 7200, "Africa/Tripoli"),
    ("cest", true, 7200, "Africa/Tunis"),
    ("cest", true, 7200, "Arctic/Longyearbyen"),
    ("cest", true, 7200, "Atlantic/Jan_Mayen"),
    ("cest", true, 7200, "Europe/Amsterdam"),
    ("cest", true, 7200, "Europe/Andorra"),
    ("cest", true, 7200, "Europe/Athens"),
    ("cest", true, 7200, "Europe/Belgrade"),
    ("cest", true, 7200, "Europe/Bratislava"),
    ("cest", true, 7200, "Europe/Brussels"),
    ("cest", true, 7200, "Europe/Budapest"),
    ("cest", true, 7200, "Europe/Busingen"),
    ("cest", true, 7200, "Europe/Chisinau"),
    ("cest", true, 7200, "Europe/Copenhagen"),
    ("cest", true, 7200, "Europe/Gibraltar"),
    ("cest", true, 7200, "Europe/Kaliningrad"),
    ("cest", true, 7200, "Europe/Kiev"),
    ("cest", true, 7200, "Europe/Lisbon"),
    ("cest", true, 7200, "Europe/Ljubljana"),
    ("cest", true, 7200, "Europe/Luxembourg"),
    ("cest", true, 7200, "Europe/Madrid"),
    ("cest", true, 7200, "Europe/Malta"),
    ("cest", true, 7200, "Europe/Minsk"),
    ("cest", true, 7200, "Europe/Monaco"),
    ("cest", true, 7200, "Europe/Oslo"),
    ("cest", true, 7200, "Europe/Paris"),
    ("cest", true, 7200, "Europe/Podgorica"),
    ("cest", true, 7200, "Europe/Prague"),
    ("cest", true, 7200, "Europe/Riga"),
    ("cest", true, 7200, "Europe/Rome"),
    ("cest", true, 7200, "Europe/San_Marino"),
    ("cest", true, 7200, "Europe/Sarajevo"),
    ("cest", true, 7200, "Europe/Simferopol"),
    ("cest", true, 7200, "Europe/Skopje"),
    ("cest", true, 7200, "Europe/Sofia"),
    ("cest", true, 7200, "Europe/Stockholm"),
    ("cest", true, 7200, "Europe/Tallinn"),
    ("cest", true, 7200, "Europe/Tirane"),
    ("cest", true, 7200, "Europe/Tiraspol"),
    ("cest", true, 7200, "Europe/Uzhgorod"),
    ("cest", true, 7200, "Europe/Vaduz"),
    ("cest", true, 7200, "Europe/Vatican"),
    ("cest", true, 7200, "Europe/Vienna"),
    ("cest", true, 7200, "Europe/Vilnius"),
    ("cest", true, 7200, "Europe/Warsaw"),
    ("cest", true, 7200, "Europe/Zagreb"),
    ("cest", true, 7200, "Europe/Zaporozhye"),
    ("cest", true, 7200, "Europe/Zurich"),
    ("cet", false, 3600, "Europe/Berlin"),
    ("cet", false, 7200, "Europe/Kaliningrad"),
    ("cet", false, 3600, "Africa/Algiers"),
    ("cet", false, 3600, "Africa/Ceuta"),
    ("cet", false, 3600, "Africa/Tripoli"),
    ("cet", false, 3600, "Africa/Tunis"),
    ("cet", false, 3600, "Arctic/Longyearbyen"),
    ("cet", false, 3600, "Atlantic/Jan_Mayen"),
    ("cet", false, 3600, "Europe/Amsterdam"),
    ("cet", false, 3600, "Europe/Andorra"),
    ("cet", false, 3600, "Europe/Athens"),
    ("cet", false, 3600, "Europe/Belgrade"),
    ("cet", false, 3600, "Europe/Bratislava"),
    ("cet", false, 3600, "Europe/Brussels"),
    ("cet", false, 3600, "Europe/Budapest"),
    ("cet", false, 3600, "Europe/Busingen"),
    ("cet", false, 3600, "Europe/Chisinau"),
    ("cet", false, 3600, "Europe/Copenhagen"),
    ("cet", false, 3600, "Europe/Gibraltar"),
    ("cet", false, 3600, "Europe/Kaliningrad"),
    ("cet", false, 3600, "Europe/Kiev"),
    ("cet", false, 3600, "Europe/Lisbon"),
    ("cet", false, 3600, "Europe/Ljubljana"),
    ("cet", false, 3600, "Europe/Luxembourg"),
    ("cet", false, 3600, "Europe/Madrid"),
    ("cet", false, 3600, "Europe/Malta"),
    ("cet", false, 3600, "Europe/Minsk"),
    ("cet", false, 3600, "Europe/Monaco"),
    ("cet", false, 3600, "Europe/Oslo"),
    ("cet", false, 3600, "Europe/Paris"),
    ("cet", false, 3600, "Europe/Podgorica"),
    ("cet", false, 3600, "Europe/Prague"),
    ("cet", false, 3600, "Europe/Riga"),
    ("cet", false, 3600, "Europe/Rome"),
    ("cet", false, 3600, "Europe/San_Marino"),
    ("cet", false, 3600, "Europe/Sarajevo"),
    ("cet", false, 3600, "Europe/Simferopol"),
    ("cet", false, 3600, "Europe/Skopje"),
    ("cet", false, 3600, "Europe/Sofia"),
    ("cet", false, 3600, "Europe/Stockholm"),
    ("cet", false, 3600, "Europe/Tallinn"),
    ("cet", false, 3600, "Europe/Tirane"),
    ("cet", false, 3600, "Europe/Tiraspol"),
    ("cet", false, 3600, "Europe/Uzhgorod"),
    ("cet", false, 3600, "Europe/Vaduz"),
    ("cet", false, 3600, "Europe/Vatican"),
    ("cet", false, 3600, "Europe/Vienna"),
    ("cet", false, 3600, "Europe/Vilnius"),
    ("cet", false, 3600, "Europe/Warsaw"),
    ("cet", false, 3600, "Europe/Zagreb"),
    ("cet", false, 3600, "Europe/Zaporozhye"),
    ("cet", false, 3600, "Europe/Zurich"),
    ("cmt", false, -15408, "America/Argentina/Buenos_Aires"),
    ("cmt", false, -15408, "America/Argentina/Catamarca"),
    ("cmt", false, -15408, "America/Argentina/ComodRivadavia"),
    ("cmt", false, -15408, "America/Argentina/Cordoba"),
    ("cmt", false, -15408, "America/Argentina/Jujuy"),
    ("cmt", false, -15408, "America/Argentina/La_Rioja"),
    ("cmt", false, -15408, "America/Argentina/Mendoza"),
    ("cmt", false, -15408, "America/Argentina/Rio_Gallegos"),
    ("cmt", false, -15408, "America/Argentina/Salta"),
    ("cmt", false, -15408, "America/Argentina/San_Juan"),
    ("cmt", false, -15408, "America/Argentina/San_Luis"),
    ("cmt", false, -15408, "America/Argentina/Tucuman"),
    ("cmt", false, -15408, "America/Argentina/Ushuaia"),
    ("cmt", false, -15408, "America/Buenos_Aires"),
    ("cmt", false, -15408, "America/Catamarca"),
    ("cmt", false, -15408, "America/Cordoba"),
    ("cmt", false, -15408, "America/Jujuy"),
    ("cmt", false, -15408, "America/Mendoza"),
    ("cmt", false, -15408, "America/Rosario"),
    ("cmt", false, -16060, "America/Caracas"),
    ("cmt", false, -16356, "America/La_Paz"),
    ("cmt", false, -19176, "America/Cayman"),
    ("cmt", false, -19176, "America/Panama"),
    ("cmt", false, 6900, "Europe/Chisinau"),
    ("cmt", false, 6900, "Europe/Tiraspol"),
    ("cpt", true, -18000, "America/Chicago"),
    ("cpt", true, -18000, "America/Atikokan"),
    ("cpt", true, -18000, "America/Coral_Harbour"),
    ("cpt", true, -18000, "America/Fort_Wayne"),
    ("cpt", true, -18000, "America/Indiana/Indianapolis"),
    ("cpt", true, -18000, "America/Indiana/Knox"),
    ("cpt", true, -18000, "America/Indiana/Marengo"),
    ("cpt", true, -18000, "America/Indiana/Petersburg"),
    ("cpt", true, -18000, "America/Indiana/Tell_City"),
    ("cpt", true, -18000, "America/Indiana/Vevay"),
    ("cpt", true, -18000, "America/Indiana/Vincennes"),
    ("cpt", true, -18000, "America/Indiana/Winamac"),
    ("cpt", true, -18000, "America/Indianapolis"),
    ("cpt", true, -18000, "America/Kentucky/Louisville"),
    ("cpt", true, -18000, "America/Kentucky/Monticello"),
    ("cpt", true, -18000, "America/Knox_IN"),
    ("cpt", true, -18000, "America/Louisville"),
    ("cpt", true, -18000, "America/Menominee"),
    ("cpt", true, -18000, "America/Rainy_River"),
    ("cpt", true, -18000, "America/Winnipeg"),
    ("cpt", true, -18000, "Canada/Central"),
    ("cst", false, -21600, "America/Chicago"),
    ("cst", false, -18000, "America/Havana"),
    ("cst", false, -21600, "America/Atikokan"),
    ("cst", false, -21600, "America/Bahia_Banderas"),
    ("cst", false, -21600, "America/Belize"),
    ("cst", false, -21600, "America/Cambridge_Bay"),
    ("cst", false, -21600, "America/Cancun"),
    ("cst", false, -21600, "America/Chihuahua"),
    ("cst", false, -21600, "America/Coral_Harbour"),
    ("cst", false, -21600, "America/Costa_Rica"),
    ("cst", false, -21600, "America/Detroit"),
    ("cst", false, -21600, "America/El_Salvador"),
    ("cst", false, -21600, "America/Fort_Wayne"),
    ("cst", false, -21600, "America/Guatemala"),
    ("cst", false, -21600, "America/Hermosillo"),
    ("cst", false, -21600, "America/Indiana/Indianapolis"),
    ("cst", false, -21600, "America/Indiana/Knox"),
    ("cst", false, -21600, "America/Indiana/Marengo"),
    ("cst", false, -21600, "America/Indiana/Petersburg"),
    ("cst", false, -21600, "America/Indiana/Tell_City"),
    ("cst", false, -21600, "America/Indiana/Vevay"),
    ("cst", false, -21600, "America/Indiana/Vincennes"),
    ("cst", false, -21600, "America/Indiana/Winamac"),
    ("cst", false, -21600, "America/Indianapolis"),
    ("cst", false, -21600, "America/Iqaluit"),
    ("cst", false, -21600, "America/Kentucky/Louisville"),
    ("cst", false, -21600, "America/Kentucky/Monticello"),
    ("cst", false, -21600, "America/Knox_IN"),
    ("cst", false, -21600, "America/Louisville"),
    ("cst", false, -21600, "America/Managua"),
    ("cst", false, -21600, "America/Matamoros"),
    ("cst", false, -21600, "America/Mazatlan"),
    ("cst", false, -21600, "America/Menominee"),
    ("cst", false, -21600, "America/Merida"),
    ("cst", false, -21600, "America/Mexico_City"),
    ("cst", false, -21600, "America/Monterrey"),
    ("cst", false, -21600, "America/North_Dakota/Beulah"),
    ("cst", false, -21600, "America/North_Dakota/Center"),
    ("cst", false, -21600, "America/North_Dakota/New_Salem"),
    ("cst", false, -21600, "America/Ojinaga"),
    ("cst", false, -21600, "America/Pangnirtung"),
    ("cst", false, -21600, "America/Rainy_River"),
    ("cst", false, -21600, "America/Rankin_Inlet"),
    ("cst", false, -21600, "America/Regina"),
    ("cst", false, -21600, "America/Resolute"),
    ("cst", false, -21600, "America/Swift_Current"),
    ("cst", false, -21600, "America/Tegucigalpa"),
    ("cst", false, -21600, "America/Thunder_Bay"),
    ("cst", false, -21600, "America/Winnipeg"),
    ("cst", false, -21600, "Canada/Central"),
    ("cst", false, -21600, "Canada/Saskatchewan"),
    ("cst", false, -21600, "Mexico/BajaSur"),
    ("cst", false, -21600, "Mexico/General"),
    ("cst", false, 28800, "Asia/Chongqing"),
    ("cst", false, 28800, "Asia/Chungking"),
    ("cst", false, 28800, "Asia/Harbin"),
    ("cst", false, 28800, "Asia/Macao"),
    ("cst", false, 28800, "Asia/Macau"),
    ("cst", false, 28800, "Asia/Shanghai"),
    ("cst", false, 28800, "Asia/Taipei"),
    ("cst", false, 28800, "PRC"),
    ("cst", false, 28800, "ROC"),
    ("cwt", true, -18000, "America/Chicago"),
    ("cwt", true, -18000, "America/Atikokan"),
    ("cwt", true, -18000, "America/Coral_Harbour"),
    ("cwt", true, -18000, "America/Fort_Wayne"),
    ("cwt", true, -18000, "America/Indiana/Indianapolis"),
    ("cwt", true, -18000, "America/Indiana/Knox"),
    ("cwt", true, -18000, "America/Indiana/Marengo"),
    ("cwt", true, -18000, "America/Indiana/Petersburg"),
    ("cwt", true, -18000, "America/Indiana/Tell_City"),
    ("cwt", true, -18000, "America/Indiana/Vevay"),
    ("cwt", true, -18000, "America/Indiana/Vincennes"),
    ("cwt", true, -18000, "America/Indiana/Winamac"),
    ("cwt", true, -18000, "America/Indianapolis"),
    ("cwt", true, -18000, "America/Kentucky/Louisville"),
    ("cwt", true, -18000, "America/Kentucky/Monticello"),
    ("cwt", true, -18000, "America/Knox_IN"),
    ("cwt", true, -18000, "America/Louisville"),
    ("cwt", true, -18000, "America/Menominee"),
    ("cwt", true, -18000, "America/Mexico_City"),
    ("cwt", true, -18000, "America/Rainy_River"),
    ("cwt", true, -18000, "America/Winnipeg"),
    ("cwt", true, -18000, "Canada/Central"),
    ("cwt", true, -18000, "Mexico/General"),
    ("chst", false, 36000, "Pacific/Guam"),
    ("chst", false, 36000, "Pacific/Saipan"),
    ("dmt", false, -1521, "Europe/Dublin"),
    ("eat", false, 10800, "Africa/Addis_Ababa"),
    ("eat", false, 10800, "Africa/Khartoum"),
    ("eat", false, 10800, "Africa/Asmara"),
    ("eat", false, 10800, "Africa/Asmera"),
    ("eat", false, 10800, "Africa/Dar_es_Salaam"),
    ("eat", false, 10800, "Africa/Djibouti"),
    ("eat", false, 10800, "Africa/Juba"),
    ("eat", false, 10800, "Africa/Kampala"),
    ("eat", false, 10800, "Africa/Mogadishu"),
    ("eat", false, 10800, "Africa/Nairobi"),
    ("eat", false, 10800, "Indian/Antananarivo"),
    ("eat", false, 10800, "Indian/Comoro"),
    ("eat", false, 10800, "Indian/Mayotte"),
    ("eddt", true, -10800, "America/Iqaluit"),
    ("edt", true, -14400, "America/New_York"),
    ("edt", true, -14400, "America/Cancun"),
    ("edt", true, -14400, "America/Detroit"),
    ("edt", true, -14400, "America/Fort_Wayne"),
    ("edt", true, -14400, "America/Grand_Turk"),
    ("edt", true, -14400, "America/Indiana/Indianapolis"),
    ("edt", true, -14400, "America/Indiana/Marengo"),
    ("edt", true, -14400, "America/Indiana/Petersburg"),
    ("edt", true, -14400, "America/Indiana/Tell_City"),
    ("edt", true, -14400, "America/Indiana/Vevay"),
    ("edt", true, -14400, "America/Indiana/Vincennes"),
    ("edt", true, -14400, "America/Indiana/Winamac"),
    ("edt", true, -14400, "America/Indianapolis"),
    ("edt", true, -14400, "America/Iqaluit"),
    ("edt", true, -14400, "America/Jamaica"),
    ("edt", true, -14400, "America/Kentucky/Louisville"),
    ("edt", true, -14400, "America/Kentucky/Monticello"),
    ("edt", true, -14400, "America/Louisville"),
    ("edt", true, -14400, "America/Montreal"),
    ("edt", true, -14400, "America/Nassau"),
    ("edt", true, -14400, "America/Nipigon"),
    ("edt", true, -14400, "America/Pangnirtung"),
    ("edt", true, -14400, "America/Port-au-Prince"),
    ("edt", true, -14400, "America/Santo_Domingo"),
    ("edt", true, -14400, "America/Thunder_Bay"),
    ("edt", true, -14400, "America/Toronto"),
    ("edt", true, -14400, "Canada/Eastern"),
    ("eest", true, 10800, "Europe/Helsinki"),
    ("eest", true, 10800, "Africa/Cairo"),
    ("eest", true, 10800, "Asia/Amman"),
    ("eest", true, 10800, "Asia/Beirut"),
    ("eest", true, 10800, "Asia/Damascus"),
    ("eest", true, 10800, "Asia/Famagusta"),
    ("eest", true, 10800, "Asia/Gaza"),
    ("eest", true, 10800, "Asia/Hebron"),
    ("eest", true, 10800, "Asia/Istanbul"),
    ("eest", true, 10800, "Asia/Nicosia"),
    ("eest", true, 10800, "Europe/Athens"),
    ("eest", true, 10800, "Europe/Bucharest"),
    ("eest", true, 10800, "Europe/Chisinau"),
    ("eest", true, 10800, "Europe/Istanbul"),
    ("eest", true, 10800, "Europe/Kaliningrad"),
    ("eest", true, 10800, "Europe/Kiev"),
    ("eest", true, 10800, "Europe/Mariehamn"),
    ("eest", true, 10800, "Europe/Minsk"),
    ("eest", true, 10800, "Europe/Moscow"),
    ("eest", true, 10800, "Europe/Nicosia"),
    ("eest", true, 10800, "Europe/Riga"),
    ("eest", true, 10800, "Europe/Simferopol"),
    ("eest", true, 10800, "Europe/Sofia"),
    ("eest", true, 10800, "Europe/Tallinn"),
    ("eest", true, 10800, "Europe/Tiraspol"),
    ("eest", true, 10800, "Europe/Uzhgorod"),
    ("eest", true, 10800, "Europe/Vilnius"),
    ("eest", true, 10800, "Europe/Warsaw"),
    ("eest", true, 10800, "Europe/Zaporozhye"),
    ("eet", false, 7200, "Europe/Helsinki"),
    ("eet", false, 7200, "Africa/Cairo"),
    ("eet", false, 7200, "Africa/Tripoli"),
    ("eet", false, 7200, "Asia/Amman"),
    ("eet", false, 7200, "Asia/Beirut"),
    ("eet", false, 7200, "Asia/Damascus"),
    ("eet", false, 7200, "Asia/Famagusta"),
    ("eet", false, 7200, "Asia/Gaza"),
    ("eet", false, 7200, "Asia/Hebron"),
    ("eet", false, 7200, "Asia/Istanbul"),
    ("eet", false, 7200, "Asia/Nicosia"),
    ("eet", false, 7200, "Europe/Athens"),
    ("eet", false, 7200, "Europe/Bucharest"),
    ("eet", false, 7200, "Europe/Chisinau"),
    ("eet", false, 7200, "Europe/Istanbul"),
    ("eet", false, 7200, "Europe/Kaliningrad"),
    ("eet", false, 7200, "Europe/Kiev"),
    ("eet", false, 7200, "Europe/Mariehamn"),
    ("eet", false, 7200, "Europe/Minsk"),
    ("eet", false, 7200, "Europe/Moscow"),
    ("eet", false, 7200, "Europe/Nicosia"),
    ("eet", false, 7200, "Europe/Riga"),
    ("eet", false, 7200, "Europe/Simferopol"),
    ("eet", false, 7200, "Europe/Sofia"),
    ("eet", false, 7200, "Europe/Tallinn"),
    ("eet", false, 7200, "Europe/Tiraspol"),
    ("eet", false, 7200, "Europe/Uzhgorod"),
    ("eet", false, 7200, "Europe/Vilnius"),
    ("eet", false, 7200, "Europe/Warsaw"),
    ("eet", false, 7200, "Europe/Zaporozhye"),
    ("emt", false, -26248, "Chile/EasterIsland"),
    ("emt", false, -26248, "Pacific/Easter"),
    ("ept", true, -14400, "America/New_York"),
    ("ept", true, -14400, "America/Detroit"),
    ("ept", true, -14400, "America/Iqaluit"),
    ("ept", true, -14400, "America/Montreal"),
    ("ept", true, -14400, "America/Nipigon"),
    ("ept", true, -14400, "America/Thunder_Bay"),
    ("ept", true, -14400, "America/Toronto"),
    ("ept", true, -14400, "Canada/Eastern"),
    ("est", false, -18000, "America/New_York"),
    ("est", false, -18000, "America/Atikokan"),
    ("est", false, -18000, "America/Cambridge_Bay"),
    ("est", false, -18000, "America/Cancun"),
    ("est", false, -18000, "America/Cayman"),
    ("est", false, -18000, "America/Chicago"),
    ("est", false, -18000, "America/Coral_Harbour"),
    ("est", false, -18000, "America/Detroit"),
    ("est", false, -18000, "America/Fort_Wayne"),
    ("est", false, -18000, "America/Grand_Turk"),
    ("est", false, -18000, "America/Indiana/Indianapolis"),
    ("est", false, -18000, "America/Indiana/Knox"),
    ("est", false, -18000, "America/Indiana/Marengo"),
    ("est", false, -18000, "America/Indiana/Petersburg"),
    ("est", false, -18000, "America/Indiana/Tell_City"),
    ("est", false, -18000, "America/Indiana/Vevay"),
    ("est", false, -18000, "America/Indiana/Vincennes"),
    ("est", false, -18000, "America/Indiana/Winamac"),
    ("est", false, -18000, "America/Indianapolis"),
    ("est", false, -18000, "America/Iqaluit"),
    ("est", false, -18000, "America/Jamaica"),
    ("est", false, -18000, "America/Kentucky/Louisville"),
    ("est", false, -18000, "America/Kentucky/Monticello"),
    ("est", false, -18000, "America/Knox_IN"),
    ("est", false, -18000, "America/Louisville"),
    ("est", false, -18000, "America/Managua"),
    ("est", false, -18000, "America/Menominee"),
    ("est", false, -18000, "America/Merida"),
    ("est", false, -18000, "America/Moncton"),
    ("est", false, -18000, "America/Montreal"),
    ("est", false, -18000, "America/Nassau"),
    ("est", false, -18000, "America/Nipigon"),
    ("est", false, -18000, "America/Panama"),
    ("est", false, -18000, "America/Pangnirtung"),
    ("est", false, -18000, "America/Port-au-Prince"),
    ("est", false, -18000, "America/Rankin_Inlet"),
    ("est", false, -18000, "America/Resolute"),
    ("est", false, -18000, "America/Santo_Domingo"),
    ("est", false, -18000, "America/Thunder_Bay"),
    ("est", false, -18000, "America/Toronto"),
    ("est", false, -18000, "Canada/Eastern"),
    ("ewt", true, -14400, "America/New_York"),
    ("ewt", true, -14400, "America/Detroit"),
    ("ewt", true, -14400, "America/Iqaluit"),
    ("ewt", true, -14400, "America/Montreal"),
    ("ewt", true, -14400, "America/Nipigon"),
    ("ewt", true, -14400, "America/Thunder_Bay"),
    ("ewt", true, -14400, "America/Toronto"),
    ("ewt", true, -14400, "Canada/Eastern"),
    ("ffmt", false, -14660, "America/Martinique"),
    ("fmt", false, -4056, "Atlantic/Madeira"),
    ("gdt", true, 39600, "Pacific/Guam"),
    ("gdt", true, 39600, "Pacific/Saipan"),
    ("gmt", false, 0, "Africa/Abidjan"),
    ("gmt", false, 0, "Africa/Accra"),
    ("gmt", false, 0, "Africa/Bamako"),
    ("gmt", false, 0, "Africa/Banjul"),
    ("gmt", false, 0, "Africa/Bissau"),
    ("gmt", false, 0, "Africa/Conakry"),
    ("gmt", false, 0, "Africa/Dakar"),
    ("gmt", false, 0, "Africa/Freetown"),
    ("gmt", false, 0, "Africa/Lome"),
    ("gmt", false, 0, "Africa/Monrovia"),
    ("gmt", false, 0, "Africa/Nouakchott"),
    ("gmt", false, 0, "Africa/Ouagadougou"),
    ("gmt", false, 0, "Africa/Sao_Tome"),
    ("gmt", false, 0, "Africa/Timbuktu"),
    ("gmt", false, 0, "America/Danmarkshavn"),
    ("gmt", false, 0, "Atlantic/Reykjavik"),
    ("gmt", false, 0, "Atlantic/St_Helena"),
    ("gmt", false, 0, "Etc/GMT"),
    ("gmt", false, 0, "Etc/Greenwich"),
    ("gmt", false, 0, "Europe/Belfast"),
    ("gmt", false, 0, "Europe/Dublin"),
    ("gmt", false, 0, "Europe/Gibraltar"),
    ("gmt", false, 0, "Europe/Guernsey"),
    ("gmt", false, 0, "Europe/Isle_of_Man"),
    ("gmt", false, 0, "Europe/Jersey"),
    ("gmt", false, 0, "Europe/London"),
    ("gmt", false, 0, "GB"),
    ("gmt", true, 0, "Europe/Bratislava"),
    ("gmt", true, 0, "Europe/Dublin"),
    ("gmt", true, 0, "Europe/Prague"),
    ("gst", false, 36000, "Pacific/Guam"),
    ("gst", false, 36000, "Pacific/Saipan"),
    ("hdt", true, -34200, "Pacific/Honolulu"),
    ("hdt", true, -32400, "America/Adak"),
    ("hdt", true, -32400, "America/Atka"),
    ("hdt", true, -34200, "Pacific/Johnston"),
    ("hkst", true, 32400, "Asia/Hong_Kong"),
    ("hkt", false, 28800, "Asia/Hong_Kong"),
    ("hkt", false, 30600, "Asia/Hong_Kong"),
    ("hmt", false, -19776, "America/Havana"),
    ("hmt", false, -6872, "Atlantic/Azores"),
    ("hmt", false, 21200, "Asia/Dacca"),
    ("hmt", false, 21200, "Asia/Dhaka"),
    ("hmt", false, 5989, "Europe/Helsinki"),
    ("hmt", false, 5989, "Europe/Mariehamn"),
    ("hpt", true, -34200, "Pacific/Honolulu"),
    ("hpt", true, -34200, "Pacific/Johnston"),
    ("hst", false, -36000, "Pacific/Honolulu"),
    ("hst", false, -37800, "Pacific/Honolulu"),
    ("hst", false, -36000, "America/Adak"),
    ("hst", false, -36000, "America/Atka"),
    ("hst", false, -36000, "Pacific/Johnston"),
    ("hst", false, -37800, "Pacific/Johnston"),
    ("hwt", true, -34200, "Pacific/Honolulu"),
    ("hwt", true, -34200, "Pacific/Johnston"),
    ("iddt", true, 14400, "Asia/Jerusalem"),
    ("iddt", true, 14400, "Asia/Tel_Aviv"),
    ("idt", true, 10800, "Asia/Jerusalem"),
    ("idt", true, 10800, "Asia/Gaza"),
    ("idt", true, 10800, "Asia/Hebron"),
    ("idt", true, 10800, "Asia/Tel_Aviv"),
    ("imt", false, 25025, "Asia/Irkutsk"),
    ("imt", false, 7016, "Asia/Istanbul"),
    ("imt", false, 7016, "Europe/Istanbul"),
    ("ist", false, 7200, "Asia/Jerusalem"),
    ("ist", false, 19800, "Asia/Calcutta"),
    ("ist", false, 19800, "Asia/Kolkata"),
    ("ist", true, 2079, "Europe/Dublin"),
    ("ist", false, 3600, "Europe/Dublin"),
    ("ist", true, 3600, "Europe/Dublin"),
    ("ist", false, 7200, "Asia/Gaza"),
    ("ist", false, 7200, "Asia/Hebron"),
    ("ist", false, 7200, "Asia/Tel_Aviv"),
    ("jdt", true, 36000, "Asia/Tokyo"),
    ("jmt", false, 8440, "Asia/Jerusalem"),
    ("jmt", false, 8440, "Asia/Tel_Aviv"),
    ("jst", false, 32400, "Asia/Tokyo"),
    ("jst", false, 32400, "Asia/Hong_Kong"),
    ("jst", false, 32400, "Asia/Manila"),
    ("jst", false, 32400, "Asia/Pyongyang"),
    ("jst", false, 32400, "Asia/Seoul"),
    ("jst", false, 32400, "Asia/Taipei"),
    ("jst", false, 32400, "ROC"),
    ("jst", false, 32400, "ROK"),
    ("kdt", true, 36000, "Asia/Seoul"),
    ("kdt", true, 34200, "Asia/Seoul"),
    ("kdt", true, 34200, "ROK"),
    ("kdt", true, 36000, "ROK"),
    ("kmt", false, 5736, "Europe/Vilnius"),
    ("kmt", false, -18430, "America/Grand_Turk"),
    ("kmt", false, -18430, "America/Jamaica"),
    ("kmt", false, 7324, "Europe/Kiev"),
    ("kst", false, 30600, "Asia/Seoul"),
    ("kst", false, 32400, "Asia/Pyongyang"),
    ("kst", false, 32400, "Asia/Seoul"),
    ("kst", false, 30600, "Asia/Pyongyang"),
    ("kst", false, 30600, "ROK"),
    ("kst", false, 32400, "ROK"),
    ("lst", true, 9394, "Europe/Riga"),
    ("mddt", true, -18000, "America/Cambridge_Bay"),
    ("mddt", true, -18000, "America/Yellowknife"),
    ("mdst", true, 16279, "Europe/Moscow"),
    ("mdt", true, -21600, "America/Denver"),
    ("mdt", true, -21600, "America/Bahia_Banderas"),
    ("mdt", true, -21600, "America/Boise"),
    ("mdt", true, -21600, "America/Cambridge_Bay"),
    ("mdt", true, -21600, "America/Chihuahua"),
    ("mdt", true, -21600, "America/Edmonton"),
    ("mdt", true, -21600, "America/Hermosillo"),
    ("mdt", true, -21600, "America/Inuvik"),
    ("mdt", true, -21600, "America/Mazatlan"),
    ("mdt", true, -21600, "America/North_Dakota/Beulah"),
    ("mdt", true, -21600, "America/North_Dakota/Center"),
    ("mdt", true, -21600, "America/North_Dakota/New_Salem"),
    ("mdt", true, -21600, "America/Ojinaga"),
    ("mdt", true, -21600, "America/Phoenix"),
    ("mdt", true, -21600, "America/Regina"),
    ("mdt", true, -21600, "America/Shiprock"),
    ("mdt", true, -21600, "America/Swift_Current"),
    ("mdt", true, -21600, "America/Yellowknife"),
    ("mdt", true, -21600, "Canada/Mountain"),
    ("mdt", true, -21600, "Canada/Saskatchewan"),
    ("mdt", true, -21600, "Mexico/BajaSur"),
    ("mest", true, 7200, "MET"),
    ("met", false, 3600, "MET"),
    ("mmt", false, 9017, "Europe/Moscow"),
    ("mmt", false, 9079, "Europe/Moscow"),
    ("mmt", false, -13491, "America/Montevideo"),
    ("mmt", false, -20712, "America/Managua"),
    ("mmt", false, -2588, "Africa/Monrovia"),
    ("mmt", false, -2670, "Africa/Monrovia"),
    ("mmt", false, 17640, "Indian/Maldives"),
    ("mmt", false, 19172, "Asia/Colombo"),
    ("mmt", false, 19270, "Asia/Calcutta"),
    ("mmt", false, 19270, "Asia/Kolkata"),
    ("mmt", false, 28656, "Asia/Makassar"),
    ("mmt", false, 28656, "Asia/Ujung_Pandang"),
    ("mmt", false, 6600, "Europe/Minsk"),
    ("mpt", true, -21600, "America/Denver"),
    ("mpt", true, -21600, "America/Boise"),
    ("mpt", true, -21600, "America/Cambridge_Bay"),
    ("mpt", true, -21600, "America/Edmonton"),
    ("mpt", true, -21600, "America/North_Dakota/Beulah"),
    ("mpt", true, -21600, "America/North_Dakota/Center"),
    ("mpt", true, -21600, "America/North_Dakota/New_Salem"),
    ("mpt", true, -21600, "America/Regina"),
    ("mpt", true, -21600, "America/Shiprock"),
    ("mpt", true, -21600, "America/Swift_Current"),
    ("mpt", true, -21600, "America/Yellowknife"),
    ("mpt", true, -21600, "Canada/Mountain"),
    ("mpt", true, -21600, "Canada/Saskatchewan"),
    ("msd", true, 14400, "Europe/Moscow"),
    ("msd", true, 14400, "Europe/Chisinau"),
    ("msd", true, 14400, "Europe/Kaliningrad"),
    ("msd", true, 14400, "Europe/Kiev"),
    ("msd", true, 14400, "Europe/Minsk"),
    ("msd", true, 14400, "Europe/Riga"),
    ("msd", true, 14400, "Europe/Simferopol"),
    ("msd", true, 14400, "Europe/Tallinn"),
    ("msd", true, 14400, "Europe/Tiraspol"),
    ("msd", true, 14400, "Europe/Uzhgorod"),
    ("msd", true, 14400, "Europe/Vilnius"),
    ("msd", true, 14400, "Europe/Zaporozhye"),
    ("msk", false, 10800, "Europe/Moscow"),
    ("msk", false, 14400, "Europe/Moscow"),
    ("msk", false, 10800, "Europe/Chisinau"),
    ("msk", false, 10800, "Europe/Kaliningrad"),
    ("msk", false, 10800, "Europe/Kiev"),
    ("msk", false, 10800, "Europe/Minsk"),
    ("msk", false, 10800, "Europe/Riga"),
    ("msk", false, 10800, "Europe/Simferopol"),
    ("msk", false, 10800, "Europe/Tallinn"),
    ("msk", false, 10800, "Europe/Tiraspol"),
    ("msk", false, 10800, "Europe/Uzhgorod"),
    ("msk", false, 10800, "Europe/Vilnius"),
    ("msk", false, 10800, "Europe/Zaporozhye"),
    ("msk", false, 14400, "Europe/Simferopol"),
    ("mst", false, -25200, "America/Denver"),
    ("mst", false, -25200, "America/Bahia_Banderas"),
    ("mst", false, -25200, "America/Boise"),
    ("mst", false, -25200, "America/Cambridge_Bay"),
    ("mst", false, -25200, "America/Chihuahua"),
    ("mst", false, -25200, "America/Creston"),
    ("mst", false, -25200, "America/Dawson_Creek"),
    ("mst", false, -25200, "America/Edmonton"),
    ("mst", false, -25200, "America/Ensenada"),
    ("mst", false, -25200, "America/Fort_Nelson"),
    ("mst", false, -25200, "America/Hermosillo"),
    ("mst", false, -25200, "America/Inuvik"),
    ("mst", false, -25200, "America/Mazatlan"),
    ("mst", false, -25200, "America/Mexico_City"),
    ("mst", false, -25200, "America/North_Dakota/Beulah"),
    ("mst", false, -25200, "America/North_Dakota/Center"),
    ("mst", false, -25200, "America/North_Dakota/New_Salem"),
    ("mst", false, -25200, "America/Ojinaga"),
    ("mst", false, -25200, "America/Phoenix"),
    ("mst", false, -25200, "America/Regina"),
    ("mst", false, -25200, "America/Santa_Isabel"),
    ("mst", false, -25200, "America/Shiprock"),
    ("mst", false, -25200, "America/Swift_Current"),
    ("mst", false, -25200, "America/Tijuana"),
    ("mst", false, -25200, "America/Yellowknife"),
    ("mst", false, -25200, "Canada/Mountain"),
    ("mst", false, -25200, "Canada/Saskatchewan"),
    ("mst", false, -25200, "Mexico/BajaNorte"),
    ("mst", false, -25200, "Mexico/BajaSur"),
    ("mst", false, -25200, "Mexico/General"),
    ("mst", true, 12679, "Europe/Moscow"),
    ("mwt", true, -21600, "America/Denver"),
    ("mwt", true, -21600, "America/Boise"),
    ("mwt", true, -21600, "America/Cambridge_Bay"),
    ("mwt", true, -21600, "America/Edmonton"),
    ("mwt", true, -21600, "America/North_Dakota/Beulah"),
    ("mwt", true, -21600, "America/North_Dakota/Center"),
    ("mwt", true, -21600, "America/North_Dakota/New_Salem"),
    ("mwt", true, -21600, "America/Phoenix"),
    ("mwt", true, -21600, "America/Regina"),
    ("mwt", true, -21600, "America/Shiprock"),
    ("mwt", true, -21600, "America/Swift_Current"),
    ("mwt", true, -21600, "America/Yellowknife"),
    ("mwt", true, -21600, "Canada/Mountain"),
    ("mwt", true, -21600, "Canada/Saskatchewan"),
    ("nddt", true, -5400, "America/St_Johns"),
    ("nddt", true, -5400, "Canada/Newfoundland"),
    ("ndt", true, -9052, "America/St_Johns"),
    ("ndt", true, -9000, "America/St_Johns"),
    ("ndt", true, -9000, "America/Goose_Bay"),
    ("ndt", true, -9000, "Canada/Newfoundland"),
    ("ndt", true, -9052, "America/Goose_Bay"),
    ("ndt", true, -9052, "Canada/Newfoundland"),
    ("npt", true, -9000, "America/St_Johns"),
    ("npt", true, -36000, "America/Adak"),
    ("npt", true, -36000, "America/Atka"),
    ("npt", true, -36000, "America/Nome"),
    ("npt", true, -9000, "America/Goose_Bay"),
    ("npt", true, -9000, "Canada/Newfoundland"),
    ("nst", false, -12600, "America/St_Johns"),
    ("nst", false, -12652, "America/St_Johns"),
    ("nst", true, 4772, "Europe/Amsterdam"),
    ("nst", false, -12600, "America/Goose_Bay"),
    ("nst", false, -12600, "Canada/Newfoundland"),
    ("nst", false, -12652, "America/Goose_Bay"),
    ("nst", false, -12652, "Canada/Newfoundland"),
    ("nst", false, -39600, "America/Adak"),
    ("nst", false, -39600, "America/Atka"),
    ("nst", false, -39600, "America/Nome"),
    ("nwt", true, -9000, "America/St_Johns"),
    ("nwt", true, -36000, "America/Adak"),
    ("nwt", true, -36000, "America/Atka"),
    ("nwt", true, -36000, "America/Nome"),
    ("nwt", true, -9000, "America/Goose_Bay"),
    ("nwt", true, -9000, "Canada/Newfoundland"),
    ("nzdt", true, 46800, "Pacific/Auckland"),
    ("nzdt", true, 46800, "Antarctica/McMurdo"),
    ("nzdt", true, 46800, "Antarctica/South_Pole"),
    ("nzdt", true, 46800, "NZ"),
    ("nzmt", false, 41400, "Pacific/Auckland"),
    ("nzmt", false, 41400, "Antarctica/McMurdo"),
    ("nzmt", false, 41400, "Antarctica/South_Pole"),
    ("nzmt", false, 41400, "NZ"),
    ("nzst", false, 43200, "Pacific/Auckland"),
    ("nzst", true, 43200, "Pacific/Auckland"),
    ("nzst", true, 45000, "Pacific/Auckland"),
    ("nzst", false, 43200, "Antarctica/McMurdo"),
    ("nzst", false, 43200, "Antarctica/South_Pole"),
    ("nzst", false, 43200, "NZ"),
    ("nzst", true, 43200, "Antarctica/McMurdo"),
    ("nzst", true, 43200, "Antarctica/South_Pole"),
    ("nzst", true, 43200, "NZ"),
    ("nzst", true, 45000, "Antarctica/McMurdo"),
    ("nzst", true, 45000, "Antarctica/South_Pole"),
    ("nzst", true, 45000, "NZ"),
    ("pddt", true, -21600, "America/Inuvik"),
    ("pdt", true, -25200, "America/Los_Angeles"),
    ("pdt", true, -25200, "America/Boise"),
    ("pdt", true, -25200, "America/Dawson"),
    ("pdt", true, -25200, "America/Dawson_Creek"),
    ("pdt", true, -25200, "America/Ensenada"),
    ("pdt", true, -25200, "America/Fort_Nelson"),
    ("pdt", true, -25200, "America/Juneau"),
    ("pdt", true, -25200, "America/Metlakatla"),
    ("pdt", true, -25200, "America/Santa_Isabel"),
    ("pdt", true, -25200, "America/Sitka"),
    ("pdt", true, -25200, "America/Tijuana"),
    ("pdt", true, -25200, "America/Vancouver"),
    ("pdt", true, -25200, "America/Whitehorse"),
    ("pdt", true, -25200, "Canada/Pacific"),
    ("pdt", true, -25200, "Canada/Yukon"),
    ("pdt", true, -25200, "Mexico/BajaNorte"),
    ("pdt", true, 32400, "Asia/Manila"),
    ("pkst", true, 21600, "Asia/Karachi"),
    ("pkt", false, 18000, "Asia/Karachi"),
    ("plmt", false, 25590, "Asia/Ho_Chi_Minh"),
    ("plmt", false, 25590, "Asia/Saigon"),
    ("pmt", false, -13236, "America/Paramaribo"),
    ("pmt", false, -13252, "America/Paramaribo"),
    ("pmt", false, 13505, "Asia/Yekaterinburg"),
    ("pmt", false, 26240, "Asia/Pontianak"),
    ("pmt", false, 561, "Africa/Algiers"),
    ("pmt", false, 561, "Africa/Tunis"),
    ("pmt", false, 561, "Europe/Monaco"),
    ("pmt", false, 561, "Europe/Paris"),
    ("ppmt", false, -17340, "America/Port-au-Prince"),
    ("ppt", true, -25200, "America/Los_Angeles"),
    ("ppt", true, -25200, "America/Dawson_Creek"),
    ("ppt", true, -25200, "America/Ensenada"),
    ("ppt", true, -25200, "America/Fort_Nelson"),
    ("ppt", true, -25200, "America/Juneau"),
    ("ppt", true, -25200, "America/Metlakatla"),
    ("ppt", true, -25200, "America/Santa_Isabel"),
    ("ppt", true, -25200, "America/Sitka"),
    ("ppt", true, -25200, "America/Tijuana"),
    ("ppt", true, -25200, "America/Vancouver"),
    ("ppt", true, -25200, "Canada/Pacific"),
    ("ppt", true, -25200, "Mexico/BajaNorte"),
    ("pst", false, -28800, "America/Los_Angeles"),
    ("pst", false, -28800, "America/Bahia_Banderas"),
    ("pst", false, -28800, "America/Boise"),
    ("pst", false, -28800, "America/Creston"),
    ("pst", false, -28800, "America/Dawson"),
    ("pst", false, -28800, "America/Dawson_Creek"),
    ("pst", false, -28800, "America/Ensenada"),
    ("pst", false, -28800, "America/Fort_Nelson"),
    ("pst", false, -28800, "America/Hermosillo"),
    ("pst", false, -28800, "America/Inuvik"),
    ("pst", false, -28800, "America/Juneau"),
    ("pst", false, -28800, "America/Mazatlan"),
    ("pst", false, -28800, "America/Metlakatla"),
    ("pst", false, -28800, "America/Santa_Isabel"),
    ("pst", false, -28800, "America/Sitka"),
    ("pst", false, -28800, "America/Tijuana"),
    ("pst", false, -28800, "America/Vancouver"),
    ("pst", false, -28800, "America/Whitehorse"),
    ("pst", false, -28800, "Canada/Pacific"),
    ("pst", false, -28800, "Canada/Yukon"),
    ("pst", false, -28800, "Mexico/BajaNorte"),
    ("pst", false, -28800, "Mexico/BajaSur"),
    ("pst", false, 28800, "Asia/Manila"),
    ("pwt", true, -25200, "America/Los_Angeles"),
    ("pwt", true, -25200, "America/Dawson_Creek"),
    ("pwt", true, -25200, "America/Ensenada"),
    ("pwt", true, -25200, "America/Fort_Nelson"),
    ("pwt", true, -25200, "America/Juneau"),
    ("pwt", true, -25200, "America/Metlakatla"),
    ("pwt", true, -25200, "America/Santa_Isabel"),
    ("pwt", true, -25200, "America/Sitka"),
    ("pwt", true, -25200, "America/Tijuana"),
    ("pwt", true, -25200, "America/Vancouver"),
    ("pwt", true, -25200, "Canada/Pacific"),
    ("pwt", true, -25200, "Mexico/BajaNorte"),
    ("qmt", false, -18840, "America/Guayaquil"),
    ("rmt", false, 5794, "Europe/Riga"),
    ("rmt", false, 23087, "Asia/Rangoon"),
    ("rmt", false, 23087, "Asia/Yangon"),
    ("sast", false, 7200, "Africa/Johannesburg"),
    ("sast", true, 10800, "Africa/Johannesburg"),
    ("sast", false, 5400, "Africa/Johannesburg"),
    ("sast", true, 10800, "Africa/Maseru"),
    ("sast", true, 10800, "Africa/Mbabane"),
    ("sast", true, 10800, "Africa/Windhoek"),
    ("sast", false, 5400, "Africa/Maseru"),
    ("sast", false, 5400, "Africa/Mbabane"),
    ("sast", false, 7200, "Africa/Maseru"),
    ("sast", false, 7200, "Africa/Mbabane"),
    ("sast", false, 7200, "Africa/Windhoek"),
    ("sdmt", false, -16800, "America/Santo_Domingo"),
    ("sjmt", false, -20173, "America/Costa_Rica"),
    ("smt", false, -13884, "Atlantic/Stanley"),
    ("smt", false, -16966, "America/Punta_Arenas"),
    ("smt", false, -16966, "America/Santiago"),
    ("smt", false, -16966, "Chile/Continental"),
    ("smt", false, 24925, "Asia/Kuala_Lumpur"),
    ("smt", false, 24925, "Asia/Singapore"),
    ("smt", false, 8160, "Europe/Simferopol"),
    ("sst", false, -39600, "Pacific/Samoa"),
    ("sst", false, -39600, "Pacific/Midway"),
    ("sst", false, -39600, "Pacific/Pago_Pago"),
    ("tbmt", false, 10751, "Asia/Tbilisi"),
    ("tmt", false, 12344, "Asia/Tehran"),
    ("tmt", false, 5940, "Europe/Tallinn"),
    ("uct", false, 0, "Etc/UCT"),
    ("utc", false, 0, "Etc/Universal"),
    ("utc", false, 0, "Etc/UTC"),
    ("utc", false, 0, "Etc/Zulu"),
    ("utc", false, 0, "UTC"),
    ("utc", false, 0, "UTC"),
    ("wast", true, 7200, "Africa/Windhoek"),
    ("wast", true, 7200, "Africa/Ndjamena"),
    ("wat", false, 3600, "Africa/Brazzaville"),
    ("wat", false, 3600, "Africa/Bangui"),
    ("wat", false, 3600, "Africa/Douala"),
    ("wat", false, 3600, "Africa/Kinshasa"),
    ("wat", false, 3600, "Africa/Lagos"),
    ("wat", false, 3600, "Africa/Libreville"),
    ("wat", false, 3600, "Africa/Luanda"),
    ("wat", false, 3600, "Africa/Malabo"),
    ("wat", false, 3600, "Africa/Ndjamena"),
    ("wat", false, 3600, "Africa/Niamey"),
    ("wat", false, 3600, "Africa/Porto-Novo"),
    ("wat", false, 3600, "Africa/Sao_Tome"),
    ("wat", true, 3600, "Africa/Windhoek"),
    ("wemt", true, 7200, "Europe/Lisbon"),
    ("wemt", true, 7200, "Europe/Madrid"),
    ("wemt", true, 7200, "Europe/Monaco"),
    ("wemt", true, 7200, "Europe/Paris"),
    ("west", true, 3600, "Europe/Paris"),
    ("west", true, 7200, "Europe/Luxembourg"),
    ("west", true, 3600, "Africa/Algiers"),
    ("west", true, 3600, "Africa/Ceuta"),
    ("west", true, 3600, "Atlantic/Canary"),
    ("west", true, 3600, "Atlantic/Faeroe"),
    ("west", true, 3600, "Atlantic/Faroe"),
    ("west", true, 3600, "Atlantic/Madeira"),
    ("west", true, 3600, "Europe/Brussels"),
    ("west", true, 3600, "Europe/Lisbon"),
    ("west", true, 3600, "Europe/Luxembourg"),
    ("west", true, 3600, "Europe/Madrid"),
    ("west", true, 3600, "Europe/Monaco"),
    ("wet", false, 0, "Europe/Paris"),
    ("wet", false, 3600, "Europe/Luxembourg"),
    ("wet", false, 0, "Africa/Algiers"),
    ("wet", false, 0, "Africa/Ceuta"),
    ("wet", false, 0, "Atlantic/Azores"),
    ("wet", false, 0, "Atlantic/Canary"),
    ("wet", false, 0, "Atlantic/Faeroe"),
    ("wet", false, 0, "Atlantic/Faroe"),
    ("wet", false, 0, "Atlantic/Madeira"),
    ("wet", false, 0, "Europe/Andorra"),
    ("wet", false, 0, "Europe/Brussels"),
    ("wet", false, 0, "Europe/Lisbon"),
    ("wet", false, 0, "Europe/Luxembourg"),
    ("wet", false, 0, "Europe/Madrid"),
    ("wet", false, 0, "Europe/Monaco"),
    ("wib", false, 25200, "Asia/Jakarta"),
    ("wib", false, 25200, "Asia/Pontianak"),
    ("wita", false, 28800, "Asia/Makassar"),
    ("wita", false, 28800, "Asia/Pontianak"),
    ("wita", false, 28800, "Asia/Ujung_Pandang"),
    ("wit", false, 32400, "Asia/Jayapura"),
    ("wmt", false, 5040, "Europe/Vilnius"),
    ("wmt", false, 5040, "Europe/Warsaw"),
    ("yddt", true, -25200, "America/Dawson"),
    ("yddt", true, -25200, "America/Whitehorse"),
    ("yddt", true, -25200, "Canada/Yukon"),
    ("ydt", true, -28800, "America/Dawson"),
    ("ydt", true, -28800, "America/Juneau"),
    ("ydt", true, -28800, "America/Whitehorse"),
    ("ydt", true, -28800, "America/Yakutat"),
    ("ydt", true, -28800, "Canada/Yukon"),
    ("ypt", true, -28800, "America/Dawson"),
    ("ypt", true, -28800, "America/Whitehorse"),
    ("ypt", true, -28800, "America/Yakutat"),
    ("ypt", true, -28800, "Canada/Yukon"),
    ("yst", false, -32400, "America/Anchorage"),
    ("yst", false, -32400, "America/Dawson"),
    ("yst", false, -32400, "America/Juneau"),
    ("yst", false, -32400, "America/Nome"),
    ("yst", false, -32400, "America/Sitka"),
    ("yst", false, -32400, "America/Whitehorse"),
    ("yst", false, -32400, "America/Yakutat"),
    ("yst", false, -32400, "Canada/Yukon"),
    ("ywt", true, -28800, "America/Dawson"),
    ("ywt", true, -28800, "America/Whitehorse"),
    ("ywt", true, -28800, "America/Yakutat"),
    ("ywt", true, -28800, "Canada/Yukon"),
    ("a", false, 3600, ""),
    ("b", false, 7200, ""),
    ("c", false, 10800, ""),
    ("d", false, 14400, ""),
    ("e", false, 18000, ""),
    ("f", false, 21600, ""),
    ("g", false, 25200, ""),
    ("h", false, 28800, ""),
    ("i", false, 32400, ""),
    ("k", false, 36000, ""),
    ("l", false, 39600, ""),
    ("m", false, 43200, ""),
    ("n", false, -3600, ""),
    ("o", false, -7200, ""),
    ("p", false, -10800, ""),
    ("q", false, -14400, ""),
    ("r", false, -18000, ""),
    ("s", false, -21600, ""),
    ("t", false, -25200, ""),
    ("u", false, -28800, ""),
    ("v", false, -32400, ""),
    ("w", false, -36000, ""),
    ("x", false, -39600, ""),
    ("y", false, -43200, ""),
    ("z", false, 0, ""),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_the_three_timezone_shapes() {
        assert_eq!(Tz::parse("+05:30"), Some(Tz::Offset(19_800)));
        assert_eq!(Tz::parse("GMT+5"), Some(Tz::Offset(18_000)));
        assert_eq!(Tz::parse("-08"), Some(Tz::Offset(-28_800)));
        assert_eq!(Tz::parse("+01:00:30"), Some(Tz::Offset(3_630)));
        assert_eq!(Tz::parse("0530"), None);
        assert_eq!(Tz::parse("gmt+5"), None);
        assert_eq!(Tz::parse("UTC").map(|t| t.type_id()), Some(3));
        assert_eq!(Tz::parse("GMT").map(|t| t.type_id()), Some(2));
        assert_eq!(Tz::parse("CET").map(|t| t.type_id()), Some(2));
        assert_eq!(Tz::parse("PST8PDT").map(|t| t.type_id()), Some(3));
        assert_eq!(Tz::parse("Europe/Berlin").map(|t| t.type_id()), Some(3));
        assert_eq!(Tz::parse("Nowhere/Nothing"), None);
        assert_eq!(Tz::parse("+05:30").unwrap().name(), "+05:30");
        assert_eq!(Tz::parse("+01:00:30").unwrap().name(), "+01:00:30");
    }

    #[test]
    fn resolves_local_time_across_a_dst_transition() {
        let berlin = Tz::Id("Europe/Berlin".to_string());
        // The gap: 02:30 does not exist and php reports 03:30+02:00.
        let sse = 1_616_898_600; // 2021-03-28 02:30 read as UTC
        assert_eq!(berlin.resolve(sse, None), 1_616_895_000);
        // The overlap: a fresh parse takes CET, a `modify` from a CEST
        // instant keeps CEST.
        let sse = 1_635_647_400; // 2021-10-31 02:30 read as UTC
        assert_eq!(berlin.resolve(sse, None), 1_635_643_800);
        assert_eq!(berlin.resolve(sse, Some(7_200)), 1_635_640_200);
        assert_eq!(berlin.resolve(sse, Some(3_600)), 1_635_643_800);
        // New York folds the other way round: the offset at `sse` is the
        // *earlier* of the two.
        let ny = Tz::Id("America/New_York".to_string());
        assert_eq!(ny.resolve(1_636_248_600, None), 1_636_263_000);
        assert_eq!(ny.resolve(1_615_689_000, None), 1_615_707_000);
    }

    #[test]
    fn reports_offsets_abbreviations_and_dst() {
        let berlin = Tz::Id("Europe/Berlin".to_string());
        assert_eq!(
            berlin.info(1_626_343_200),
            (7_200, "CEST".to_string(), true)
        );
        assert_eq!(
            berlin.info(1_610_708_400),
            (3_600, "CET".to_string(), false)
        );
        assert_eq!(Tz::Offset(19_800).info(0).1, "GMT+0530");
        assert_eq!(Tz::Offset(-28_800).info(0).1, "GMT-0800");
    }
}
