[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rphp-test.workspace = true
rphp-ext-api.workspace = true
walkdir.workspace = true
rayon.workspace = true
regex.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
pico-args.workspace = true
tempfile.workspace = true
rphp-span.workspace = true
rphp-source.workspace = true
rphp-intern.workspace = true
rphp-diagnostics.workspace = true
rphp-lexer.workspace = true
rphp-ast.workspace = true
rphp-parser.workspace = true
rphp-tokenizer.workspace = true
