<?php
// Tier-A differential: NumberFormatter — the pattern-driven styles over
// ICU's locale patterns and symbols, rounding on decimal digits, the
// attributes and text attributes, symbols, custom patterns, currencies
// with their own digits and symbols, parsing back, the error paths.
foreach (['en_US', 'de_DE', 'fr_FR', 'en_US_POSIX', 'hi_IN', 'ja_JP', 'de_CH', 'es_ES', 'pt_BR', 'sv_SE', 'ru_RU', 'zh_CN', 'it_IT', 'nl_NL', 'pl_PL', 'tr_TR', 'ar_EG', 'en_GB', 'en_IN', 'fr_CA', 'de_AT', 'cs_CZ', 'da_DK', 'fi_FI', 'ko_KR', 'he_IL', 'th_TH', 'id_ID', 'nb_NO', 'uk_UA'] as $l) {
    $out = [];
    foreach ([NumberFormatter::DECIMAL, NumberFormatter::CURRENCY, NumberFormatter::PERCENT, NumberFormatter::SCIENTIFIC, NumberFormatter::CURRENCY_ACCOUNTING] as $style) {
        $f = new NumberFormatter($l, $style);
        $out[] = $f->getPattern() . " | " . $f->format(1234567.891) . " | " . $f->format(-0.5) . " | " . $f->format(0) . " | " . $f->getSymbol(NumberFormatter::DECIMAL_SEPARATOR_SYMBOL) . $f->getSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL) . $f->getSymbol(NumberFormatter::CURRENCY_SYMBOL) . "/" . $f->getTextAttribute(NumberFormatter::CURRENCY_CODE) . " " . $f->formatCurrency(1234.5, "EUR") . " " . $f->formatCurrency(-1234.5, "JPY") . " " . $f->getLocale(Locale::VALID_LOCALE);
    }
    echo "[$l] ", implode(" || ", $out), "\n";
}
$f = new NumberFormatter("en_US", NumberFormatter::DECIMAL);
var_dump($f->format(1234.5678), $f->format(-0.0), $f->format(0.125, NumberFormatter::TYPE_DOUBLE), $f->format(12345678901234567), $f->format(1e20), $f->format(1.5e-7), $f->format(NAN), $f->format(INF), $f->format(-INF), $f->format("12.5"), $f->format(3, NumberFormatter::TYPE_INT32), $f->format(2.7, NumberFormatter::TYPE_INT64), $f->format(2.7, NumberFormatter::TYPE_INT32), $f->format(PHP_INT_MAX), $f->format(PHP_INT_MIN), $f->format(0.1 + 0.2), $f->format(2.5), $f->format(3.5), $f->format(0.0005), $f->format(0.0015), $f->format(1e15), $f->format(1e16), $f->format(123456789012345678), $f->format(0.1), $f->format(100), $f->format(true), $f->format(1.0), $f->format(-1234.5678), $f->format(999.9995), $f->format(0.9995), $f->format(1e-10), $f->format(123456.7891));
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 2); var_dump($f->getPattern(), $f->format(1.005), $f->format(1.015), $f->format(2), $f->getAttribute(NumberFormatter::MIN_FRACTION_DIGITS), $f->getAttribute(NumberFormatter::MAX_FRACTION_DIGITS), $f->getAttribute(NumberFormatter::FRACTION_DIGITS));
$f->setAttribute(NumberFormatter::ROUNDING_MODE, NumberFormatter::ROUND_HALFUP); var_dump($f->format(1.005), $f->format(2.5), $f->format(-2.5), $f->getAttribute(NumberFormatter::ROUNDING_MODE));
foreach ([NumberFormatter::ROUND_CEILING, NumberFormatter::ROUND_FLOOR, NumberFormatter::ROUND_DOWN, NumberFormatter::ROUND_UP, NumberFormatter::ROUND_HALFEVEN, NumberFormatter::ROUND_HALFDOWN, NumberFormatter::ROUND_HALFUP, NumberFormatter::ROUND_HALFODD] as $m) { $f->setAttribute(NumberFormatter::ROUNDING_MODE, $m); echo $m, ": ", implode(" ", array_map(fn($v) => $f->format($v), [1.125, 1.135, -1.125, -1.135, 1.001, -1.001, 2.5, 0.005, -0.005])), "\n"; }
$f->setAttribute(NumberFormatter::ROUNDING_MODE, NumberFormatter::ROUND_HALFEVEN);
$f->setAttribute(NumberFormatter::GROUPING_USED, 0); var_dump($f->getPattern(), $f->format(1234567.891));
$f->setAttribute(NumberFormatter::MIN_INTEGER_DIGITS, 5); var_dump($f->getPattern(), $f->format(12.3));
$f->setAttribute(NumberFormatter::MAX_INTEGER_DIGITS, 3); var_dump($f->getPattern(), $f->format(123456.7), $f->getAttribute(NumberFormatter::MAX_INTEGER_DIGITS), $f->getAttribute(NumberFormatter::INTEGER_DIGITS));
$g = new NumberFormatter("en_US", NumberFormatter::PATTERN_DECIMAL, "#,##0.0#;(#)"); var_dump($g->getPattern(), $g->format(1234.5), $g->format(-1234.567), $g->format(0), $g->getTextAttribute(NumberFormatter::NEGATIVE_PREFIX), $g->getTextAttribute(NumberFormatter::NEGATIVE_SUFFIX), $g->getTextAttribute(NumberFormatter::POSITIVE_PREFIX));
$h = new NumberFormatter("en_US", NumberFormatter::DECIMAL);
foreach (["00.00", "#,##,##0.###", "@@@", "@@#", "*x##0.0", "#,##0.00 ¤", "#0.###E0", "##0.###E0", "#E0", "0.###E+00", "#%", "#‰", "#,##0.###;#,##0.###-", "0.05", "#,##0.###;", "bad{{", "", "'abc'#'def'", "#,##0.00;-#,##0.00", "0000000000.0000", "#.##", "#,##0", "#,##0.0000000000", "#,##0.###E0", "0.00E0", "'#'#", "¤¤ #,##0.00", "#,##0.00 ¤¤¤", "#,##0.00 ¤¤¤;(#,##0.00 ¤¤¤)"] as $pat) {
    $ok = $h->setPattern($pat);
    echo json_encode($pat), " => ", var_export($ok, true), " ", var_export($h->getPattern(), true), " | ", implode(" ", array_map(fn($v) => var_export($h->format($v), true), [12345.678, 0.000123, 5, -5.5, 0, 1e6, 0.5])), " | inc=", $h->getAttribute(NumberFormatter::ROUNDING_INCREMENT), " mul=", $h->getAttribute(NumberFormatter::MULTIPLIER), " gs=", $h->getAttribute(NumberFormatter::GROUPING_SIZE), " sg=", $h->getAttribute(NumberFormatter::SECONDARY_GROUPING_SIZE), " sig=", $h->getAttribute(NumberFormatter::SIGNIFICANT_DIGITS_USED), " w=", $h->getAttribute(NumberFormatter::FORMAT_WIDTH), " pad=", json_encode($h->getTextAttribute(NumberFormatter::PADDING_CHARACTER)), " pp=", json_encode($h->getTextAttribute(NumberFormatter::POSITIVE_PREFIX)), " ps=", json_encode($h->getTextAttribute(NumberFormatter::POSITIVE_SUFFIX)), " np=", json_encode($h->getTextAttribute(NumberFormatter::NEGATIVE_PREFIX)), " ns=", json_encode($h->getTextAttribute(NumberFormatter::NEGATIVE_SUFFIX)), " min=", $h->getAttribute(NumberFormatter::MIN_FRACTION_DIGITS), "/", $h->getAttribute(NumberFormatter::MAX_FRACTION_DIGITS), " int=", $h->getAttribute(NumberFormatter::MIN_INTEGER_DIGITS), "/", $h->getAttribute(NumberFormatter::MAX_INTEGER_DIGITS), " das=", $h->getAttribute(NumberFormatter::DECIMAL_ALWAYS_SHOWN), "\n";
}
$p = 0; $f = new NumberFormatter("en_US", NumberFormatter::DECIMAL);
var_dump($f->parse("1,234.5"), $f->parse("1,234.5", NumberFormatter::TYPE_INT32), $f->parse("1,234.5", NumberFormatter::TYPE_INT64), $f->parse("1,234.5", NumberFormatter::TYPE_DOUBLE, $p), $p, $f->parse("abc"), $f->getErrorCode(), $f->getErrorMessage(), $f->parse("12abc", NumberFormatter::TYPE_DOUBLE, $p), $p, $f->parse("  42"), $f->parse("-42"), $f->parse("(42)"), $f->parse("1e3"), $f->parse("1E3"), $f->parse("∞"), $f->parse("NaN"), $f->parse("1.5.5", NumberFormatter::TYPE_DOUBLE, $p), $p, $f->parse(""), $f->getErrorCode(), $f->parse("9223372036854775808"), $f->parse("9223372036854775808", NumberFormatter::TYPE_INT64), $f->parse("3.9", NumberFormatter::TYPE_INT32), $f->parse("1,2,3"), $f->parse("1 234"), $f->parse(".5"), $f->parse("5."), $f->parse("0x10"), $f->parse("1_000"), $f->parse("-1,234,567.89"), $f->parse("1234567.89"), $f->parse("00012"), $f->parse("1.5e2"));
$p = 3; var_dump($f->parse("xx 1,234.5 yy", NumberFormatter::TYPE_DOUBLE, $p), $p);
$c = new NumberFormatter("en_US", NumberFormatter::CURRENCY); $cur = "";
var_dump($c->parseCurrency("$1,234.50", $cur), $cur, $c->parseCurrency("€1,234.50", $cur), $cur, $c->parseCurrency("abc", $cur), $c->getErrorMessage(), $c->parse("$1,234.50"), $c->parse("1234.5"), $c->getErrorCode());
var_dump($c->formatCurrency(1234.567, "EUR"), $c->formatCurrency(1234.567, "JPY"), $c->formatCurrency(1234.567, "BHD"), $c->formatCurrency(1234.567, "XXX"), $c->formatCurrency(1234.567, "ZZZ"), $c->formatCurrency(1234.567, "eur"), $c->formatCurrency(1234.567, "E"), $c->getErrorMessage(), $c->formatCurrency(-1234.567, "USD"));
foreach (["CHF", "CAD", "AUD", "GBP", "INR", "CNY", "BRL", "SEK", "KRW", "MXN", "PLN", "TRY", "RUB", "HKD", "NZD", "SGD", "ILS", "ZAR", "CZK", "DKK", "NOK", "HUF", "THB", "TWD", "VND", "PHP", "IDR", "SAR", "AED", "EGP", "NGN", "UAH", "BTC", "XAU", "KWD", "CLP", "ISK", "TND"] as $code) echo $code, "=", $c->formatCurrency(1234.567, $code), " "; echo "\n";
$d = new NumberFormatter("de_DE", NumberFormatter::CURRENCY); foreach (["CHF", "USD", "JPY", "GBP", "EUR", "INR", "CNY", "BRL", "KRW"] as $code) echo $code, "=", $d->formatCurrency(-1234.567, $code), " "; echo "\n";
$j = new NumberFormatter("ja_JP", NumberFormatter::CURRENCY); foreach (["JPY", "USD", "EUR", "CNY", "KRW"] as $code) echo $code, "=", $j->formatCurrency(1234.567, $code), " "; echo "\n";
var_dump($c->setTextAttribute(NumberFormatter::CURRENCY_CODE, "EUR"), $c->format(1234.5), $c->getSymbol(NumberFormatter::CURRENCY_SYMBOL), $c->getSymbol(NumberFormatter::INTL_CURRENCY_SYMBOL), $c->setSymbol(NumberFormatter::CURRENCY_SYMBOL, "EUR "), $c->format(1234.5), $c->formatCurrency(5, "USD"), $c->format(5), $c->setSymbol(99, "x"), $c->getSymbol(99), $c->getErrorMessage(), $c->getTextAttribute(99), $c->getErrorMessage(), $c->setTextAttribute(99, "x"), $c->getErrorMessage(), $c->getAttribute(99), $c->getErrorMessage(), $c->setAttribute(99, 1), $c->getErrorMessage(), $c->getLocale(99), $c->getErrorMessage(), $c->getLocale(Locale::ACTUAL_LOCALE));
$j = new NumberFormatter("en_US", NumberFormatter::DECIMAL); var_dump($j->setTextAttribute(NumberFormatter::POSITIVE_PREFIX, "pre-"), $j->getPattern(), $j->format(5), $j->setTextAttribute(NumberFormatter::NEGATIVE_PREFIX, "neg#"), $j->getPattern(), $j->format(-5), $j->getTextAttribute(NumberFormatter::NEGATIVE_PREFIX), $j->setTextAttribute(NumberFormatter::PADDING_CHARACTER, "_"), $j->setAttribute(NumberFormatter::FORMAT_WIDTH, 12), $j->getPattern(), $j->format(5), $j->setAttribute(NumberFormatter::PADDING_POSITION, NumberFormatter::PAD_AFTER_PREFIX), $j->getPattern(), $j->format(5), $j->setAttribute(NumberFormatter::SIGNIFICANT_DIGITS_USED, 1), $j->setAttribute(NumberFormatter::MAX_SIGNIFICANT_DIGITS, 4), $j->getPattern(), $j->format(1234567), $j->format(0.00012345), $j->setAttribute(NumberFormatter::SIGNIFICANT_DIGITS_USED, 0), $j->getPattern(), $j->setAttribute(NumberFormatter::ROUNDING_INCREMENT, 0.25), $j->getPattern(), $j->format(1.13), $j->getAttribute(NumberFormatter::ROUNDING_INCREMENT), $j->setAttribute(NumberFormatter::MULTIPLIER, 3), $j->getPattern(), $j->format(2), $j->getAttribute(NumberFormatter::MULTIPLIER));
$k = new NumberFormatter("de_DE", NumberFormatter::DECIMAL); var_dump($k->setSymbol(NumberFormatter::DECIMAL_SEPARATOR_SYMBOL, "#"), $k->setSymbol(NumberFormatter::GROUPING_SEPARATOR_SYMBOL, "'"), $k->format(1234567.891), $k->parse("1'234#5"), $k->setSymbol(NumberFormatter::ZERO_DIGIT_SYMBOL, "٠"), $k->format(1234567.891), $k->setSymbol(NumberFormatter::MINUS_SIGN_SYMBOL, "minus"), $k->format(-5), $k->setSymbol(NumberFormatter::NAN_SYMBOL, "nope"), $k->format(NAN), $k->setSymbol(NumberFormatter::INFINITY_SYMBOL, "inf"), $k->format(-INF));
foreach ([NumberFormatter::CURRENCY_ISO, NumberFormatter::CURRENCY_PLURAL, NumberFormatter::CASH_CURRENCY, NumberFormatter::CURRENCY_STANDARD, NumberFormatter::DECIMAL_COMPACT_SHORT, NumberFormatter::DECIMAL_COMPACT_LONG] as $s) { $f = new NumberFormatter("en_US", $s); echo $s, ": pat=", var_export($f->getPattern(), true), " ", $f->format(1234567.891), " | ", $f->format(1.5), " | ", $f->format(-3), " | ", $f->formatCurrency(1234.5, "EUR"), " | ", $f->formatCurrency(1234.5, "CHF"), " | ", $f->format(0), " | ", $f->format(999999), " | ", $f->format(1000), "\n"; }
var_dump(numfmt_create("en", 99), intl_get_error_message(), numfmt_create("xx", 1) ?? "x");
try { new NumberFormatter("xx", NumberFormatter::DECIMAL); } catch (ValueError $e) { echo $e->getMessage(), "\n"; }
try { new NumberFormatter("root", NumberFormatter::DECIMAL); } catch (ValueError $e) { echo $e->getMessage(), "\n"; }
try { $f->format(2.7, 99); } catch (ValueError $e) { echo $e->getMessage(), "\n"; }
$e = new NumberFormatter("en_US", NumberFormatter::PATTERN_DECIMAL); var_dump($e->getPattern(), $e->format(3), (new NumberFormatter("de_XX", NumberFormatter::CURRENCY))->getLocale(Locale::VALID_LOCALE), (new NumberFormatter("en_150", NumberFormatter::CURRENCY))->format(5), (new NumberFormatter("de-DE-u-nu-arab", NumberFormatter::CURRENCY))->format(1234.5), (new NumberFormatter("en_US@numbers=arab", NumberFormatter::DECIMAL))->format(1234.5), (new NumberFormatter("de_DE@currency=USD", NumberFormatter::CURRENCY))->format(1234.5), (new NumberFormatter("tlh", NumberFormatter::DECIMAL))->getLocale(Locale::VALID_LOCALE), (new NumberFormatter("en_XA", NumberFormatter::CURRENCY))->format(5));
$m = clone $c; var_dump($m->format(3), $m->getTextAttribute(NumberFormatter::CURRENCY_CODE));
