<?php
// IntlTimeZone and IntlCalendar: the metadata ICU carries, the offsets, the display names, the fields.
date_default_timezone_set("Europe/Vienna");

$ts = 1700000000;
foreach (["America/New_York", "Europe/Berlin", "UTC", "GMT", "GMT+5:30", "CET", "US/Pacific", "Asia/Kolkata", "Etc/GMT+3", "Australia/Lord_Howe", "Nope/Zone", "utc", "Z", "Asia/Calcutta", "PST", "PST8PDT", "Etc/UTC", "Etc/Unknown", ""] as $id) {
    $z = IntlTimeZone::createTimeZone($id);
    echo json_encode($id), ": id=", json_encode($z->getID()), " raw=", $z->getRawOffset(), " dst=", var_export($z->useDaylightTime(), true), " sav=", $z->getDSTSavings(), " canon=", json_encode(IntlTimeZone::getCanonicalID($id, $sys)), "/", var_export($sys, true), " region=", json_encode(IntlTimeZone::getRegion($id)), " iana=", json_encode(IntlTimeZone::getIanaID($id)), " win=", json_encode(IntlTimeZone::getWindowsID($id)), " err=", intl_get_error_code(), " names=", $z->getDisplayName(false, IntlTimeZone::DISPLAY_SHORT), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_LONG), "|", $z->getDisplayName($z->useDaylightTime(), IntlTimeZone::DISPLAY_SHORT), "|", $z->getDisplayName($z->useDaylightTime(), IntlTimeZone::DISPLAY_LONG), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_SHORT_GENERIC), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_LONG_GENERIC), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_SHORT_GMT), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_LONG_GMT), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_SHORT_COMMONLY_USED), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_GENERIC_LOCATION), "|", $z->getDisplayName(false, IntlTimeZone::DISPLAY_LONG, "de"), " eq=", IntlTimeZone::countEquivalentIDs($id), "/", json_encode(IntlTimeZone::getEquivalentID($id, 0)), " dtz=", json_encode(@(function($z) { try { return $z->toDateTimeZone()->getName(); } catch (Throwable $e) { return get_class($e); } })($z)), "\n";
    $z->getOffset($ts * 1000, false, $raw, $dst); echo "   offset(utc)=$raw/$dst "; $z->getOffset($ts * 1000, true, $raw, $dst); echo "offset(local)=$raw/$dst\n";
}
var_dump(IntlTimeZone::createDefault()->getID(), IntlTimeZone::getGMT()->getID(), IntlTimeZone::getUnknown()->getID(), IntlTimeZone::getTZDataVersion(), IntlTimeZone::fromDateTimeZone(new DateTimeZone("+02:00"))->getID(), IntlTimeZone::fromDateTimeZone(new DateTimeZone("EST"))->getID(), IntlTimeZone::fromDateTimeZone(new DateTimeZone("Europe/Berlin"))->getID(), IntlTimeZone::getIDForWindowsID("Eastern Standard Time"), IntlTimeZone::getIDForWindowsID("Eastern Standard Time", "CA"), IntlTimeZone::getIDForWindowsID("Nope"), IntlTimeZone::createTimeZone("America/New_York")->hasSameRules(IntlTimeZone::createTimeZone("US/Eastern")), IntlTimeZone::createTimeZone("America/New_York")->hasSameRules(IntlTimeZone::createTimeZone("Europe/Berlin")), count(iterator_to_array(IntlTimeZone::createEnumeration())), count(iterator_to_array(IntlTimeZone::createEnumeration("US"))), count(iterator_to_array(IntlTimeZone::createEnumeration(-18000000))), iterator_to_array(IntlTimeZone::createEnumeration("DE")), count(iterator_to_array(IntlTimeZone::createTimeZoneIDEnumeration(IntlTimeZone::TYPE_CANONICAL))), iterator_to_array(IntlTimeZone::createTimeZoneIDEnumeration(IntlTimeZone::TYPE_ANY, "DE")), iterator_to_array(IntlTimeZone::createTimeZoneIDEnumeration(IntlTimeZone::TYPE_CANONICAL_LOCATION, null, 3600000)));
$z = IntlTimeZone::createTimeZone("Europe/Berlin"); var_dump($z->getErrorCode(), $z->getErrorMessage(), (string) get_class($z));
try { new IntlTimeZone(); } catch (Throwable $e) { echo get_class($e), ": ", $e->getMessage(), "\n"; }
var_dump(IntlTimeZone::createTimeZone("Europe/Berlin") == IntlTimeZone::createTimeZone("Europe/Berlin"));


$c = IntlCalendar::createInstance("Europe/Berlin", "de_DE");
var_dump(get_class($c), $c->getType(), $c->getTimeZone()->getID(), $c->getLocale(Locale::VALID_LOCALE), $c->getLocale(Locale::ACTUAL_LOCALE), $c->getFirstDayOfWeek(), $c->getMinimalDaysInFirstWeek(), $c->isLenient(), $c->getErrorCode(), $c->getErrorMessage(), $c->getRepeatedWallTimeOption(), $c->getSkippedWallTimeOption());
$c->setTime(1700000000000);
var_dump($c->getTime(), $c->get(IntlCalendar::FIELD_YEAR), $c->get(IntlCalendar::FIELD_MONTH), $c->get(IntlCalendar::FIELD_DAY_OF_MONTH), $c->get(IntlCalendar::FIELD_HOUR_OF_DAY), $c->get(IntlCalendar::FIELD_MINUTE), $c->get(IntlCalendar::FIELD_SECOND), $c->get(IntlCalendar::FIELD_MILLISECOND), $c->get(IntlCalendar::FIELD_DAY_OF_WEEK), $c->get(IntlCalendar::FIELD_DAY_OF_YEAR), $c->get(IntlCalendar::FIELD_WEEK_OF_YEAR), $c->get(IntlCalendar::FIELD_WEEK_OF_MONTH), $c->get(IntlCalendar::FIELD_ERA), $c->get(IntlCalendar::FIELD_AM_PM), $c->get(IntlCalendar::FIELD_HOUR), $c->get(IntlCalendar::FIELD_ZONE_OFFSET), $c->get(IntlCalendar::FIELD_DST_OFFSET), $c->get(IntlCalendar::FIELD_EXTENDED_YEAR), $c->get(IntlCalendar::FIELD_JULIAN_DAY), $c->get(IntlCalendar::FIELD_MILLISECONDS_IN_DAY), $c->get(IntlCalendar::FIELD_IS_LEAP_MONTH), $c->get(IntlCalendar::FIELD_DAY_OF_WEEK_IN_MONTH), $c->get(IntlCalendar::FIELD_YEAR_WOY), $c->get(IntlCalendar::FIELD_DOW_LOCAL));
var_dump($c->inDaylightTime(), $c->toDateTime()->format("c"), IntlCalendar::fromDateTime("2024-03-10 14:30:00 Asia/Tokyo")->getTime(), IntlCalendar::fromDateTime(new DateTime("2024-03-10 14:30:00 Asia/Tokyo"))->getTimeZone()->getID());
$c2 = IntlCalendar::createInstance("UTC", "en_US"); $c2->setTime(1700000000000);
var_dump($c->equals($c2), $c->after($c2), $c->before($c2), $c->fieldDifference(1800000000000, IntlCalendar::FIELD_DAY_OF_MONTH), $c->getTime());
$c2->set(2024, 2, 10); var_dump($c2->getTime(), $c2->toDateTime()->format("c"));
$c2->set(2024, 2, 10, 14, 30, 5); var_dump($c2->toDateTime()->format("c"));
$c2->set(IntlCalendar::FIELD_YEAR, 2030); var_dump($c2->toDateTime()->format("c"));
$c2->add(IntlCalendar::FIELD_MONTH, 5); var_dump($c2->toDateTime()->format("c"));
$c2->roll(IntlCalendar::FIELD_MONTH, 10); var_dump($c2->toDateTime()->format("c"));
var_dump($c2->getActualMaximum(IntlCalendar::FIELD_DAY_OF_MONTH), $c2->getActualMinimum(IntlCalendar::FIELD_DAY_OF_MONTH), $c2->getMaximum(IntlCalendar::FIELD_DAY_OF_MONTH), $c2->getMinimum(IntlCalendar::FIELD_DAY_OF_MONTH), $c2->getLeastMaximum(IntlCalendar::FIELD_DAY_OF_MONTH), $c2->getGreatestMinimum(IntlCalendar::FIELD_DAY_OF_MONTH), $c2->getDayOfWeekType(1), $c2->getDayOfWeekType(7), $c2->getWeekendTransition(1), $c2->isWeekend(), $c2->isSet(IntlCalendar::FIELD_YEAR), $c2->getKeywordValuesForLocale("calendar", "de_DE", true) ? iterator_to_array($c2->getKeywordValuesForLocale("calendar", "de_DE", true)) : null);
var_dump(count(IntlCalendar::getAvailableLocales()), IntlGregorianCalendar::class, get_class(new IntlGregorianCalendar("UTC", "en")), (new IntlGregorianCalendar(2024, 2, 10))->toDateTime()->format("c"), (new IntlGregorianCalendar(2024, 2, 10, 14, 30, 5))->toDateTime()->format("c"), (new IntlGregorianCalendar("Asia/Tokyo"))->getTimeZone()->getID(), (new IntlGregorianCalendar())->getGregorianChange(), (new IntlGregorianCalendar())->isLeapYear(2024));
