[package]
name = "rphp-ext-posix"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rphp-runtime.workspace = true
rphp-value.workspace = true
rphp-stdlib.workspace = true
rustix.workspace = true
nix = { version = "=0.31.3", features = ["signal", "process", "user", "fs", "resource", "term", "feature"] }
libc = "=0.2.186"
