//! PHP token ids and names.
//!
//! GENERATED by `cargo xtask token-ids` from PHP 8.5.0 (`get_defined_constants(true)['tokenizer']`
//! and `token_name()` for ids 256..=450). Do not edit by hand: re-run the xtask after a PHP
//! upgrade; `tests/ids_generated.rs` re-derives this table from the installed `php` and fails
//! if it drifted. Ids below 256 are the byte values of single-character tokens.

/// `T_LNUMBER` (260).
pub const T_LNUMBER: u16 = 260;
/// `T_DNUMBER` (261).
pub const T_DNUMBER: u16 = 261;
/// `T_STRING` (262).
pub const T_STRING: u16 = 262;
/// `T_NAME_FULLY_QUALIFIED` (263).
pub const T_NAME_FULLY_QUALIFIED: u16 = 263;
/// `T_NAME_RELATIVE` (264).
pub const T_NAME_RELATIVE: u16 = 264;
/// `T_NAME_QUALIFIED` (265).
pub const T_NAME_QUALIFIED: u16 = 265;
/// `T_VARIABLE` (266).
pub const T_VARIABLE: u16 = 266;
/// `T_INLINE_HTML` (267).
pub const T_INLINE_HTML: u16 = 267;
/// `T_ENCAPSED_AND_WHITESPACE` (268).
pub const T_ENCAPSED_AND_WHITESPACE: u16 = 268;
/// `T_CONSTANT_ENCAPSED_STRING` (269).
pub const T_CONSTANT_ENCAPSED_STRING: u16 = 269;
/// `T_STRING_VARNAME` (270).
pub const T_STRING_VARNAME: u16 = 270;
/// `T_NUM_STRING` (271).
pub const T_NUM_STRING: u16 = 271;
/// `T_INCLUDE` (272).
pub const T_INCLUDE: u16 = 272;
/// `T_INCLUDE_ONCE` (273).
pub const T_INCLUDE_ONCE: u16 = 273;
/// `T_EVAL` (274).
pub const T_EVAL: u16 = 274;
/// `T_REQUIRE` (275).
pub const T_REQUIRE: u16 = 275;
/// `T_REQUIRE_ONCE` (276).
pub const T_REQUIRE_ONCE: u16 = 276;
/// `T_LOGICAL_OR` (277).
pub const T_LOGICAL_OR: u16 = 277;
/// `T_LOGICAL_XOR` (278).
pub const T_LOGICAL_XOR: u16 = 278;
/// `T_LOGICAL_AND` (279).
pub const T_LOGICAL_AND: u16 = 279;
/// `T_PRINT` (280).
pub const T_PRINT: u16 = 280;
/// `T_YIELD` (281).
pub const T_YIELD: u16 = 281;
/// `T_YIELD_FROM` (282).
pub const T_YIELD_FROM: u16 = 282;
/// `T_INSTANCEOF` (283).
pub const T_INSTANCEOF: u16 = 283;
/// `T_NEW` (284).
pub const T_NEW: u16 = 284;
/// `T_CLONE` (285).
pub const T_CLONE: u16 = 285;
/// `T_EXIT` (286).
pub const T_EXIT: u16 = 286;
/// `T_IF` (287).
pub const T_IF: u16 = 287;
/// `T_ELSEIF` (288).
pub const T_ELSEIF: u16 = 288;
/// `T_ELSE` (289).
pub const T_ELSE: u16 = 289;
/// `T_ENDIF` (290).
pub const T_ENDIF: u16 = 290;
/// `T_ECHO` (291).
pub const T_ECHO: u16 = 291;
/// `T_DO` (292).
pub const T_DO: u16 = 292;
/// `T_WHILE` (293).
pub const T_WHILE: u16 = 293;
/// `T_ENDWHILE` (294).
pub const T_ENDWHILE: u16 = 294;
/// `T_FOR` (295).
pub const T_FOR: u16 = 295;
/// `T_ENDFOR` (296).
pub const T_ENDFOR: u16 = 296;
/// `T_FOREACH` (297).
pub const T_FOREACH: u16 = 297;
/// `T_ENDFOREACH` (298).
pub const T_ENDFOREACH: u16 = 298;
/// `T_DECLARE` (299).
pub const T_DECLARE: u16 = 299;
/// `T_ENDDECLARE` (300).
pub const T_ENDDECLARE: u16 = 300;
/// `T_AS` (301).
pub const T_AS: u16 = 301;
/// `T_SWITCH` (302).
pub const T_SWITCH: u16 = 302;
/// `T_ENDSWITCH` (303).
pub const T_ENDSWITCH: u16 = 303;
/// `T_CASE` (304).
pub const T_CASE: u16 = 304;
/// `T_DEFAULT` (305).
pub const T_DEFAULT: u16 = 305;
/// `T_MATCH` (306).
pub const T_MATCH: u16 = 306;
/// `T_BREAK` (307).
pub const T_BREAK: u16 = 307;
/// `T_CONTINUE` (308).
pub const T_CONTINUE: u16 = 308;
/// `T_GOTO` (309).
pub const T_GOTO: u16 = 309;
/// `T_FUNCTION` (310).
pub const T_FUNCTION: u16 = 310;
/// `T_FN` (311).
pub const T_FN: u16 = 311;
/// `T_CONST` (312).
pub const T_CONST: u16 = 312;
/// `T_RETURN` (313).
pub const T_RETURN: u16 = 313;
/// `T_TRY` (314).
pub const T_TRY: u16 = 314;
/// `T_CATCH` (315).
pub const T_CATCH: u16 = 315;
/// `T_FINALLY` (316).
pub const T_FINALLY: u16 = 316;
/// `T_THROW` (317).
pub const T_THROW: u16 = 317;
/// `T_USE` (318).
pub const T_USE: u16 = 318;
/// `T_INSTEADOF` (319).
pub const T_INSTEADOF: u16 = 319;
/// `T_GLOBAL` (320).
pub const T_GLOBAL: u16 = 320;
/// `T_STATIC` (321).
pub const T_STATIC: u16 = 321;
/// `T_ABSTRACT` (322).
pub const T_ABSTRACT: u16 = 322;
/// `T_FINAL` (323).
pub const T_FINAL: u16 = 323;
/// `T_PRIVATE` (324).
pub const T_PRIVATE: u16 = 324;
/// `T_PROTECTED` (325).
pub const T_PROTECTED: u16 = 325;
/// `T_PUBLIC` (326).
pub const T_PUBLIC: u16 = 326;
/// `T_PRIVATE_SET` (327).
pub const T_PRIVATE_SET: u16 = 327;
/// `T_PROTECTED_SET` (328).
pub const T_PROTECTED_SET: u16 = 328;
/// `T_PUBLIC_SET` (329).
pub const T_PUBLIC_SET: u16 = 329;
/// `T_READONLY` (330).
pub const T_READONLY: u16 = 330;
/// `T_VAR` (331).
pub const T_VAR: u16 = 331;
/// `T_UNSET` (332).
pub const T_UNSET: u16 = 332;
/// `T_ISSET` (333).
pub const T_ISSET: u16 = 333;
/// `T_EMPTY` (334).
pub const T_EMPTY: u16 = 334;
/// `T_HALT_COMPILER` (335).
pub const T_HALT_COMPILER: u16 = 335;
/// `T_CLASS` (336).
pub const T_CLASS: u16 = 336;
/// `T_TRAIT` (337).
pub const T_TRAIT: u16 = 337;
/// `T_INTERFACE` (338).
pub const T_INTERFACE: u16 = 338;
/// `T_ENUM` (339).
pub const T_ENUM: u16 = 339;
/// `T_EXTENDS` (340).
pub const T_EXTENDS: u16 = 340;
/// `T_IMPLEMENTS` (341).
pub const T_IMPLEMENTS: u16 = 341;
/// `T_NAMESPACE` (342).
pub const T_NAMESPACE: u16 = 342;
/// `T_LIST` (343).
pub const T_LIST: u16 = 343;
/// `T_ARRAY` (344).
pub const T_ARRAY: u16 = 344;
/// `T_CALLABLE` (345).
pub const T_CALLABLE: u16 = 345;
/// `T_LINE` (346).
pub const T_LINE: u16 = 346;
/// `T_FILE` (347).
pub const T_FILE: u16 = 347;
/// `T_DIR` (348).
pub const T_DIR: u16 = 348;
/// `T_CLASS_C` (349).
pub const T_CLASS_C: u16 = 349;
/// `T_TRAIT_C` (350).
pub const T_TRAIT_C: u16 = 350;
/// `T_METHOD_C` (351).
pub const T_METHOD_C: u16 = 351;
/// `T_FUNC_C` (352).
pub const T_FUNC_C: u16 = 352;
/// `T_PROPERTY_C` (353).
pub const T_PROPERTY_C: u16 = 353;
/// `T_NS_C` (354).
pub const T_NS_C: u16 = 354;
/// `T_ATTRIBUTE` (355).
pub const T_ATTRIBUTE: u16 = 355;
/// `T_PLUS_EQUAL` (356).
pub const T_PLUS_EQUAL: u16 = 356;
/// `T_MINUS_EQUAL` (357).
pub const T_MINUS_EQUAL: u16 = 357;
/// `T_MUL_EQUAL` (358).
pub const T_MUL_EQUAL: u16 = 358;
/// `T_DIV_EQUAL` (359).
pub const T_DIV_EQUAL: u16 = 359;
/// `T_CONCAT_EQUAL` (360).
pub const T_CONCAT_EQUAL: u16 = 360;
/// `T_MOD_EQUAL` (361).
pub const T_MOD_EQUAL: u16 = 361;
/// `T_AND_EQUAL` (362).
pub const T_AND_EQUAL: u16 = 362;
/// `T_OR_EQUAL` (363).
pub const T_OR_EQUAL: u16 = 363;
/// `T_XOR_EQUAL` (364).
pub const T_XOR_EQUAL: u16 = 364;
/// `T_SL_EQUAL` (365).
pub const T_SL_EQUAL: u16 = 365;
/// `T_SR_EQUAL` (366).
pub const T_SR_EQUAL: u16 = 366;
/// `T_COALESCE_EQUAL` (367).
pub const T_COALESCE_EQUAL: u16 = 367;
/// `T_BOOLEAN_OR` (368).
pub const T_BOOLEAN_OR: u16 = 368;
/// `T_BOOLEAN_AND` (369).
pub const T_BOOLEAN_AND: u16 = 369;
/// `T_IS_EQUAL` (370).
pub const T_IS_EQUAL: u16 = 370;
/// `T_IS_NOT_EQUAL` (371).
pub const T_IS_NOT_EQUAL: u16 = 371;
/// `T_IS_IDENTICAL` (372).
pub const T_IS_IDENTICAL: u16 = 372;
/// `T_IS_NOT_IDENTICAL` (373).
pub const T_IS_NOT_IDENTICAL: u16 = 373;
/// `T_IS_SMALLER_OR_EQUAL` (374).
pub const T_IS_SMALLER_OR_EQUAL: u16 = 374;
/// `T_IS_GREATER_OR_EQUAL` (375).
pub const T_IS_GREATER_OR_EQUAL: u16 = 375;
/// `T_SPACESHIP` (376).
pub const T_SPACESHIP: u16 = 376;
/// `T_SL` (377).
pub const T_SL: u16 = 377;
/// `T_SR` (378).
pub const T_SR: u16 = 378;
/// `T_INC` (379).
pub const T_INC: u16 = 379;
/// `T_DEC` (380).
pub const T_DEC: u16 = 380;
/// `T_INT_CAST` (381).
pub const T_INT_CAST: u16 = 381;
/// `T_DOUBLE_CAST` (382).
pub const T_DOUBLE_CAST: u16 = 382;
/// `T_STRING_CAST` (383).
pub const T_STRING_CAST: u16 = 383;
/// `T_ARRAY_CAST` (384).
pub const T_ARRAY_CAST: u16 = 384;
/// `T_OBJECT_CAST` (385).
pub const T_OBJECT_CAST: u16 = 385;
/// `T_BOOL_CAST` (386).
pub const T_BOOL_CAST: u16 = 386;
/// `T_UNSET_CAST` (387).
pub const T_UNSET_CAST: u16 = 387;
/// `T_VOID_CAST` (388).
pub const T_VOID_CAST: u16 = 388;
/// `T_OBJECT_OPERATOR` (389).
pub const T_OBJECT_OPERATOR: u16 = 389;
/// `T_NULLSAFE_OBJECT_OPERATOR` (390).
pub const T_NULLSAFE_OBJECT_OPERATOR: u16 = 390;
/// `T_DOUBLE_ARROW` (391).
pub const T_DOUBLE_ARROW: u16 = 391;
/// `T_COMMENT` (392).
pub const T_COMMENT: u16 = 392;
/// `T_DOC_COMMENT` (393).
pub const T_DOC_COMMENT: u16 = 393;
/// `T_OPEN_TAG` (394).
pub const T_OPEN_TAG: u16 = 394;
/// `T_OPEN_TAG_WITH_ECHO` (395).
pub const T_OPEN_TAG_WITH_ECHO: u16 = 395;
/// `T_CLOSE_TAG` (396).
pub const T_CLOSE_TAG: u16 = 396;
/// `T_WHITESPACE` (397).
pub const T_WHITESPACE: u16 = 397;
/// `T_START_HEREDOC` (398).
pub const T_START_HEREDOC: u16 = 398;
/// `T_END_HEREDOC` (399).
pub const T_END_HEREDOC: u16 = 399;
/// `T_DOLLAR_OPEN_CURLY_BRACES` (400).
pub const T_DOLLAR_OPEN_CURLY_BRACES: u16 = 400;
/// `T_CURLY_OPEN` (401).
pub const T_CURLY_OPEN: u16 = 401;
/// `T_DOUBLE_COLON` (402).
pub const T_DOUBLE_COLON: u16 = 402;
/// `T_PAAMAYIM_NEKUDOTAYIM` (402).
pub const T_PAAMAYIM_NEKUDOTAYIM: u16 = 402;
/// `T_NS_SEPARATOR` (403).
pub const T_NS_SEPARATOR: u16 = 403;
/// `T_ELLIPSIS` (404).
pub const T_ELLIPSIS: u16 = 404;
/// `T_COALESCE` (405).
pub const T_COALESCE: u16 = 405;
/// `T_POW` (406).
pub const T_POW: u16 = 406;
/// `T_POW_EQUAL` (407).
pub const T_POW_EQUAL: u16 = 407;
/// `T_PIPE` (408).
pub const T_PIPE: u16 = 408;
/// `T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG` (409).
pub const T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG: u16 = 409;
/// `T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG` (410).
pub const T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG: u16 = 410;
/// `T_BAD_CHARACTER` (411).
pub const T_BAD_CHARACTER: u16 = 411;

/// Every `T_*` constant exported by ext/tokenizer as `(name, id)`, sorted by id then name.
/// Aliases share an id (`T_DOUBLE_COLON` / `T_PAAMAYIM_NEKUDOTAYIM`).
pub const ALL: &[(&str, u16)] = &[
    ("T_LNUMBER", 260),
    ("T_DNUMBER", 261),
    ("T_STRING", 262),
    ("T_NAME_FULLY_QUALIFIED", 263),
    ("T_NAME_RELATIVE", 264),
    ("T_NAME_QUALIFIED", 265),
    ("T_VARIABLE", 266),
    ("T_INLINE_HTML", 267),
    ("T_ENCAPSED_AND_WHITESPACE", 268),
    ("T_CONSTANT_ENCAPSED_STRING", 269),
    ("T_STRING_VARNAME", 270),
    ("T_NUM_STRING", 271),
    ("T_INCLUDE", 272),
    ("T_INCLUDE_ONCE", 273),
    ("T_EVAL", 274),
    ("T_REQUIRE", 275),
    ("T_REQUIRE_ONCE", 276),
    ("T_LOGICAL_OR", 277),
    ("T_LOGICAL_XOR", 278),
    ("T_LOGICAL_AND", 279),
    ("T_PRINT", 280),
    ("T_YIELD", 281),
    ("T_YIELD_FROM", 282),
    ("T_INSTANCEOF", 283),
    ("T_NEW", 284),
    ("T_CLONE", 285),
    ("T_EXIT", 286),
    ("T_IF", 287),
    ("T_ELSEIF", 288),
    ("T_ELSE", 289),
    ("T_ENDIF", 290),
    ("T_ECHO", 291),
    ("T_DO", 292),
    ("T_WHILE", 293),
    ("T_ENDWHILE", 294),
    ("T_FOR", 295),
    ("T_ENDFOR", 296),
    ("T_FOREACH", 297),
    ("T_ENDFOREACH", 298),
    ("T_DECLARE", 299),
    ("T_ENDDECLARE", 300),
    ("T_AS", 301),
    ("T_SWITCH", 302),
    ("T_ENDSWITCH", 303),
    ("T_CASE", 304),
    ("T_DEFAULT", 305),
    ("T_MATCH", 306),
    ("T_BREAK", 307),
    ("T_CONTINUE", 308),
    ("T_GOTO", 309),
    ("T_FUNCTION", 310),
    ("T_FN", 311),
    ("T_CONST", 312),
    ("T_RETURN", 313),
    ("T_TRY", 314),
    ("T_CATCH", 315),
    ("T_FINALLY", 316),
    ("T_THROW", 317),
    ("T_USE", 318),
    ("T_INSTEADOF", 319),
    ("T_GLOBAL", 320),
    ("T_STATIC", 321),
    ("T_ABSTRACT", 322),
    ("T_FINAL", 323),
    ("T_PRIVATE", 324),
    ("T_PROTECTED", 325),
    ("T_PUBLIC", 326),
    ("T_PRIVATE_SET", 327),
    ("T_PROTECTED_SET", 328),
    ("T_PUBLIC_SET", 329),
    ("T_READONLY", 330),
    ("T_VAR", 331),
    ("T_UNSET", 332),
    ("T_ISSET", 333),
    ("T_EMPTY", 334),
    ("T_HALT_COMPILER", 335),
    ("T_CLASS", 336),
    ("T_TRAIT", 337),
    ("T_INTERFACE", 338),
    ("T_ENUM", 339),
    ("T_EXTENDS", 340),
    ("T_IMPLEMENTS", 341),
    ("T_NAMESPACE", 342),
    ("T_LIST", 343),
    ("T_ARRAY", 344),
    ("T_CALLABLE", 345),
    ("T_LINE", 346),
    ("T_FILE", 347),
    ("T_DIR", 348),
    ("T_CLASS_C", 349),
    ("T_TRAIT_C", 350),
    ("T_METHOD_C", 351),
    ("T_FUNC_C", 352),
    ("T_PROPERTY_C", 353),
    ("T_NS_C", 354),
    ("T_ATTRIBUTE", 355),
    ("T_PLUS_EQUAL", 356),
    ("T_MINUS_EQUAL", 357),
    ("T_MUL_EQUAL", 358),
    ("T_DIV_EQUAL", 359),
    ("T_CONCAT_EQUAL", 360),
    ("T_MOD_EQUAL", 361),
    ("T_AND_EQUAL", 362),
    ("T_OR_EQUAL", 363),
    ("T_XOR_EQUAL", 364),
    ("T_SL_EQUAL", 365),
    ("T_SR_EQUAL", 366),
    ("T_COALESCE_EQUAL", 367),
    ("T_BOOLEAN_OR", 368),
    ("T_BOOLEAN_AND", 369),
    ("T_IS_EQUAL", 370),
    ("T_IS_NOT_EQUAL", 371),
    ("T_IS_IDENTICAL", 372),
    ("T_IS_NOT_IDENTICAL", 373),
    ("T_IS_SMALLER_OR_EQUAL", 374),
    ("T_IS_GREATER_OR_EQUAL", 375),
    ("T_SPACESHIP", 376),
    ("T_SL", 377),
    ("T_SR", 378),
    ("T_INC", 379),
    ("T_DEC", 380),
    ("T_INT_CAST", 381),
    ("T_DOUBLE_CAST", 382),
    ("T_STRING_CAST", 383),
    ("T_ARRAY_CAST", 384),
    ("T_OBJECT_CAST", 385),
    ("T_BOOL_CAST", 386),
    ("T_UNSET_CAST", 387),
    ("T_VOID_CAST", 388),
    ("T_OBJECT_OPERATOR", 389),
    ("T_NULLSAFE_OBJECT_OPERATOR", 390),
    ("T_DOUBLE_ARROW", 391),
    ("T_COMMENT", 392),
    ("T_DOC_COMMENT", 393),
    ("T_OPEN_TAG", 394),
    ("T_OPEN_TAG_WITH_ECHO", 395),
    ("T_CLOSE_TAG", 396),
    ("T_WHITESPACE", 397),
    ("T_START_HEREDOC", 398),
    ("T_END_HEREDOC", 399),
    ("T_DOLLAR_OPEN_CURLY_BRACES", 400),
    ("T_CURLY_OPEN", 401),
    ("T_DOUBLE_COLON", 402),
    ("T_PAAMAYIM_NEKUDOTAYIM", 402),
    ("T_NS_SEPARATOR", 403),
    ("T_ELLIPSIS", 404),
    ("T_COALESCE", 405),
    ("T_POW", 406),
    ("T_POW_EQUAL", 407),
    ("T_PIPE", 408),
    ("T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG", 409),
    ("T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG", 410),
    ("T_BAD_CHARACTER", 411),
];

/// Smallest id in [`ALL`].
pub const MIN_ID: u16 = 260;

/// Largest id in [`ALL`].
pub const MAX_ID: u16 = 411;

/// The canonical name PHP's `token_name()` reports for `id`, or `None` where PHP reports
/// `UNKNOWN` (single-character tokens and unassigned ids).
pub const fn name_of(id: u16) -> Option<&'static str> {
    match id {
        260 => Some("T_LNUMBER"),
        261 => Some("T_DNUMBER"),
        262 => Some("T_STRING"),
        263 => Some("T_NAME_FULLY_QUALIFIED"),
        264 => Some("T_NAME_RELATIVE"),
        265 => Some("T_NAME_QUALIFIED"),
        266 => Some("T_VARIABLE"),
        267 => Some("T_INLINE_HTML"),
        268 => Some("T_ENCAPSED_AND_WHITESPACE"),
        269 => Some("T_CONSTANT_ENCAPSED_STRING"),
        270 => Some("T_STRING_VARNAME"),
        271 => Some("T_NUM_STRING"),
        272 => Some("T_INCLUDE"),
        273 => Some("T_INCLUDE_ONCE"),
        274 => Some("T_EVAL"),
        275 => Some("T_REQUIRE"),
        276 => Some("T_REQUIRE_ONCE"),
        277 => Some("T_LOGICAL_OR"),
        278 => Some("T_LOGICAL_XOR"),
        279 => Some("T_LOGICAL_AND"),
        280 => Some("T_PRINT"),
        281 => Some("T_YIELD"),
        282 => Some("T_YIELD_FROM"),
        283 => Some("T_INSTANCEOF"),
        284 => Some("T_NEW"),
        285 => Some("T_CLONE"),
        286 => Some("T_EXIT"),
        287 => Some("T_IF"),
        288 => Some("T_ELSEIF"),
        289 => Some("T_ELSE"),
        290 => Some("T_ENDIF"),
        291 => Some("T_ECHO"),
        292 => Some("T_DO"),
        293 => Some("T_WHILE"),
        294 => Some("T_ENDWHILE"),
        295 => Some("T_FOR"),
        296 => Some("T_ENDFOR"),
        297 => Some("T_FOREACH"),
        298 => Some("T_ENDFOREACH"),
        299 => Some("T_DECLARE"),
        300 => Some("T_ENDDECLARE"),
        301 => Some("T_AS"),
        302 => Some("T_SWITCH"),
        303 => Some("T_ENDSWITCH"),
        304 => Some("T_CASE"),
        305 => Some("T_DEFAULT"),
        306 => Some("T_MATCH"),
        307 => Some("T_BREAK"),
        308 => Some("T_CONTINUE"),
        309 => Some("T_GOTO"),
        310 => Some("T_FUNCTION"),
        311 => Some("T_FN"),
        312 => Some("T_CONST"),
        313 => Some("T_RETURN"),
        314 => Some("T_TRY"),
        315 => Some("T_CATCH"),
        316 => Some("T_FINALLY"),
        317 => Some("T_THROW"),
        318 => Some("T_USE"),
        319 => Some("T_INSTEADOF"),
        320 => Some("T_GLOBAL"),
        321 => Some("T_STATIC"),
        322 => Some("T_ABSTRACT"),
        323 => Some("T_FINAL"),
        324 => Some("T_PRIVATE"),
        325 => Some("T_PROTECTED"),
        326 => Some("T_PUBLIC"),
        327 => Some("T_PRIVATE_SET"),
        328 => Some("T_PROTECTED_SET"),
        329 => Some("T_PUBLIC_SET"),
        330 => Some("T_READONLY"),
        331 => Some("T_VAR"),
        332 => Some("T_UNSET"),
        333 => Some("T_ISSET"),
        334 => Some("T_EMPTY"),
        335 => Some("T_HALT_COMPILER"),
        336 => Some("T_CLASS"),
        337 => Some("T_TRAIT"),
        338 => Some("T_INTERFACE"),
        339 => Some("T_ENUM"),
        340 => Some("T_EXTENDS"),
        341 => Some("T_IMPLEMENTS"),
        342 => Some("T_NAMESPACE"),
        343 => Some("T_LIST"),
        344 => Some("T_ARRAY"),
        345 => Some("T_CALLABLE"),
        346 => Some("T_LINE"),
        347 => Some("T_FILE"),
        348 => Some("T_DIR"),
        349 => Some("T_CLASS_C"),
        350 => Some("T_TRAIT_C"),
        351 => Some("T_METHOD_C"),
        352 => Some("T_FUNC_C"),
        353 => Some("T_PROPERTY_C"),
        354 => Some("T_NS_C"),
        355 => Some("T_ATTRIBUTE"),
        356 => Some("T_PLUS_EQUAL"),
        357 => Some("T_MINUS_EQUAL"),
        358 => Some("T_MUL_EQUAL"),
        359 => Some("T_DIV_EQUAL"),
        360 => Some("T_CONCAT_EQUAL"),
        361 => Some("T_MOD_EQUAL"),
        362 => Some("T_AND_EQUAL"),
        363 => Some("T_OR_EQUAL"),
        364 => Some("T_XOR_EQUAL"),
        365 => Some("T_SL_EQUAL"),
        366 => Some("T_SR_EQUAL"),
        367 => Some("T_COALESCE_EQUAL"),
        368 => Some("T_BOOLEAN_OR"),
        369 => Some("T_BOOLEAN_AND"),
        370 => Some("T_IS_EQUAL"),
        371 => Some("T_IS_NOT_EQUAL"),
        372 => Some("T_IS_IDENTICAL"),
        373 => Some("T_IS_NOT_IDENTICAL"),
        374 => Some("T_IS_SMALLER_OR_EQUAL"),
        375 => Some("T_IS_GREATER_OR_EQUAL"),
        376 => Some("T_SPACESHIP"),
        377 => Some("T_SL"),
        378 => Some("T_SR"),
        379 => Some("T_INC"),
        380 => Some("T_DEC"),
        381 => Some("T_INT_CAST"),
        382 => Some("T_DOUBLE_CAST"),
        383 => Some("T_STRING_CAST"),
        384 => Some("T_ARRAY_CAST"),
        385 => Some("T_OBJECT_CAST"),
        386 => Some("T_BOOL_CAST"),
        387 => Some("T_UNSET_CAST"),
        388 => Some("T_VOID_CAST"),
        389 => Some("T_OBJECT_OPERATOR"),
        390 => Some("T_NULLSAFE_OBJECT_OPERATOR"),
        391 => Some("T_DOUBLE_ARROW"),
        392 => Some("T_COMMENT"),
        393 => Some("T_DOC_COMMENT"),
        394 => Some("T_OPEN_TAG"),
        395 => Some("T_OPEN_TAG_WITH_ECHO"),
        396 => Some("T_CLOSE_TAG"),
        397 => Some("T_WHITESPACE"),
        398 => Some("T_START_HEREDOC"),
        399 => Some("T_END_HEREDOC"),
        400 => Some("T_DOLLAR_OPEN_CURLY_BRACES"),
        401 => Some("T_CURLY_OPEN"),
        402 => Some("T_DOUBLE_COLON"),
        403 => Some("T_NS_SEPARATOR"),
        404 => Some("T_ELLIPSIS"),
        405 => Some("T_COALESCE"),
        406 => Some("T_POW"),
        407 => Some("T_POW_EQUAL"),
        408 => Some("T_PIPE"),
        409 => Some("T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG"),
        410 => Some("T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG"),
        411 => Some("T_BAD_CHARACTER"),
        _ => None,
    }
}
