//! `cargo xtask string-params`: the table of native parameters php declares
//! as `string`, generated from the manifest.
//!
//! php's argument parser calls `__toString()` when an object reaches a
//! parameter typed exactly `string` (`?string` included) — `sprintf('%s',
//! $alias)`, `strlen($stringable)` — and leaves the object alone for
//! `mixed`, `array|string`, `object` and every other type. The engine's
//! native-call boundary needs to know which positions those are, per
//! function and per method, and this table is that knowledge:
//! `crates/rphp-runtime/src/string_params.rs`, one `(name, mask)` row per
//! native with at least one such parameter, bit *i* for parameter *i*, and
//! the top byte the index plus one of a variadic `string ...$rest`.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::XtaskResult;

#[derive(serde::Deserialize)]
struct Param {
    name: String,
    #[serde(rename = "type")]
    ty: Option<String>,
    #[serde(default)]
    nullable: bool,
    #[serde(default)]
    variadic: bool,
}

#[derive(serde::Deserialize)]
struct Sig {
    params: Vec<Param>,
}

#[derive(serde::Deserialize)]
struct Method {
    name: String,
    params: Vec<Param>,
}

#[derive(serde::Deserialize)]
struct Class {
    name: String,
    methods: Vec<Method>,
}

/// Whether a declared type is one php coerces a `Stringable` for: a union
/// that names `string` and could not take the object as it is — so
/// `string`, `?string`, `array|string` and `string|int` qualify, and
/// `mixed`, `object|string` and `Stringable|string` do not.
fn is_string_type(ty: &Option<String>) -> bool {
    let Some(t) = ty.as_deref() else {
        return false;
    };
    let parts: Vec<String> = t
        .trim_start_matches('?')
        .split('|')
        .map(|p| p.trim().to_ascii_lowercase())
        .collect();
    parts.iter().any(|p| p == "string")
        && !parts.iter().any(|p| {
            p == "mixed" || p == "object" || p == "stringable" || p == "callable"
                || p.chars().next().is_some_and(|c| c.is_ascii_uppercase())
        })
}

/// Bits 0..48 flag the positional parameters; the top byte holds the index
/// *plus one* of a variadic `string ...$rest`, so every argument from that
/// position on is a string parameter too.
fn mask_of(params: &[Param]) -> u64 {
    let mut mask = 0u64;
    for (i, p) in params.iter().enumerate() {
        if !is_string_type(&p.ty) {
            continue;
        }
        if p.variadic {
            mask |= ((i as u64) + 1) << 56;
        } else if i < 48 {
            mask |= 1 << i;
        }
    }
    mask
}

pub fn run(args: &[String]) -> XtaskResult {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives one level below the workspace root")
        .to_path_buf();
    let manifest = args
        .first()
        .map(|a| root.join(a))
        .unwrap_or_else(|| root.join("manifest/php-8.5.0"));
    let functions: BTreeMap<String, Sig> = serde_json::from_str(&fs::read_to_string(manifest.join("functions.json"))?)?;
    let classes: BTreeMap<String, Class> = serde_json::from_str(&fs::read_to_string(manifest.join("classes.json"))?)?;

    // (key, mask, [(position, name, type text)] for the flagged parameters)
    let mut rows: Vec<(String, u64, Vec<(usize, String, String)>)> = Vec::new();
    let flagged = |params: &[Param]| -> Vec<(usize, String, String)> {
        params
            .iter()
            .enumerate()
            .filter(|(_, p)| is_string_type(&p.ty))
            .map(|(i, p)| {
                let ty = p.ty.clone().unwrap_or_default();
                let ty = if p.nullable && !ty.contains("null") && !ty.starts_with('?') {
                    format!("?{ty}")
                } else {
                    ty
                };
                (i, p.name.clone(), ty)
            })
            .collect()
    };
    for (name, sig) in &functions {
        let m = mask_of(&sig.params);
        if m != 0 {
            rows.push((name.to_ascii_lowercase(), m, flagged(&sig.params)));
        }
    }
    for class in classes.values() {
        for method in &class.methods {
            let m = mask_of(&method.params);
            if m != 0 {
                rows.push((
                    format!("{}::{}", class.name.to_ascii_lowercase(), method.name.to_ascii_lowercase()),
                    m,
                    flagged(&method.params),
                ));
            }
        }
    }
    rows.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("//! Generated by `cargo xtask string-params` from the php manifest — do\n");
    out.push_str("//! not edit. The native parameters php declares as `string`, which its\n");
    out.push_str("//! argument parser calls `__toString()` for: one row per native with at\n");
    out.push_str("//! least one, bit *i* for parameter *i*; the top byte is the index plus one\n");
    out.push_str("//! of a variadic `string ...$rest`, from which every argument is one.\n");
    out.push_str("//! Keys are lowercase; a method is `class::method`. Each row also names\n");
    out.push_str("//! its flagged parameters — position, name, declared type — for the\n");
    out.push_str("//! `TypeError` an object without `__toString()` earns.\n\n");
    out.push_str(&format!("/// {} natives.\n", rows.len()));
    out.push_str("pub static STRING_PARAMS: &[(&str, u64, &[(u8, &str, &str)])] = &[\n");
    for (name, mask, params) in &rows {
        let ps: Vec<String> = params
            .iter()
            .map(|(i, n, t)| format!("({i}, {n:?}, {t:?})"))
            .collect();
        out.push_str(&format!("    ({:?}, {:#x}, &[{}]),\n", name, mask, ps.join(", ")));
    }
    out.push_str("];\n");
    let path = root.join("crates/rphp-runtime/src/string_params.rs");
    fs::write(&path, out)?;
    println!("string-params: {} rows -> {}", rows.len(), path.display());
    Ok(())
}
