//! `cargo xtask token-ids [--check]` — regenerate `crates/rphp-tokenizer/src/ids.rs`
//! from the installed `php` (override the binary with `PHP=/path/to/php`).
//!
//! The tokenizer's numeric token ids are PHP's own (`T_LNUMBER` = 260, …) and
//! move between PHP versions, so they are dumped from the oracle rather than
//! typed in: every `T_*` constant of ext/tokenizer plus the canonical
//! `token_name()` for ids 256..=450. The output is deterministic (sorted by id,
//! then name), so re-running against the same PHP is a no-op. `--check` fails
//! when the committed file differs (CI guard);
//! `crates/rphp-tokenizer/tests/ids_generated.rs` performs the same
//! comparison at test time without touching the file.

use crate::XtaskResult;
use std::path::PathBuf;
use std::process::Command;

/// Dump script: `C\t<name>\t<id>` per constant, `N\t<id>\t<name>` per named id,
/// `V\t<version>` last. Kept textually identical to the copy in
/// `crates/rphp-tokenizer/tests/ids_generated.rs`.
const PHP_SCRIPT: &str = r#"foreach (get_defined_constants(true)["tokenizer"] as $k => $v) { if (str_starts_with($k, "T_")) echo "C\t$k\t$v\n"; } for ($i = 256; $i <= 450; $i++) { $n = token_name($i); if ($n !== "UNKNOWN") echo "N\t$i\t$n\n"; } echo "V\t", PHP_VERSION, "\n";"#;

struct Dump {
    version: String,
    /// `(name, id)` sorted by id then name.
    consts: Vec<(String, u16)>,
    /// `(id, canonical name)` sorted by id.
    names: Vec<(u16, String)>,
}

pub fn run(args: &[String]) -> XtaskResult {
    let mut check = false;
    for a in args {
        match a.as_str() {
            "--check" => check = true,
            other => return Err(format!("unknown argument `{other}` (usage: token-ids [--check])").into()),
        }
    }
    let php = std::env::var("PHP").unwrap_or_else(|_| "php".to_string());
    let out = Command::new(&php)
        .args(["-n", "-r", PHP_SCRIPT])
        .output()
        .map_err(|e| format!("cannot run `{php}`: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "`{php} -n -r …` failed ({}): {}",
            out.status,
            String::from_utf8_lossy(&out.stderr)
        )
        .into());
    }
    let dump = parse(&String::from_utf8(out.stdout)?)?;
    let rendered = render(&dump);

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or("xtask has no parent directory")?
        .join("crates/rphp-tokenizer/src/ids.rs");
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    if current == rendered {
        println!(
            "token-ids: {} is up to date ({} constants, {} named ids, PHP {})",
            path.display(),
            dump.consts.len(),
            dump.names.len(),
            dump.version
        );
        return Ok(());
    }
    if check {
        return Err(format!(
            "{} is stale for PHP {}; run `cargo xtask token-ids`",
            path.display(),
            dump.version
        )
        .into());
    }
    std::fs::write(&path, rendered)?;
    println!(
        "token-ids: wrote {} ({} constants, {} named ids, PHP {})",
        path.display(),
        dump.consts.len(),
        dump.names.len(),
        dump.version
    );
    Ok(())
}

fn parse(text: &str) -> Result<Dump, Box<dyn std::error::Error>> {
    let mut consts = Vec::new();
    let mut names = Vec::new();
    let mut version = None;
    for line in text.lines() {
        let mut f = line.split('\t');
        match (f.next(), f.next(), f.next()) {
            (Some("C"), Some(name), Some(id)) => consts.push((name.to_string(), id.parse::<u16>()?)),
            (Some("N"), Some(id), Some(name)) => names.push((id.parse::<u16>()?, name.to_string())),
            (Some("V"), Some(v), None) => version = Some(v.to_string()),
            _ => return Err(format!("unexpected dump line: {line:?}").into()),
        }
    }
    if consts.is_empty() || names.is_empty() {
        return Err("php produced no token constants (is ext/tokenizer loaded?)".into());
    }
    consts.sort_by(|a, b| (a.1, &a.0).cmp(&(b.1, &b.0)));
    names.sort_by_key(|n| n.0);
    Ok(Dump { version: version.ok_or("dump has no version line")?, consts, names })
}

fn render(d: &Dump) -> String {
    let mut s = String::new();
    s.push_str("//! PHP token ids and names.\n//!\n");
    s.push_str(&format!(
        "//! GENERATED by `cargo xtask token-ids` from PHP {} (`get_defined_constants(true)['tokenizer']`\n",
        d.version
    ));
    s.push_str("//! and `token_name()` for ids 256..=450). Do not edit by hand: re-run the xtask after a PHP\n");
    s.push_str("//! upgrade; `tests/ids_generated.rs` re-derives this table from the installed `php` and fails\n");
    s.push_str("//! if it drifted. Ids below 256 are the byte values of single-character tokens.\n\n");
    for (name, id) in &d.consts {
        s.push_str(&format!("/// `{name}` ({id}).\npub const {name}: u16 = {id};\n"));
    }
    s.push_str("\n/// Every `T_*` constant exported by ext/tokenizer as `(name, id)`, sorted by id then name.\n");
    s.push_str("/// Aliases share an id (`T_DOUBLE_COLON` / `T_PAAMAYIM_NEKUDOTAYIM`).\n");
    s.push_str("pub const ALL: &[(&str, u16)] = &[\n");
    for (name, id) in &d.consts {
        s.push_str(&format!("    (\"{name}\", {id}),\n"));
    }
    s.push_str("];\n\n");
    let min = d.consts.iter().map(|c| c.1).min().unwrap_or(0);
    let max = d.consts.iter().map(|c| c.1).max().unwrap_or(0);
    s.push_str(&format!(
        "/// Smallest id in [`ALL`].\npub const MIN_ID: u16 = {min};\n\n/// Largest id in [`ALL`].\npub const MAX_ID: u16 = {max};\n\n"
    ));
    s.push_str("/// The canonical name PHP's `token_name()` reports for `id`, or `None` where PHP reports\n");
    s.push_str("/// `UNKNOWN` (single-character tokens and unassigned ids).\n");
    s.push_str("pub const fn name_of(id: u16) -> Option<&'static str> {\n    match id {\n");
    for (id, name) in &d.names {
        s.push_str(&format!("        {id} => Some(\"{name}\"),\n"));
    }
    s.push_str("        _ => None,\n    }\n}\n");
    s
}
