<?php
// Dumps the plural rules from the stock php/ICU this project is measured
// against: ICU's `plurals` bundle — the cardinal and ordinal rule set of
// every language it has, and each rule set's keyword conditions (the
// `@integer` / `@decimal` samples left out). MessageFormatter's plural
// and selectordinal, and the rule-based formats' `$(…)$` plural text,
// select through these.
//
//   php -n tools/intl-data/dump-plurals.php > crates/rphp-ext-intl/src/msgfmt/plural_data.rs
$r = new ResourceBundle('plurals', 'ICUDATA', false);
$q = fn($s) => '"' . preg_replace_callback('/[\p{Cf}\x{00A0}\x{2000}-\x{200F}\x{2028}-\x{202F}\x{205F}-\x{206F}\x{3000}\x{FEFF}]/u', fn($m) => sprintf('\\u{%X}', mb_ord($m[0], 'UTF-8')), addcslashes($s, "\\\"\0..\37")) . '"';
$map = function ($name) use ($r) {
    $out = [];
    foreach ($r->get($name) as $k => $v) $out[$k] = $v;
    ksort($out, SORT_STRING);
    return $out;
};
$cardinal = $map('locales');
$ordinal = $map('locales_ordinals');
$sets = [];
foreach ($r->get('rules') as $set => $rules) {
    $list = [];
    foreach ($rules as $kw => $cond) {
        $cond = trim(preg_replace('/@(integer|decimal).*$/s', '', $cond));
        $list[] = [$kw, $cond];
    }
    $sets[$set] = $list;
}
ksort($sets, SORT_STRING);
echo "//! Generated by `tools/intl-data/dump-plurals.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! ICU's plural rules: the cardinal and ordinal rule set of each locale, and the keyword conditions of\n//! each rule set.\n\n";
echo "/// Locale → cardinal rule set, sorted.\npub static CARDINAL: &[(&str, &str)] = &[\n";
foreach ($cardinal as $k => $v) echo "    (", $q($k), ", ", $q($v), "),\n";
echo "];\n\n/// Locale → ordinal rule set, sorted.\npub static ORDINAL: &[(&str, &str)] = &[\n";
foreach ($ordinal as $k => $v) echo "    (", $q($k), ", ", $q($v), "),\n";
echo "];\n\n/// Rule set → (keyword, condition), sorted by rule set.\npub static RULES: &[(&str, &[(&str, &str)])] = &[\n";
foreach ($sets as $set => $list) {
    echo "    (", $q($set), ", &[", implode(", ", array_map(fn($p) => "(" . $q($p[0]) . ", " . $q($p[1]) . ")", $list)), "]),\n";
}
echo "];\n";
