<?php
// Dumps the transliterator registry behind `Transliterator::create()`:
// `Transliterator::listIDs()` of the stock php/ICU this project is measured
// against (its order is ICU's hashtable order, which php hands back as is),
// and every rule-based ID ICU registers — the forward and backward IDs and
// aliases of CLDR's transforms metadata — mapped to the ICU4X data marker
// that carries the same CLDR rules (`und-Latn-t-und-cyrl`, …), or, where
// ICU4X ships no baked data, to the CLDR rules source compiled at runtime.
//
//   php -n tools/intl-data/dump-translit.php <cldr-json>/cldr-transforms/transforms \
//       ~/.cargo/registry/src/*/icu_experimental_data-0.6.0/data/transliterator_rules_v1.rs.data \
//       > crates/rphp-ext-intl/src/translit/table.rs
//
// The rules sources it names are copied by hand to
// crates/rphp-ext-intl/src/translit/rules/ (they are few and small).
[$_, $dir, $bakedFile] = $argv;
preg_match_all('/pub const TRANSLITERATOR_RULES_V1_UND_([A-Z0-9_]+)/', file_get_contents($bakedFile), $m);
$baked = [];
foreach ($m[1] as $k) $baked[strtolower(str_replace('_', '-', $k))] = true;

$registry = [];
$sources = [];
$add = function (string $name, string $target) use (&$registry) {
    $k = strtolower($name);
    if (!isset($registry[$k])) $registry[$k] = $target;
};
foreach (glob("$dir/*.json") as $f) {
    $j = json_decode(file_get_contents($f), true);
    $var = isset($j['_variant']) ? '/' . $j['_variant'] : '';
    $dirs = [];
    if ($j['_direction'] !== 'backward') {
        $dirs[] = [false, "{$j['_source']}-{$j['_target']}$var", $j['_alias'] ?? '', $j['_aliasBcp47'] ?? ''];
    }
    if ($j['_direction'] !== 'forward') {
        $dirs[] = [true, "{$j['_target']}-{$j['_source']}$var", $j['_backwardAlias'] ?? '', $j['_backwardAliasBcp47'] ?? ''];
    }
    foreach ($dirs as [$rev, $id, $aliases, $bcps]) {
        $target = null;
        // ICU4X's baked Han-Latin predates CLDR 48 (it folds fullwidth
        // punctuation and spaces pinyin from Latin): compile CLDR's source.
        if (in_array($j['_rulesFile'], ['Han-Latin.txt'], true)) $bcps = '';
        foreach (preg_split('/\s+/', trim($bcps), -1, PREG_SPLIT_NO_EMPTY) as $b) {
            if (isset($baked[strtolower($b)])) { $target = 'B:' . strtolower($b); break; }
        }
        if ($target === null) {
            if ($j['_visibility'] === 'internal') continue; // reached only through other rules
            $target = ($rev ? 'R:' : 'F:') . $j['_rulesFile'];
            $sources[$j['_rulesFile']] = true;
        }
        $add($id, $target);
        foreach (preg_split('/\s+/', trim($aliases), -1, PREG_SPLIT_NO_EMPTY) as $a) $add($a, $target);
    }
}
// ICU's own aliases (translit/root.txt) that CLDR's metadata does not carry.
$add('Tone-Digit', $registry['pinyin-numericpinyin']);
$add('Digit-Tone', $registry['numericpinyin-pinyin']);
ksort($registry, SORT_STRING);

$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
echo "// @generated by tools/intl-data/dump-translit.php from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " and CLDR's transforms — do not edit.\n";
echo "//! `Transliterator::listIDs()` and ICU's rule-based transliterator registry.\n\n";
echo "use super::Rbt;\n\n";
echo "/// `Transliterator::listIDs()`, in ICU's order.\n";
echo "pub static LIST_IDS: &[&str] = &[\n";
foreach (Transliterator::listIDs() as $id) echo "    ", $q($id), ",\n";
echo "];\n\n";
echo "/// Every rule-based ID ICU registers (lowercased, sorted) and where its rules live.\n";
echo "pub static REGISTRY: &[(&str, Rbt)] = &[\n";
foreach ($registry as $k => $t) {
    [$kind, $v] = explode(':', $t, 2);
    $e = match ($kind) {
        'B' => "Rbt::Baked(" . $q($v) . ")",
        'F' => "Rbt::Source(" . $q($v) . ", false)",
        'R' => "Rbt::Source(" . $q($v) . ", true)",
    };
    echo "    (", $q($k), ", $e),\n";
}
echo "];\n";
fwrite(STDERR, "sources: " . implode(' ', array_keys($sources)) . "\n");
