<?php
// Dumps the list patterns behind IntlListFormatter from the stock php/ICU
// this project is measured against: for every locale ICU knows and each
// of the nine type × width combinations, the glue ICU puts between the
// items — CLDR's `2`, `start`, `middle` and `end` list patterns as the
// text between `{0}` and `{1}` and, for `2` and `end`, after `{1}` —
// read back from IntlListFormatter::format() over marker items, so ICU's
// own style aliases and bundle fallback are in the result. (No CLDR list
// pattern has text before `{0}`, nor `start`/`middle` after `{1}`; the
// script stops if one does.) Rows are deduplicated; a locale points at
// its row.
//
//   php -n tools/intl-data/dump-listfmt.php > crates/rphp-ext-intl/src/listfmt/data.rs
$types = [IntlListFormatter::TYPE_AND, IntlListFormatter::TYPE_OR, IntlListFormatter::TYPE_UNITS];
$widths = [IntlListFormatter::WIDTH_WIDE, IntlListFormatter::WIDTH_SHORT, IntlListFormatter::WIDTH_NARROW];
$rows = []; $index = []; $locales = [];
$all = ResourceBundle::getLocales('');
$all[] = 'en_US_POSIX';
sort($all);
// the items after the first start with a Hebrew letter, so that none of
// ICU's contextual handlers (Spanish y/e, o/u; Hebrew ו/ו-) fires
[$A, $B, $C, $D] = ["\u{E000}", "\u{5D0}\u{E001}", "\u{5D0}\u{E002}", "\u{5D0}\u{E003}"];
// the text between two markers
$between = function (string $s, string $x, string $y) {
    $i = strpos($s, $x); $j = strpos($s, $y);
    if ($i === false || $j === false || $j < $i) throw new Exception("markers out of order in " . json_encode($s));
    return substr($s, $i + strlen($x), $j - $i - strlen($x));
};
foreach (array_unique($all) as $loc) {
    $row = [];
    foreach ($types as $t) foreach ($widths as $w) {
        $f = new IntlListFormatter($loc, $t, $w);
        $two = $f->format([$A, $B]);
        $three = $f->format([$A, $B, $C]);
        $four = $f->format([$A, $B, $C, $D]);
        foreach ([$two, $three, $four] as $s) {
            if (!str_starts_with($s, $A)) throw new Exception("$loc: a list pattern with a prefix: " . json_encode($s));
        }
        $p2 = $between($two, $A, $B);
        $p2s = substr($two, strpos($two, $B) + strlen($B));
        $start = $between($four, $A, $B);
        $middle = $between($four, $B, $C);
        $end = $between($four, $C, $D);
        $ends = substr($four, strpos($four, $D) + strlen($D));
        // the derivation must give back the three-item form
        if ($A . $start . $B . $end . $C . $ends !== $three) throw new Exception("$loc: inconsistent three-item list " . json_encode($three));
        array_push($row, $p2, $p2s, $start, $middle, $end, $ends);
    }
    $key = json_encode($row);
    if (!isset($index[$key])) { $index[$key] = count($rows); $rows[] = $row; }
    $locales[$loc] = $index[$key];
}
$q = fn($s) => '"' . preg_replace_callback('/[\p{Cf}\x{00A0}\x{2000}-\x{200F}\x{2028}-\x{202F}\x{205F}-\x{206F}\x{3000}\x{FEFF}]/u', fn($m) => sprintf('\\u{%X}', mb_ord($m[0], 'UTF-8')), addcslashes($s, "\\\"\0..\37")) . '"';
echo "//! Generated by `tools/intl-data/dump-listfmt.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! The list glue of every ICU locale: for TYPE_AND, TYPE_OR, TYPE_UNITS × WIDTH_WIDE, WIDTH_SHORT,\n//! WIDTH_NARROW in that order, the `2` pattern's infix and suffix, the `start` and `middle` infixes,\n//! the `end` pattern's infix and suffix (index `(type * 3 + width) * 6 + part`).\n\n";
echo "pub static ROWS: &[[&str; 54]] = &[\n";
foreach ($rows as $r) { echo "    [", implode(", ", array_map($q, $r)), "],\n"; }
echo "];\n\n/// Locale → row, sorted by locale for a binary search.\npub static LOCALES: &[(&str, u16)] = &[\n";
foreach ($locales as $loc => $i) { echo "    (", $q($loc), ", $i),\n"; }
echo "];\n";
