<?php
// Dumps the locale data behind IntlDateFormatter's styles from the stock
// php/ICU this project is measured against: for every locale ICU knows,
// `getPattern()` of each date style × time style (FULL, LONG, MEDIUM,
// SHORT, NONE — 25 combinations, the Gregorian calendar). Rows are
// deduplicated; a locale points at its row.
//
//   php -n tools/intl-data/dump-datefmt.php > crates/rphp-ext-intl/src/data/datefmt.rs
$styles = [IntlDateFormatter::FULL, IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, IntlDateFormatter::NONE];
$rows = []; $index = []; $locales = [];
$all = ResourceBundle::getLocales('');
$all[] = 'en_US_POSIX';
sort($all);
foreach (array_unique($all) as $loc) {
    $pat = [];
    foreach ($styles as $d) foreach ($styles as $t) { $f = new IntlDateFormatter($loc, $d, $t, 'UTC'); $pat[] = $f->getPattern(); }
    $key = json_encode($pat);
    if (!isset($index[$key])) { $index[$key] = count($rows); $rows[] = $pat; }
    $locales[$loc] = $index[$key];
}
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
echo "//! Generated by `tools/intl-data/dump-datefmt.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! `IntlDateFormatter::getPattern()` of every ICU locale for each date style × time style, FULL, LONG,\n//! MEDIUM, SHORT, NONE in that order (index `date * 5 + time`), the Gregorian calendar.\n\n";
echo "pub static ROWS: &[[&str; 25]] = &[\n";
foreach ($rows as $r) { echo "    [", implode(", ", array_map($q, $r)), "],\n"; }
echo "];\n\n/// Locale → row, sorted by locale for a binary search.\npub static LOCALES: &[(&str, u16)] = &[\n";
foreach ($locales as $loc => $i) { echo "    (", $q($loc), ", $i),\n"; }
echo "];\n";
