<?php
// Dumps the calendar names behind IntlDateFormatter from the stock php/ICU
// this project is measured against: for every locale ICU knows, the month,
// weekday, era, AM/PM, day-period, quarter and relative-day names in every
// width, as the fields `M L E c G a b B Q q` of a pattern render them. Rows
// are deduplicated; a locale points at its row.
//
//   php -n tools/intl-data/dump-datenames.php > crates/rphp-ext-intl/src/data/datenames.rs
date_default_timezone_set('UTC');
$rows = []; $index = []; $locales = [];
$all = ResourceBundle::getLocales('');
$all[] = 'en_US_POSIX';
sort($all);
$fmt = function ($loc, $pat, $ts) {
    static $cache = [];
    $key = "$loc\0$pat";
    if (!isset($cache[$key])) $cache[$key] = new IntlDateFormatter($loc, IntlDateFormatter::NONE, IntlDateFormatter::NONE, 'UTC', IntlDateFormatter::GREGORIAN, $pat);
    return $cache[$key]->format($ts);
};
$now = time();
$today = strtotime('today 12:00', $now);
foreach (array_unique($all) as $loc) {
    $names = [];
    // months: format and standalone, abbreviated / wide / narrow
    foreach (['MMM', 'MMMM', 'MMMMM', 'LLL', 'LLLL', 'LLLLL'] as $p) {
        for ($m = 1; $m <= 12; $m++) $names[] = $fmt($loc, $p, gmmktime(12, 0, 0, $m, 15, 2023));
    }
    // weekdays Sunday..Saturday: format and standalone, abbreviated / wide / narrow / short
    foreach (['EEE', 'EEEE', 'EEEEE', 'EEEEEE', 'ccc', 'cccc', 'ccccc', 'cccccc'] as $p) {
        for ($d = 12; $d <= 18; $d++) $names[] = $fmt($loc, $p, gmmktime(12, 0, 0, 11, $d, 2023));
    }
    // eras AD / BC: abbreviated, wide, narrow
    foreach (['G', 'GGGG', 'GGGGG'] as $p) {
        $names[] = $fmt($loc, $p, gmmktime(12, 0, 0, 6, 15, 2023));
        $names[] = $fmt($loc, $p, -65000000000); // 90 BC
    }
    // AM / PM: abbreviated, wide, narrow
    foreach (['a', 'aaaa', 'aaaaa'] as $p) {
        $names[] = $fmt($loc, $p, gmmktime(10, 0, 0, 6, 15, 2023));
        $names[] = $fmt($loc, $p, gmmktime(22, 0, 0, 6, 15, 2023));
    }
    // midnight / noon (`b`), abbreviated, wide, narrow
    foreach (['b', 'bbbb', 'bbbbb'] as $p) {
        $names[] = $fmt($loc, $p, gmmktime(0, 0, 0, 6, 15, 2023));
        $names[] = $fmt($loc, $p, gmmktime(12, 0, 0, 6, 15, 2023));
    }
    // flexible day periods (`B`) for every hour on the hour and at the half hour
    foreach (['B', 'BBBB', 'BBBBB'] as $p) {
        for ($h = 0; $h < 24; $h++) { $names[] = $fmt($loc, $p, gmmktime($h, 0, 0, 6, 15, 2023)); $names[] = $fmt($loc, $p, gmmktime($h, 30, 0, 6, 15, 2023)); }
    }
    // quarters: format and standalone, abbreviated / wide
    foreach (['QQQ', 'QQQQ', 'qqq', 'qqqq'] as $p) {
        foreach ([2, 5, 8, 11] as $m) $names[] = $fmt($loc, $p, gmmktime(12, 0, 0, $m, 15, 2023));
    }
    // relative days -2..+2: the word, or "" when the day has none
    $plain = new IntlDateFormatter($loc, IntlDateFormatter::FULL, IntlDateFormatter::NONE, 'UTC');
    $rel = new IntlDateFormatter($loc, IntlDateFormatter::RELATIVE_FULL, IntlDateFormatter::NONE, 'UTC');
    for ($k = -2; $k <= 2; $k++) { $ts = $today + $k * 86400; $r = $rel->format($ts); $names[] = $r === $plain->format($ts) ? '' : $r; }
    // the relative date-time glue per style: `{1}` the day, `{0}` the time
    foreach ([IntlDateFormatter::RELATIVE_FULL, IntlDateFormatter::RELATIVE_LONG, IntlDateFormatter::RELATIVE_MEDIUM, IntlDateFormatter::RELATIVE_SHORT] as $s) {
        $word = $rel->format($today);
        $time = (new IntlDateFormatter($loc, IntlDateFormatter::NONE, IntlDateFormatter::SHORT, 'UTC'))->format($today);
        $both = (new IntlDateFormatter($loc, $s, IntlDateFormatter::SHORT, 'UTC'))->format($today);
        $glue = $both;
        if ($word !== '' && $time !== '' && strpos($both, $word) !== false && strpos($both, $time) !== false) { $glue = str_replace([$word, $time], ['{1}', '{0}'], $both); }
        $names[] = $glue;
    }
    $key = json_encode($names);
    if (!isset($index[$key])) { $index[$key] = count($rows); $rows[] = $names; }
    $locales[$loc] = $index[$key];
}
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
echo "//! Generated by `tools/intl-data/dump-datenames.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! The calendar names of every ICU locale as `IntlDateFormatter` renders the fields, in this order:\n";
echo "//! months ×12 for MMM MMMM MMMMM LLL LLLL LLLLL (0..71); weekdays Sunday..Saturday ×7 for EEE EEEE EEEEE\n";
echo "//! EEEEEE ccc cccc ccccc cccccc (72..127); eras AD,BC for G GGGG GGGGG (128..133); AM,PM for a aaaa aaaaa\n";
echo "//! (134..139); midnight,noon for b bbbb bbbbb (140..145); day periods for B BBBB BBBBB at each hour on the\n";
echo "//! hour and at :30 (146..289); quarters ×4 for QQQ QQQQ qqq qqqq (290..305); relative days -2..+2 (306..310);\n";
echo "//! the relative date-time glue for RELATIVE_FULL/LONG/MEDIUM/SHORT (311..314).\n\n";
echo "pub const N: usize = 315;\n\n";
echo "pub static ROWS: &[[&str; 315]] = &[\n";
foreach ($rows as $r) { echo "    [", implode(", ", array_map($q, $r)), "],\n"; }
echo "];\n\n/// Locale → row, sorted by locale for a binary search.\npub static LOCALES: &[(&str, u16)] = &[\n";
foreach ($locales as $loc => $i) { echo "    (", $q($loc), ", $i),\n"; }
echo "];\n";

// The locales whose traditional calendar is not the Gregorian one.
echo "\n/// The calendar `IntlDateFormatter::TRADITIONAL` means in a locale, where it is not `gregorian`.\npub static TRADITIONAL: &[(&str, &str)] = &[\n";
foreach (array_unique($all) as $loc) {
    $t = IntlCalendar::createInstance('UTC', $loc)->getType();
    if ($t !== 'gregorian') echo "    (", $q($loc), ", ", $q($t), "),\n";
}
echo "];\n";
