<?php
// Dumps the locale data behind NumberFormatter from the stock php/ICU this
// project is measured against: for every locale ICU knows, the patterns of
// the six pattern-driven styles and the 18 symbols (from the DECIMAL
// formatter, the currency symbol/code from the CURRENCY one). Rows are
// deduplicated; a locale points at its row.
//
//   php -n tools/intl-data/dump-numfmt.php > crates/rphp-ext-intl/src/data/numfmt.rs
$styles = [NumberFormatter::DECIMAL, NumberFormatter::CURRENCY, NumberFormatter::PERCENT, NumberFormatter::SCIENTIFIC, NumberFormatter::CURRENCY_ACCOUNTING, NumberFormatter::CURRENCY_PLURAL];
$rows = []; $index = []; $locales = [];
$all = ResourceBundle::getLocales('');
$all[] = 'en_US_POSIX';
sort($all);
foreach (array_unique($all) as $loc) {
    $pat = [];
    foreach ($styles as $s) { $f = new NumberFormatter($loc, $s); $pat[] = $f->getPattern(); }
    $dec = new NumberFormatter($loc, NumberFormatter::DECIMAL);
    $cur = new NumberFormatter($loc, NumberFormatter::CURRENCY);
    $sym = [];
    for ($i = 0; $i < 18; $i++) { $sym[] = $i === 8 || $i === 9 ? $cur->getSymbol($i) : $dec->getSymbol($i); }
    $key = json_encode([$pat, $sym]);
    if (!isset($index[$key])) { $index[$key] = count($rows); $rows[] = [$pat, $sym]; }
    $locales[$loc] = $index[$key];
}
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
echo "//! Generated by `tools/intl-data/dump-numfmt.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! The number patterns and symbols of every ICU locale: `NumberFormatter::getPattern()` for\n//! DECIMAL, CURRENCY, PERCENT, SCIENTIFIC, CURRENCY_ACCOUNTING and CURRENCY_PLURAL, and the 18 symbols in\n//! `NumberFormatter::*_SYMBOL` order (the currency symbol and code are the locale's default currency).\n\n";
echo "/// One locale's row: the six patterns, the eighteen symbols.\npub struct NumRow {\n    pub patterns: [&'static str; 6],\n    pub symbols: [&'static str; 18],\n}\n\n";
echo "pub static ROWS: &[NumRow] = &[\n";
foreach ($rows as $r) { echo "    NumRow { patterns: [", implode(", ", array_map($q, $r[0])), "], symbols: [", implode(", ", array_map($q, $r[1])), "] },\n"; }
echo "];\n\n/// Locale → row, sorted by locale for a binary search.\npub static LOCALES: &[(&str, u16)] = &[\n";
foreach ($locales as $loc => $i) { echo "    (", $q($loc), ", $i),\n"; }
echo "];\n";

// The languages ICU accepts in a formatter's locale (php 8.4+'s
// constructors throw `ValueError` for any other): every 2- and 3-letter
// code `new NumberFormatter($code)` takes.
$langs = [];
for ($a = 0; $a < 26; $a++) for ($b = 0; $b < 26; $b++) {
    $two = chr(97 + $a) . chr(97 + $b);
    try { new NumberFormatter($two, NumberFormatter::DECIMAL); $langs[] = $two; } catch (ValueError $e) {}
    for ($c = 0; $c < 26; $c++) {
        $three = $two . chr(97 + $c);
        try { new NumberFormatter($three, NumberFormatter::DECIMAL); $langs[] = $three; } catch (ValueError $e) {}
    }
}
echo "\n/// The language codes ICU's formatters accept (`uloc_getISOLanguages()` plus the aliases); the constructors\n/// throw `ValueError` for any other, as php 8.4+ does.\npub static LANGUAGES: &[&str] = &[\n";
foreach ($langs as $l) echo "    ", $q($l), ",\n";
echo "];\n";

// CLDR's region → currency (`ucurr_forLocale`): the currency a locale's
// region implies, by region code.
$regions = [];
for ($a = 0; $a < 26; $a++) for ($b = 0; $b < 26; $b++) {
    $r = chr(65 + $a) . chr(65 + $b);
    $f = new NumberFormatter("en_$r", NumberFormatter::CURRENCY);
    $code = $f->getTextAttribute(NumberFormatter::CURRENCY_CODE);
    if ($code !== 'XXX') $regions[$r] = $code;
}
for ($n = 0; $n < 1000; $n++) {
    $r = sprintf('%03d', $n);
    $f = new NumberFormatter("en_$r", NumberFormatter::CURRENCY);
    $code = $f->getTextAttribute(NumberFormatter::CURRENCY_CODE);
    if ($code !== 'XXX') $regions[$r] = $code;
}
echo "\n/// The currency a region implies (`ucurr_forLocale`), by region code.\npub static REGION_CURRENCIES: &[(&str, &str)] = &[\n";
foreach ($regions as $r => $c) echo "    (", $q($r), ", ", $q($c), "),\n";
echo "];\n";
