<?php
// Dumps the currency symbols behind NumberFormatter from the stock php/ICU
// this project is measured against: for every ICU locale and every ISO
// 4217 code ICU knows, the symbol `¤` renders — only where it differs from
// the code itself (absence means the code). Maps are deduplicated; a
// locale points at its map. Also the codes themselves, the plural names
// (`¤¤¤`) for the `one`/`other` forms in English are left to ICU4X.
//
//   php -n tools/intl-data/dump-currency.php > crates/rphp-ext-intl/src/data/currency.rs
$b = new ResourceBundle('en', 'ICUDATA-curr');
$codes = [];
foreach ($b->get('Currencies') as $k => $v) $codes[] = $k;
sort($codes);
$maps = []; $index = []; $locales = [];
$all = ResourceBundle::getLocales('');
$all[] = 'en_US_POSIX';
sort($all);
foreach (array_unique($all) as $loc) {
    $f = new NumberFormatter($loc, NumberFormatter::CURRENCY);
    $map = [];
    foreach ($codes as $code) {
        $f->setTextAttribute(NumberFormatter::CURRENCY_CODE, $code);
        $sym = $f->getSymbol(NumberFormatter::CURRENCY_SYMBOL);
        if ($sym !== $code) $map[$code] = $sym;
    }
    $key = json_encode($map);
    if (!isset($index[$key])) { $index[$key] = count($maps); $maps[] = $map; }
    $locales[$loc] = $index[$key];
}
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
echo "//! Generated by `tools/intl-data/dump-currency.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! The currency symbols of every ICU locale, per ISO 4217 code, where they differ from the code\n//! (`NumberFormatter::getSymbol(CURRENCY_SYMBOL)` after `setTextAttribute(CURRENCY_CODE, …)`).\n\n";
echo "/// The ISO 4217 codes ICU knows.\npub static CODES: &[&str] = &[\n";
foreach ($codes as $c) echo "    ", $q($c), ",\n";
echo "];\n\n/// Symbol maps: (code, symbol) pairs sorted by code.\npub static MAPS: &[&[(&str, &str)]] = &[\n";
foreach ($maps as $m) { echo "    &["; $parts = []; foreach ($m as $c => $s) $parts[] = "(" . $q($c) . ", " . $q($s) . ")"; echo implode(", ", $parts), "],\n"; }
echo "];\n\n/// Locale → map, sorted by locale for a binary search.\npub static LOCALES: &[(&str, u16)] = &[\n";
foreach ($locales as $loc => $i) echo "    (", $q($loc), ", $i),\n";
echo "];\n";

// The fraction digits and rounding increments of every currency for the
// standard and the cash usage (`ucurr_getDefaultFractionDigitsForUsage`,
// `ucurr_getRoundingIncrementForUsage`), read off formatted amounts.
$std = new NumberFormatter('en_US', NumberFormatter::CURRENCY);
$cash = new NumberFormatter('en_US', NumberFormatter::CASH_CURRENCY);
$probe = function ($f, $code) {
    $one = $f->formatCurrency(1, $code);
    $digits = preg_match('/\\.(\\d+)/', $one, $m) ? strlen($m[1]) : 0;
    $unit = 10 ** -$digits;
    $three = $f->formatCurrency(3 * $unit, $code);
    $thirty = $f->formatCurrency(30 * $unit, $code);
    $num = fn($s) => (float) preg_replace('/[^0-9.]/', '', $s);
    $inc = 1;
    if (abs($num($three) - 5 * $unit) < $unit / 10) $inc = 5;
    elseif (abs($num($three)) < $unit / 10 && abs($num($thirty) - 50 * $unit) < $unit / 10) $inc = 50;
    return [$digits, $inc];
};
echo "\n/// Fraction digits and rounding increment (in units of the last digit) per code, for the standard and the\n/// cash usage: (code, digits, increment, cash digits, cash increment). Only codes off the (2, 1, 2, 1) default.\npub static FRACTIONS: &[(&str, u8, u8, u8, u8)] = &[\n";
foreach ($codes as $code) {
    [$d, $i] = $probe($std, $code);
    [$cd, $ci] = $probe($cash, $code);
    if ([$d, $i, $cd, $ci] !== [2, 1, 2, 1]) echo "    (", $q($code), ", $d, $i, $cd, $ci),\n";
}
echo "];\n";
