<?php
// Dumps the rule-based number format rules from the stock php/ICU this
// project is measured against: for every locale ICU knows, the rules ICU
// builds its SPELLOUT, ORDINAL and DURATION formatters from — the
// `RBNFRules` arrays of ICU's rbnf bundles as written (the `>>>` and `>>`
// tokens that NumberFormatter::getPattern() would normalize away kept),
// found the way ICU finds them: the bundle NumberFormatter reports as its
// actual locale, then its `%%Parent` or truncated parents up to root. The
// `%%lenient-parse` collation rules are left out. Also that actual
// locale: its plural rules and decimal symbols are the ones the rules run
// with. Rule texts are deduplicated; a locale points at its row.
//
//   php -n tools/intl-data/dump-rbnf.php > crates/rphp-ext-intl/src/rbnf/data.rs
$kinds = [NumberFormatter::SPELLOUT => 'SpelloutRules', NumberFormatter::ORDINAL => 'OrdinalRules', NumberFormatter::DURATION => 'DurationRules'];
$texts = []; $index = []; $locales = []; $rows = []; $rowIndex = [];
$all = ResourceBundle::getLocales('');
$all[] = 'en_US_POSIX';
sort($all);
$cache = [];
// the rules of `$key` for a bundle, climbing its parents
$rules = function (string $bundle, string $key) use (&$cache) {
    for ($b = $bundle; ; ) {
        if (!isset($cache[$b])) $cache[$b] = new ResourceBundle($b === '' ? 'root' : $b, 'ICUDATA-rbnf', false) ?: false;
        $rb = $cache[$b];
        if ($rb) {
            $r = $rb->get('RBNFRules', false);
            if ($r && ($lines = $r->get($key, false))) {
                $out = []; $skip = false;
                foreach ($lines as $line) {
                    if (str_starts_with($line, '%%lenient-parse:')) { $skip = true; continue; }
                    if ($skip && str_starts_with($line, '%')) $skip = false;
                    if (!$skip) $out[] = $line;
                }
                return implode("\n", $out);
            }
            $parent = $rb->get('%%Parent', false);
        } else {
            $parent = null;
        }
        if ($b === 'root') throw new Exception("no $key for $bundle");
        if (is_string($parent) && $parent !== '') { $b = $parent; continue; }
        $i = strrpos($b, '_');
        $b = $i === false ? 'root' : substr($b, 0, $i);
    }
};
foreach (array_unique($all) as $loc) {
    $row = []; $act = [];
    foreach ($kinds as $k => $key) {
        $actual = (new NumberFormatter($loc, $k))->getLocale(Locale::ACTUAL_LOCALE);
        $t = $rules($actual, $key);
        if (!isset($index[$t])) { $index[$t] = count($texts); $texts[] = $t; }
        $row[] = $index[$t];
        $act[] = $actual;
    }
    $key = json_encode([$row, $act]);
    if (!isset($rowIndex[$key])) { $rowIndex[$key] = count($rows); $rows[] = [$row, $act]; }
    $locales[$loc] = $rowIndex[$key];
}
$q = fn($s) => '"' . preg_replace_callback('/[\p{Cf}\x{00A0}\x{2000}-\x{200F}\x{2028}-\x{202F}\x{205F}-\x{206F}\x{3000}\x{FEFF}]/u', fn($m) => sprintf('\\u{%X}', mb_ord($m[0], 'UTF-8')), addcslashes($s, "\\\"\0..\37")) . '"';
echo "//! Generated by `tools/intl-data/dump-rbnf.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! The rule-based number format rules of every ICU locale (the `RBNFRules` of ICU's rbnf bundles, one\n//! source line per text line, the lenient-parse rules left out) and the locale of the bundle they are from.\n\n";
echo "pub static RULES: &[&str] = &[\n";
foreach ($texts as $t) { echo "    ", $q($t), ",\n"; }
echo "];\n\n/// The SPELLOUT, ORDINAL, DURATION rules (indexes into `RULES`) and the actual locale of each.\npub static ROWS: &[([u16; 3], [&str; 3])] = &[\n";
foreach ($rows as [$r, $a]) { echo "    ([", implode(", ", $r), "], [", implode(", ", array_map($q, $a)), "]),\n"; }
echo "];\n\n/// Locale → row, sorted by locale for a binary search.\npub static LOCALES: &[(&str, u16)] = &[\n";
foreach ($locales as $loc => $i) { echo "    (", $q($loc), ", $i),\n"; }
echo "];\n";
