<?php
// Dumps ICU's converter registry as the stock php/ICU this project is
// measured against reports it — `UConverter::getAvailable()`,
// `getAliases()` of each, `getStandards()`, which aliases ICU calls
// ambiguous, each converter's type, default substitution bytes and the
// substitution lengths it accepts — plus the full mapping tables of every
// single-byte (SBCS) converter: byte → code point (or unassigned /
// illegal) and the code points whose encoding is not the first byte that
// decodes to them.
//
//   php -n tools/intl-data/dump-uconverter.php > crates/rphp-ext-intl/src/uconverter/data.rs
class Probe extends UConverter {
    public array $to = [];
    public array $from = [];
    public function toUCallback($reason, $source, $codeUnits, &$error): string|int|array|null {
        if ($reason <= 2) { $this->to[] = [$reason, $codeUnits]; $error = 0; }
        return null;
    }
    public function fromUCallback($reason, $source, $codePoint, &$error): string|int|array|null {
        if ($reason <= 2) { $this->from[$codePoint] = true; $error = 0; }
        return null;
    }
}
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
$hex = fn($s) => implode(', ', array_map(fn($c) => sprintf('0x%02X', ord($c)), str_split($s)));
$available = UConverter::getAvailable();
$converters = [];
$aliasRows = [];
$tables = [];
foreach ($available as $name) {
    // A name ICU itself calls ambiguous cannot be constructed; its type
    // and substitution are never asked for.
    try {
        $u = new UConverter($name, $name);
        $type = $u->getSourceType();
        $subst = $u->getSubstChars();
    } catch (IntlException $e) {
        $type = -2;
        $subst = '';
    }
    $lens = [];
    for ($n = 1; $n <= 4 && $type !== -2; $n++) {
        $t = new UConverter($name, $name);
        if (@$t->setSubstChars(str_repeat('?', $n))) $lens[] = $n;
    }
    $aliases = UConverter::getAliases($name) ?: [];
    foreach ($aliases as $a) {
        // The converter ICU opens for the alias, and whether it warns.
        try {
            $chosen = (new UConverter($a, 'UTF-8'))->getDestinationEncoding();
            $ambiguous = false;
        } catch (IntlException $e) {
            if (!preg_match('/Ambiguous encoding specified, using (.*)$/', $e->getMessage(), $m)) continue;
            [$chosen, $ambiguous] = [$m[1], true];
        }
        $aliasRows[strtolower($a)] = [$chosen, $ambiguous];
    }
    if ($type === UConverter::SBCS) {
        $decode = [];
        for ($b = 0; $b < 256; $b++) {
            $p = new Probe('UTF-32BE', $name);
            $r = $p->convert(chr($b));
            if ($p->to) $decode[] = $p->to[0][0] === 0 ? 'U' : 'I';
            else $decode[] = unpack('N', $r)[1];
        }
        $first = [];
        foreach ($decode as $b => $cp) if (is_int($cp) && !isset($first[$cp])) $first[$cp] = $b;
        $all = '';
        $cps = [];
        for ($cp = 0; $cp < 0x10000; $cp++) {
            if ($cp >= 0xD800 && $cp < 0xE000) continue;
            $cps[] = $cp;
            $all .= mb_chr($cp, 'UTF-8');
        }
        $p = new Probe($name, 'UTF-8');
        $out = $p->convert($all);
        $i = 0;
        $over = [];
        foreach ($cps as $cp) {
            $enc = isset($p->from[$cp]) ? null : ord($out[$i++]);
            $default = $first[$cp] ?? null;
            if ($enc !== $default) $over[] = [$cp, $enc];
        }
        $tables[count($converters)] = [$decode, $over];
    }
    $converters[] = [$name, $type, $subst, $lens, $aliases];
}
echo "// @generated by tools/intl-data/dump-uconverter.php from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! ICU's converters: names, aliases, types, substitution bytes, SBCS tables.\n\n";
echo "#![allow(clippy::unreadable_literal)]\n\n";
echo "use super::{Conv, Sbcs, ILL, UNA};\n\n";
echo "/// `UConverter::getStandards()`.\n";
echo "pub static STANDARDS: &[&str] = &[", implode(', ', array_map($q, UConverter::getStandards())), "];\n\n";
echo "/// `UConverter::getAvailable()`, in ICU's order, with type, default substitution\n/// bytes, the substitution lengths `setSubstChars()` accepts and the SBCS table.\n";
echo "pub static CONVERTERS: &[Conv] = &[\n";
$index = [];
foreach ($converters as $i => [$name]) $index[$name] = $i;
foreach ($converters as $i => [$name, $type, $subst, $lens, $aliases]) {
    $table = isset($tables[$i]) ? "Some(&SBCS_$i)" : 'None';
    printf("    Conv { name: %s, ty: %d, subst: &[%s], subst_lens: &[%s], aliases: &[%s], sbcs: %s },\n",
        $q($name), $type, $hex($subst), implode(', ', $lens), implode(', ', array_map($q, $aliases)), $table);
}
echo "];\n\n";
echo "/// Every alias (lowercased), the converter ICU opens for it and whether it\n/// warns that the alias is ambiguous, sorted.\n";
ksort($aliasRows, SORT_STRING);
echo "pub static ALIASES: &[(&str, usize, bool)] = &[\n";
foreach ($aliasRows as $k => [$chosen, $amb]) printf("    (%s, %d, %s),\n", $q($k), $index[$chosen], $amb ? 'true' : 'false');
echo "];\n\n";
foreach ($tables as $i => [$decode, $over]) {
    echo "static SBCS_$i: Sbcs = Sbcs {\n    decode: [\n";
    foreach (array_chunk($decode, 8) as $chunk) {
        echo "        ", implode(', ', array_map(fn($v) => $v === 'U' ? 'UNA' : ($v === 'I' ? 'ILL' : sprintf('0x%04X', $v)), $chunk)), ",\n";
    }
    echo "    ],\n    overrides: &[", implode(', ', array_map(fn($o) => sprintf('(0x%04X, %s)', $o[0], $o[1] === null ? 'None' : sprintf('Some(0x%02X)', $o[1])), $over)), "],\n};\n\n";
}
