<?php
// Dumps what IntlBreakIterator's factories resolve per locale in the stock
// php/ICU this project is measured against: the valid and actual locale
// `getLocale()` reports and which rule set ICU loaded (its `getRules()`
// source text, kept verbatim so `getRules()` and the rules constructor
// round-trip). Locales that resolve to root with no locale are left out.
//
//   php -n tools/intl-data/dump-breakiter.php > crates/rphp-ext-intl/src/breakiter/data.rs
$kinds = ['Word' => 'createWordInstance', 'Line' => 'createLineInstance', 'Sentence' => 'createSentenceInstance',
    'Character' => 'createCharacterInstance', 'Title' => 'createTitleInstance'];
$locales = ResourceBundle::getLocales('');
$locales[] = 'en_US_POSIX';
foreach (['ja', 'zh', 'ko', 'th', 'de', 'en'] as $base) {
    foreach (['@lb=strict', '@lb=normal', '@lb=loose'] as $kw) $locales[] = $base . $kw;
}
$locales = array_values(array_unique($locales));
sort($locales, SORT_STRING);
$rules = [];
$rows = [];
foreach ($kinds as $kind => $m) {
    foreach ($locales as $loc) {
        $b = IntlBreakIterator::$m($loc);
        $r = $b->getRules();
        if (!isset($rules[$r])) $rules[$r] = count($rules);
        $v = $b->getLocale(Locale::VALID_LOCALE);
        $a = $b->getLocale(Locale::ACTUAL_LOCALE);
        $root = IntlBreakIterator::$m('root')->getRules();
        if ($v === '' && $a === '' && $r === $root) continue;
        $rows[] = [$kind, $loc, $v, $a, $rules[$r]];
    }
    $rootRules[$kind] = $rules[IntlBreakIterator::$m('root')->getRules()];
}
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';
echo "// @generated by tools/intl-data/dump-breakiter.php from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " — do not edit.\n";
echo "//! The break iterator factories per locale: valid/actual locale and rule set.\n\n";
echo "use super::Kind;\n\n";
echo "/// The rule sources ICU's `getRules()` reports, by index.\n";
echo "pub static RULES: &[&str] = &[\n";
foreach ($rules as $r => $i) echo "    ", $q($r), ",\n";
echo "];\n\n";
echo "/// The root rule set of each kind.\n";
echo "pub static ROOT: &[(Kind, usize)] = &[\n";
foreach ($rootRules as $k => $i) echo "    (Kind::$k, $i),\n";
echo "];\n\n";
echo "/// `(kind, requested locale, valid, actual, rules)`, sorted by kind then locale.\n";
echo "pub static LOCALES: &[(Kind, &str, &str, &str, usize)] = &[\n";
foreach ($rows as [$k, $l, $v, $a, $i]) echo "    (Kind::$k, ", $q($l), ", ", $q($v), ", ", $q($a), ", $i),\n";
echo "];\n";
