<?php
// Dumps ICU's timezone metadata from the stock php/ICU this project is
// measured against: every zone ID ICU knows with its canonical ID, its
// region, its IANA ID and its Windows ID, plus the equivalence groups
// (`countEquivalentIDs`/`getEquivalentID`) and the Windows → IANA map.
// Offsets and DST rules are not dumped: rphp reads those from php's own
// timezone database through ext/date.
//
//   php -n tools/intl-data/dump-tz.php > crates/rphp-ext-intl/src/data/tz.rs
$all = iterator_to_array(IntlTimeZone::createEnumeration());
sort($all);
$q = fn($s) => '"' . addcslashes($s, "\\\"\0..\37") . '"';

// the equivalence groups, keyed by their first member
$groups = []; $group_of = [];
foreach ($all as $id) {
    if (isset($group_of[$id])) continue;
    $n = IntlTimeZone::countEquivalentIDs($id);
    $members = [];
    for ($i = 0; $i < $n; $i++) $members[] = IntlTimeZone::getEquivalentID($id, $i);
    if (!$members) $members = [$id];
    sort($members);
    $gi = count($groups);
    $groups[] = $members;
    foreach ($members as $m) $group_of[$m] = $gi;
}

echo "//! Generated by `tools/intl-data/dump-tz.php` from php ", PHP_VERSION, " / ICU ", INTL_ICU_VERSION, " (tzdata ", IntlTimeZone::getTZDataVersion(), ") — do not edit.\n";
echo "//! ICU's timezone metadata: every zone ID with its canonical ID, region, IANA ID and Windows ID, the\n//! equivalence groups `IntlTimeZone::getEquivalentID()` walks, and the Windows → IANA map per region.\n\n";

echo "/// One zone: (id, canonical id, region or \"\", iana id or \"\", windows id or \"\", equivalence group,\n/// raw offset in ms, DST saving in ms, whether it observes daylight time).\npub static ZONES: &[(&str, &str, &str, &str, &str, u16, i32, i32, bool)] = &[\n";
foreach ($all as $id) {
    $canon = IntlTimeZone::getCanonicalID($id, $isSystem);
    $region = IntlTimeZone::getRegion($id);
    $iana = IntlTimeZone::getIanaID($id);
    $win = IntlTimeZone::getWindowsID($id);
    $z = IntlTimeZone::createTimeZone($id);
    echo "    (", $q($id), ", ", $q($canon === false ? '' : $canon), ", ", $q($region === false ? '' : $region), ", ", $q($iana === false ? '' : $iana), ", ", $q($win === false ? '' : $win), ", ", $group_of[$id], ", ", $z->getRawOffset(), ", ", $z->getDSTSavings(), ", ", $z->useDaylightTime() ? 'true' : 'false', "),\n";
}
echo "];\n\n";

echo "/// The equivalence groups, each sorted; a zone's group is its index in `ZONES`.\npub static GROUPS: &[&[&str]] = &[\n";
foreach ($groups as $g) { echo "    &[", implode(", ", array_map($q, $g)), "],\n"; }
echo "];\n\n";

// Windows → IANA, for every region a zone of the group names, plus the default
$wins = [];
foreach ($all as $id) { $w = IntlTimeZone::getWindowsID($id); if ($w !== false) $wins[$w] = true; }
$regions = array_unique(array_filter(array_map(fn($id) => IntlTimeZone::getRegion($id), $all), fn($r) => $r !== false));
sort($regions);
echo "/// Windows ID → IANA ID: the default (region \"\") and the per-region overrides.\npub static WINDOWS: &[(&str, &str, &str)] = &[\n";
foreach (array_keys($wins) as $w) {
    $def = IntlTimeZone::getIDForWindowsID($w);
    if ($def !== false) echo "    (", $q($w), ", \"\", ", $q($def), "),\n";
    foreach ($regions as $r) {
        $id = IntlTimeZone::getIDForWindowsID($w, $r);
        if ($id !== false && $id !== $def) echo "    (", $q($w), ", ", $q($r), ", ", $q($id), "),\n";
    }
}
echo "];\n\n";

echo "/// `IntlTimeZone::getTZDataVersion()`.\npub static TZDATA_VERSION: &str = ", $q(IntlTimeZone::getTZDataVersion()), ";\n\n";

// the canonical zones by type, for createTimeZoneIDEnumeration
foreach ([['CANONICAL', IntlTimeZone::TYPE_CANONICAL], ['CANONICAL_LOCATION', IntlTimeZone::TYPE_CANONICAL_LOCATION]] as [$name, $type]) {
    $ids = iterator_to_array(IntlTimeZone::createTimeZoneIDEnumeration($type));
    sort($ids);
    echo "/// The zone IDs of `IntlTimeZone::TYPE_$name`.\npub static TYPE_$name: &[&str] = &[\n";
    foreach ($ids as $id) echo "    ", $q($id), ",\n";
    echo "];\n\n";
}
