<?php
// Turns UTS #39's confusables.txt (Unicode 17.0.0, the security data ICU
// 78 builds its Spoofchecker from) into the prototype table behind
// Spoofchecker's skeletons: each source code point and the string it maps
// to, sorted by code point.
//
//   curl -O https://www.unicode.org/Public/17.0.0/security/confusables.txt
//   php -n tools/intl-data/gen-confusables.php confusables.txt > crates/rphp-ext-intl/src/spoof/data.rs
$rows = [];
foreach (file($argv[1]) as $line) {
    $line = preg_replace('/#.*/', '', $line);
    if (!preg_match('/^\s*([0-9A-F]+)\s*;\s*([0-9A-F ]+?)\s*;\s*MA/', $line, $m)) continue;
    $target = '';
    foreach (preg_split('/\s+/', $m[2]) as $h) $target .= sprintf('\u{%X}', hexdec($h));
    $rows[hexdec($m[1])] = $target;
}
ksort($rows);
echo "// @generated by tools/intl-data/gen-confusables.php from UTS #39 confusables.txt 17.0.0 — do not edit.\n";
echo "//! The confusable prototypes: `(code point, prototype)`, sorted.\n\n";
echo "pub static CONFUSABLES: &[(u32, &str)] = &[\n";
foreach ($rows as $cp => $t) printf("    (0x%X, \"%s\"),\n", $cp, $t);
echo "];\n";
