#!/usr/bin/env python3
"""Regenerate the data tables in this directory from a php-src checkout.

    python3 gen_tables.py /path/to/php-src

Reads (php-8.5.0):
  ext/mbstring/unicode_data.h                       -> casemap.rs, props.rs
  ext/mbstring/libmbfl/mbfl/eaw_table.h             -> eaw.rs
  ext/mbstring/rare_cp_bitvec.h                     -> rare_cp.rs
  ext/mbstring/libmbfl/filters/mbfilter_singlebyte.c -> singlebyte.rs
  ext/mbstring/libmbfl/filters/html_entities.c      -> html_entities.rs
  ext/mbstring/libmbfl/filters/unicode_table_jis.h,
  unicode_table_cp932_ext.h, cp932_table.h, mbfilter_cjk.c -> jis.rs

The C sources store the case tables in minimal-perfect-hash order; here they
are emitted sorted by code point so Rust can binary-search them. Nothing
else is transformed: every value is php-src's.
"""
import os
import re
import sys

root = sys.argv[1]
here = os.path.dirname(os.path.abspath(__file__))

HEADER = "// Generated by gen_tables.py from php-src {src}; do not edit by hand.\n"


def read(path):
    with open(os.path.join(root, path), encoding="utf-8", errors="replace") as f:
        return f.read()


def c_array(src, name):
    m = re.search(r"\b" + re.escape(name) + r"\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit("array not found: " + name)
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
    return [int(x, 0) for x in re.findall(r"0[xX][0-9a-fA-F]+|\d+", body)]


def c_scalar(src, name):
    m = re.search(r"\b" + re.escape(name) + r"\s*=\s*(\d+)", src)
    return int(m.group(1))


def write(name, text):
    with open(os.path.join(here, name), "w") as f:
        f.write(text)


def fmt_pairs(pairs, per_line=4):
    out = []
    for i in range(0, len(pairs), per_line):
        out.append("    " + " ".join("(0x{:x}, 0x{:x}),".format(a, b) for a, b in pairs[i:i + per_line]))
    return "\n".join(out)


def fmt_nums(nums, per_line=8, width=0):
    out = []
    for i in range(0, len(nums), per_line):
        out.append("    " + " ".join(("0x{:0" + str(width) + "x},").format(n) for n in nums[i:i + per_line]))
    return "\n".join(out)


# ---- case mapping -----------------------------------------------------------
ud = read("ext/mbstring/unicode_data.h")
parts = [HEADER.format(src="ext/mbstring/unicode_data.h")]
parts.append("//! Case-mapping tables (`unicode_data.h`): simple mappings as sorted\n"
             "//! `(code, mapping)` pairs; a mapping above `0xFFFFFF` encodes a special\n"
             "//! casing sequence (`len << 24 | index` into [`EXTRA`]).\n")
for kind in ("upper", "lower", "title", "fold"):
    vals = c_array(ud, "_uccase_%s_table" % kind)
    size = c_scalar(ud, "_uccase_%s_table_size" % kind)
    assert len(vals) == 2 * size, (kind, len(vals), size)
    pairs = sorted((vals[2 * i], vals[2 * i + 1]) for i in range(size))
    codes = [p[0] for p in pairs]
    assert len(set(codes)) == len(codes), "duplicate code in " + kind
    parts.append("/// `_uccase_%s_table`, sorted by code point.\npub static %s: &[(u32, u32)] = &[\n%s\n];\n"
                 % (kind, kind.upper(), fmt_pairs(pairs)))
extra = c_array(ud, "_uccase_extra_table")
parts.append("/// `_uccase_extra_table`: at `index` the simple mapping, followed by the\n"
             "/// `len` code points of the full mapping.\npub static EXTRA: &[u32] = &[\n%s\n];\n" % fmt_nums(extra))
write("casemap.rs", "\n".join(parts))

# ---- properties -------------------------------------------------------------
offsets = c_array(ud, "_ucprop_offsets")
ranges = c_array(ud, "_ucprop_ranges")
size = c_scalar(ud, "_ucprop_size")


def prop_ranges(n):
    lo, hi = offsets[n], offsets[n + 1]
    seg = ranges[lo:hi]
    return [(seg[i], seg[i + 1]) for i in range(0, len(seg), 2)]


names = {35: "CASED", 36: "CASE_IGNORABLE"}
parts = [HEADER.format(src="ext/mbstring/unicode_data.h"),
         "//! Unicode property ranges (`_ucprop_ranges`): inclusive `(first, last)`\n"
         "//! pairs, sorted, for the properties the case converter consults.\n"]
for n, nm in names.items():
    rs = prop_ranges(n)
    parts.append("/// Property %d (`UC_%s`).\npub static %s: &[(u32, u32)] = &[\n%s\n];\n" % (n, nm, nm, fmt_pairs(rs)))
write("props.rs", "\n".join(parts))

# ---- east asian width -------------------------------------------------------
eaw = read("ext/mbstring/libmbfl/mbfl/eaw_table.h")
vals = c_array(eaw, "mbfl_eaw_table")
first = int(re.search(r"FIRST_DOUBLEWIDTH_CODEPOINT\s+(0x[0-9a-fA-F]+)", eaw).group(1), 16)
pairs = [(vals[i], vals[i + 1]) for i in range(0, len(vals), 2)]
write("eaw.rs", HEADER.format(src="ext/mbstring/libmbfl/mbfl/eaw_table.h") +
      "//! php's East Asian Width table (`eaw_table.h`): inclusive code-point ranges\n"
      "//! displayed double-width.\n\n"
      "/// `FIRST_DOUBLEWIDTH_CODEPOINT`.\npub const FIRST_DOUBLEWIDTH: u32 = 0x%x;\n\n"
      "/// `mbfl_eaw_table`.\npub static EAW: &[(u32, u32)] = &[\n%s\n];\n" % (first, fmt_pairs(pairs)))

# ---- rare code points --------------------------------------------------------
rc = read("ext/mbstring/rare_cp_bitvec.h")
vals = c_array(rc, "rare_codepoint_bitvec")
assert len(vals) == 2048, len(vals)
write("rare_cp.rs", HEADER.format(src="ext/mbstring/rare_cp_bitvec.h") +
      "//! `rare_codepoint_bitvec`: one bit per code point U+0000..U+FFFF, set when\n"
      "//! the code point is 'rare' for encoding detection (`mb_detect_encoding`).\n\n"
      "/// The bit vector, 32 code points per word.\npub static RARE: &[u32; 2048] = &[\n%s\n];\n" % fmt_nums(vals, 8, 8))

# ---- single-byte tables ------------------------------------------------------
sb = read("ext/mbstring/libmbfl/filters/mbfilter_singlebyte.c")
parts = [HEADER.format(src="ext/mbstring/libmbfl/filters/mbfilter_singlebyte.c"),
         "//! Single-byte charset tables (`mbfilter_singlebyte.c`): the Unicode code\n"
         "//! point of each byte from the table's first byte upward, `0` = unmapped.\n"]
for m in re.finditer(r"static const unsigned short (\w+)_ucs_table\[\] = \{(.*?)\};", sb, re.S):
    nm, body = m.group(1), m.group(2)
    vals = [int(x, 0) for x in re.findall(r"0[xX][0-9a-fA-F]+", body)]
    parts.append("/// `%s_ucs_table`.\npub static %s: &[u16] = &[\n%s\n];\n" % (nm, nm.upper(), fmt_nums(vals, 8, 4)))
m = re.search(r"static const unsigned char ucs_armscii8_table\[\] = \{(.*?)\};", sb, re.S)
vals = [int(x, 0) for x in re.findall(r"0[xX][0-9a-fA-F]+", m.group(1))]
parts.append("/// `ucs_armscii8_table`: bytes for U+0028..U+002F.\npub static UCS_ARMSCII8: &[u8] = &[\n%s\n];\n" % fmt_nums(vals, 8, 2))
write("singlebyte.rs", "\n".join(parts))

# ---- html entities -----------------------------------------------------------
he = read("ext/mbstring/libmbfl/filters/html_entities.c")
ents = re.findall(r'\{"(\w+)",\s*(\d+)\}', he)
lines = ["    (\"%s\", %s)," % (n, c) for n, c in ents]
write("html_entities.rs", HEADER.format(src="ext/mbstring/libmbfl/filters/html_entities.c") +
      "//! `mbfl_html_entity_list`: the named entities the `HTML-ENTITIES` codec\n"
      "//! knows, in php's table order (which decides encoding when two names map\n"
      "//! to one code point).\n\n"
      "/// `(name, code point)` in table order.\npub static ENTITIES: &[(&str, u32)] = &[\n%s\n];\n" % "\n".join(lines))
# ---- JIS X 0208 / 0212 / CP932 ------------------------------------------------
jis = read("ext/mbstring/libmbfl/filters/unicode_table_jis.h")
ext = read("ext/mbstring/libmbfl/filters/unicode_table_cp932_ext.h")
cp932 = read("ext/mbstring/libmbfl/filters/cp932_table.h")
cjk = read("ext/mbstring/libmbfl/filters/mbfilter_cjk.c")


def c_array_signed16(src, name):
    m = re.search(r"\b" + re.escape(name) + r"\[\]\s*=\s*\{(.*?)\};", src, re.S)
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
    out = []
    for tok in re.findall(r"-?0[xX][0-9a-fA-F]+|-?\d+", body):
        v = int(tok, 0)
        out.append(v & 0xFFFF)
    return out


def pairs_array(src, name):
    m = re.search(r"\b" + re.escape(name) + r"\[\]\[2\]\s*=\s*\{(.*?)\};", src, re.S)
    return [(int(a, 0), int(b, 0)) for a, b in re.findall(r"\{\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*\}", m.group(1))]


parts = [HEADER.format(src="ext/mbstring/libmbfl/filters/{unicode_table_jis.h,unicode_table_cp932_ext.h,cp932_table.h,mbfilter_cjk.c}"),
         "//! JIS X 0208 / JIS X 0212 / CP932 tables: code point per 94x94 cell\n"
         "//! (`0` = unassigned), the reverse tables keyed by code-point block\n"
         "//! (values are JIS codes, `0x8080 |` for JIS X 0212, bytes below 0x100 for\n"
         "//! JIS X 0201), the CP932 extension rows and the Shift_JIS byte decoders.\n"]
for nm, rs in [("jisx0208_ucs_table", "JISX0208"), ("jisx0212_ucs_table", "JISX0212"),
               ("ucs_a1_jis_table", "UCS_A1_JIS"), ("ucs_a2_jis_table", "UCS_A2_JIS"),
               ("ucs_i_jis_table", "UCS_I_JIS"), ("ucs_r_jis_table", "UCS_R_JIS")]:
    vals = c_array(jis, nm)
    parts.append("/// `%s`.\npub static %s: &[u16] = &[\n%s\n];\n" % (nm, rs, fmt_nums(vals, 8, 4)))
for nm, rs in [("cp932ext1_ucs_table", "CP932EXT1"), ("cp932ext2_ucs_table", "CP932EXT2"), ("cp932ext3_ucs_table", "CP932EXT3")]:
    vals = c_array(ext, nm)
    parts.append("/// `%s`.\npub static %s: &[u16] = &[\n%s\n];\n" % (nm, rs, fmt_nums(vals, 8, 4)))
for nm, rs in [("cp932ext1_ucs_table_paired_sorted", "CP932EXT1_PAIRED"), ("cp932ext3_ucs_table_paired_sorted", "CP932EXT3_PAIRED")]:
    ps = pairs_array(ext, nm)
    parts.append("/// `%s`: `(code point, index)` sorted by code point.\npub static %s: &[(u16, u16)] = &[\n%s\n];\n" % (nm, rs, fmt_pairs(ps, 6)))
vals = c_array(cp932, "cp932ext3_eucjp_table")
parts.append("/// `cp932ext3_eucjp_table`: EUC-JP codes of the CP932 IBM extension rows.\npub static CP932EXT3_EUCJP: &[u16] = &[\n%s\n];\n" % fmt_nums(vals, 8, 4))
for nm, rs in [("sjis_decode_tbl1", "SJIS_DECODE_TBL1"), ("sjis_decode_tbl2", "SJIS_DECODE_TBL2"), ("sjis_mobile_decode_tbl1", "SJIS_MOBILE_DECODE_TBL1")]:
    vals = c_array_signed16(cjk, nm)
    assert len(vals) == 256, (nm, len(vals))
    parts.append("/// `%s` (as the C `unsigned short`s, negatives wrapped).\npub static %s: &[u16; 256] = &[\n%s\n];\n" % (nm, rs, fmt_nums(vals, 8, 4)))
write("jis.rs", "\n".join(parts))
print("ok")
